-- GENERATED by threepoint/kernel_lean.py; do not edit
import Thomson.ThreePoint.Kernel.Defs

set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false

/-! # Task 1c: the entries of `Acomb 0 u` — GENERATED

Each entry is a polynomial in `u` with rational coefficients: the `√2` of the cross chords
cancels (`cU_sq`). -/

namespace Thomson

theorem Bpoly_0_0_0 : Bpoly 0 0 0 = 0 := rfl

theorem Bpoly_0_0_1 : Bpoly 0 0 1 = -(4743/10000 : ℝ) * ((1 : ℝ) + (-2 : ℝ) * uStar + (3 : ℝ) * uStar ^ 2) := rfl

theorem Bpoly_0_0_2 : Bpoly 0 0 2 = 0 := rfl

theorem Bpoly_0_0_3 : Bpoly 0 0 3 = -(609/5000 : ℝ) * ((3 : ℝ) + (-12 : ℝ) * uStar + (42 : ℝ) * uStar ^ 2 + (-60 : ℝ) * uStar ^ 3 + (35 : ℝ) * uStar ^ 4) := rfl

theorem Bpoly_0_0_4 : Bpoly 0 0 4 = -(1249/10000 : ℝ) * ((5 : ℝ) * uStar + (-20 : ℝ) * uStar ^ 2 + (30 : ℝ) * uStar ^ 3 + (-20 : ℝ) * uStar ^ 4 + (5 : ℝ) * uStar ^ 5) := rfl

theorem Bpoly_0_0_5 : Bpoly 0 0 5 = -(6139/100000 : ℝ) * ((5 : ℝ) + (-30 : ℝ) * uStar + (165 : ℝ) * uStar ^ 2 + (-460 : ℝ) * uStar ^ 3 + (735 : ℝ) * uStar ^ 4 + (-630 : ℝ) * uStar ^ 5 + (231 : ℝ) * uStar ^ 6) := rfl

theorem Bpoly_0_0_6 : Bpoly 0 0 6 = -(6233/100000 : ℝ) * ((21 : ℝ) * uStar + (-126 : ℝ) * uStar ^ 2 + (385 : ℝ) * uStar ^ 3 + (-700 : ℝ) * uStar ^ 4 + (735 : ℝ) * uStar ^ 5 + (-406 : ℝ) * uStar ^ 6 + (91 : ℝ) * uStar ^ 7) := rfl

theorem Bpoly_0_0_7 : Bpoly 0 0 7 = -(1541/50000 : ℝ) * ((9 : ℝ) + (-72 : ℝ) * uStar + (532 : ℝ) * uStar ^ 2 + (-2184 : ℝ) * uStar ^ 3 + (5670 : ℝ) * uStar ^ 4 + (-9464 : ℝ) * uStar ^ 5 + (9940 : ℝ) * uStar ^ 6 + (-6008 : ℝ) * uStar ^ 7 + (1609 : ℝ) * uStar ^ 8) := rfl

theorem Bpoly_0_0_8 : Bpoly 0 0 8 = 0 := rfl

theorem Bpoly_0_1_0 : Bpoly 0 1 0 = (1 : ℝ) * ((1 : ℝ)) := rfl

theorem Bpoly_0_1_1 : Bpoly 0 1 1 = 0 := rfl

theorem Bpoly_0_1_2 : Bpoly 0 1 2 = 0 := rfl

theorem Bpoly_0_1_3 : Bpoly 0 1 3 = 0 := rfl

theorem Bpoly_0_1_4 : Bpoly 0 1 4 = 0 := rfl

theorem Bpoly_0_1_5 : Bpoly 0 1 5 = 0 := rfl

theorem Bpoly_0_1_6 : Bpoly 0 1 6 = 0 := rfl

theorem Bpoly_0_1_7 : Bpoly 0 1 7 = 0 := rfl

theorem Bpoly_0_1_8 : Bpoly 0 1 8 = 0 := rfl

theorem Bpoly_0_2_0 : Bpoly 0 2 0 = 0 := rfl

theorem Bpoly_0_2_1 : Bpoly 0 2 1 = (4743/10000 : ℝ) * ((2 : ℝ)) := rfl

theorem Bpoly_0_2_2 : Bpoly 0 2 2 = 0 := rfl

theorem Bpoly_0_2_3 : Bpoly 0 2 3 = 0 := rfl

theorem Bpoly_0_2_4 : Bpoly 0 2 4 = 0 := rfl

theorem Bpoly_0_2_5 : Bpoly 0 2 5 = 0 := rfl

theorem Bpoly_0_2_6 : Bpoly 0 2 6 = 0 := rfl

theorem Bpoly_0_2_7 : Bpoly 0 2 7 = 0 := rfl

theorem Bpoly_0_2_8 : Bpoly 0 2 8 = 0 := rfl

theorem Bpoly_0_3_0 : Bpoly 0 3 0 = 0 := rfl

theorem Bpoly_0_3_1 : Bpoly 0 3 1 = 0 := rfl

theorem Bpoly_0_3_2 : Bpoly 0 3 2 = (1 : ℝ) * ((1 : ℝ)) := rfl

theorem Bpoly_0_3_3 : Bpoly 0 3 3 = 0 := rfl

theorem Bpoly_0_3_4 : Bpoly 0 3 4 = 0 := rfl

theorem Bpoly_0_3_5 : Bpoly 0 3 5 = 0 := rfl

theorem Bpoly_0_3_6 : Bpoly 0 3 6 = 0 := rfl

theorem Bpoly_0_3_7 : Bpoly 0 3 7 = 0 := rfl

theorem Bpoly_0_3_8 : Bpoly 0 3 8 = 0 := rfl

theorem Bpoly_0_4_0 : Bpoly 0 4 0 = 0 := rfl

theorem Bpoly_0_4_1 : Bpoly 0 4 1 = 0 := rfl

theorem Bpoly_0_4_2 : Bpoly 0 4 2 = 0 := rfl

theorem Bpoly_0_4_3 : Bpoly 0 4 3 = (609/5000 : ℝ) * ((8 : ℝ)) := rfl

theorem Bpoly_0_4_4 : Bpoly 0 4 4 = 0 := rfl

theorem Bpoly_0_4_5 : Bpoly 0 4 5 = 0 := rfl

theorem Bpoly_0_4_6 : Bpoly 0 4 6 = 0 := rfl

theorem Bpoly_0_4_7 : Bpoly 0 4 7 = 0 := rfl

theorem Bpoly_0_4_8 : Bpoly 0 4 8 = 0 := rfl

theorem Bpoly_0_5_0 : Bpoly 0 5 0 = 0 := rfl

theorem Bpoly_0_5_1 : Bpoly 0 5 1 = 0 := rfl

theorem Bpoly_0_5_2 : Bpoly 0 5 2 = 0 := rfl

theorem Bpoly_0_5_3 : Bpoly 0 5 3 = 0 := rfl

theorem Bpoly_0_5_4 : Bpoly 0 5 4 = (1249/10000 : ℝ) * ((8 : ℝ)) := rfl

theorem Bpoly_0_5_5 : Bpoly 0 5 5 = 0 := rfl

theorem Bpoly_0_5_6 : Bpoly 0 5 6 = 0 := rfl

theorem Bpoly_0_5_7 : Bpoly 0 5 7 = 0 := rfl

theorem Bpoly_0_5_8 : Bpoly 0 5 8 = 0 := rfl

theorem Bpoly_0_6_0 : Bpoly 0 6 0 = 0 := rfl

theorem Bpoly_0_6_1 : Bpoly 0 6 1 = 0 := rfl

theorem Bpoly_0_6_2 : Bpoly 0 6 2 = 0 := rfl

theorem Bpoly_0_6_3 : Bpoly 0 6 3 = 0 := rfl

theorem Bpoly_0_6_4 : Bpoly 0 6 4 = 0 := rfl

theorem Bpoly_0_6_5 : Bpoly 0 6 5 = (6139/100000 : ℝ) * ((16 : ℝ)) := rfl

theorem Bpoly_0_6_6 : Bpoly 0 6 6 = 0 := rfl

theorem Bpoly_0_6_7 : Bpoly 0 6 7 = 0 := rfl

theorem Bpoly_0_6_8 : Bpoly 0 6 8 = 0 := rfl

theorem Bpoly_0_7_0 : Bpoly 0 7 0 = 0 := rfl

theorem Bpoly_0_7_1 : Bpoly 0 7 1 = 0 := rfl

theorem Bpoly_0_7_2 : Bpoly 0 7 2 = 0 := rfl

theorem Bpoly_0_7_3 : Bpoly 0 7 3 = 0 := rfl

theorem Bpoly_0_7_4 : Bpoly 0 7 4 = 0 := rfl

theorem Bpoly_0_7_5 : Bpoly 0 7 5 = 0 := rfl

theorem Bpoly_0_7_6 : Bpoly 0 7 6 = (6233/100000 : ℝ) * ((16 : ℝ)) := rfl

theorem Bpoly_0_7_7 : Bpoly 0 7 7 = 0 := rfl

theorem Bpoly_0_7_8 : Bpoly 0 7 8 = 0 := rfl

theorem Bpoly_0_8_0 : Bpoly 0 8 0 = 0 := rfl

theorem Bpoly_0_8_1 : Bpoly 0 8 1 = 0 := rfl

theorem Bpoly_0_8_2 : Bpoly 0 8 2 = 0 := rfl

theorem Bpoly_0_8_3 : Bpoly 0 8 3 = 0 := rfl

theorem Bpoly_0_8_4 : Bpoly 0 8 4 = 0 := rfl

theorem Bpoly_0_8_5 : Bpoly 0 8 5 = 0 := rfl

theorem Bpoly_0_8_6 : Bpoly 0 8 6 = 0 := rfl

theorem Bpoly_0_8_7 : Bpoly 0 8 7 = (1541/50000 : ℝ) * ((32 : ℝ)) := rfl

theorem Bpoly_0_8_8 : Bpoly 0 8 8 = 0 := rfl

set_option maxHeartbeats 1000000 in
theorem AcombN_0_0_0 (u : ℝ) : AcombN 0 0 0 u = (512 : ℝ) := by
  simp only [AcombN, S3N, Q3, tA, tD, tN, tF]
  linear_combination (0) * cU_sq u

set_option maxHeartbeats 1000000 in
theorem AcombN_0_0_1 (u : ℝ) : AcombN 0 0 1 u = 0 := by
  simp only [AcombN, S3N, Q3, tA, tD, tN, tF]
  linear_combination (0) * cU_sq u

set_option maxHeartbeats 1000000 in
theorem AcombN_0_0_2 (u : ℝ) : AcombN 0 0 2 u = (768 : ℝ) * u ^ 2 + (-512 : ℝ) * u + (256 : ℝ) := by
  simp only [AcombN, S3N, Q3, tA, tD, tN, tF]
  linear_combination ((256 : ℝ)) * cU_sq u

set_option maxHeartbeats 1000000 in
theorem AcombN_0_0_3 (u : ℝ) : AcombN 0 0 3 u = 0 := by
  simp only [AcombN, S3N, Q3, tA, tD, tN, tF]
  linear_combination ((-768 : ℝ) * u) * cU_sq u

set_option maxHeartbeats 1000000 in
theorem AcombN_0_0_4 (u : ℝ) : AcombN 0 0 4 u = (2240 : ℝ) * u ^ 4 + (-3840 : ℝ) * u ^ 3 + (2688 : ℝ) * u ^ 2 + (-768 : ℝ) * u + (192 : ℝ) := by
  simp only [AcombN, S3N, Q3, tA, tD, tN, tF]
  linear_combination ((1664 : ℝ) * u ^ 2 + (-256 : ℝ) * u + (256 : ℝ) * cU u ^ 2 + (128 : ℝ)) * cU_sq u

set_option maxHeartbeats 1000000 in
theorem AcombN_0_0_5 (u : ℝ) : AcombN 0 0 5 u = (320 : ℝ) * u ^ 5 + (-1280 : ℝ) * u ^ 4 + (1920 : ℝ) * u ^ 3 + (-1280 : ℝ) * u ^ 2 + (320 : ℝ) * u := by
  simp only [AcombN, S3N, Q3, tA, tD, tN, tF]
  linear_combination ((-3200 : ℝ) * u ^ 3 + (1280 : ℝ) * u ^ 2 + (-1280 : ℝ) * u * cU u ^ 2 + (-640 : ℝ) * u) * cU_sq u

set_option maxHeartbeats 1000000 in
theorem AcombN_0_0_6 (u : ℝ) : AcombN 0 0 6 u = (7392 : ℝ) * u ^ 6 + (-20160 : ℝ) * u ^ 5 + (23520 : ℝ) * u ^ 4 + (-14720 : ℝ) * u ^ 3 + (5280 : ℝ) * u ^ 2 + (-960 : ℝ) * u + (160 : ℝ) := by
  simp only [AcombN, S3N, Q3, tA, tD, tN, tF]
  linear_combination ((5824 : ℝ) * u ^ 4 + (-4096 : ℝ) * u ^ 3 + (3968 : ℝ) * u ^ 2 * cU u ^ 2 + (2304 : ℝ) * u ^ 2 + (-256 : ℝ) * u * cU u ^ 2 + (-256 : ℝ) * u + (256 : ℝ) * cU u ^ 4 + (128 : ℝ) * cU u ^ 2 + (64 : ℝ)) * cU_sq u

set_option maxHeartbeats 1000000 in
theorem AcombN_0_0_7 (u : ℝ) : AcombN 0 0 7 u = (2912 : ℝ) * u ^ 7 + (-12992 : ℝ) * u ^ 6 + (23520 : ℝ) * u ^ 5 + (-22400 : ℝ) * u ^ 4 + (12320 : ℝ) * u ^ 3 + (-4032 : ℝ) * u ^ 2 + (672 : ℝ) * u := by
  simp only [AcombN, S3N, Q3, tA, tD, tN, tF]
  linear_combination ((-10304 : ℝ) * u ^ 5 + (10752 : ℝ) * u ^ 4 + (-9856 : ℝ) * u ^ 3 * cU u ^ 2 + (-7168 : ℝ) * u ^ 3 + (1792 : ℝ) * u ^ 2 * cU u ^ 2 + (1792 : ℝ) * u ^ 2 + (-1792 : ℝ) * u * cU u ^ 4 + (-896 : ℝ) * u * cU u ^ 2 + (-448 : ℝ) * u) * cU_sq u

set_option maxHeartbeats 1000000 in
theorem AcombN_0_0_8 (u : ℝ) : AcombN 0 0 8 u = (25744 : ℝ) * u ^ 8 + (-96128 : ℝ) * u ^ 7 + (159040 : ℝ) * u ^ 6 + (-151424 : ℝ) * u ^ 5 + (90720 : ℝ) * u ^ 4 + (-34944 : ℝ) * u ^ 3 + (8512 : ℝ) * u ^ 2 + (-1152 : ℝ) * u + (144 : ℝ) := by
  simp only [AcombN, S3N, Q3, tA, tD, tN, tF]
  linear_combination ((17952 : ℝ) * u ^ 6 + (-25280 : ℝ) * u ^ 5 + (21568 : ℝ) * u ^ 4 * cU u ^ 2 + (20192 : ℝ) * u ^ 4 + (-7424 : ℝ) * u ^ 3 * cU u ^ 2 + (-7808 : ℝ) * u ^ 3 + (7296 : ℝ) * u ^ 2 * cU u ^ 4 + (3968 : ℝ) * u ^ 2 * cU u ^ 2 + (2272 : ℝ) * u ^ 2 + (-256 : ℝ) * u * cU u ^ 4 + (-256 : ℝ) * u * cU u ^ 2 + (-192 : ℝ) * u + (256 : ℝ) * cU u ^ 6 + (128 : ℝ) * cU u ^ 4 + (64 : ℝ) * cU u ^ 2 + (32 : ℝ)) * cU_sq u

theorem AcombN_0_1_0 (u : ℝ) : AcombN 0 1 0 u = 0 := by
  rw [AcombN_symm]; exact AcombN_0_0_1 u

set_option maxHeartbeats 1000000 in
theorem AcombN_0_1_1 (u : ℝ) : AcombN 0 1 1 u = 0 := by
  simp only [AcombN, S3N, Q3, tA, tD, tN, tF]
  linear_combination (0) * cU_sq u

set_option maxHeartbeats 1000000 in
theorem AcombN_0_1_2 (u : ℝ) : AcombN 0 1 2 u = 0 := by
  simp only [AcombN, S3N, Q3, tA, tD, tN, tF]
  linear_combination (0) * cU_sq u

set_option maxHeartbeats 1000000 in
theorem AcombN_0_1_3 (u : ℝ) : AcombN 0 1 3 u = 0 := by
  simp only [AcombN, S3N, Q3, tA, tD, tN, tF]
  linear_combination (0) * cU_sq u

set_option maxHeartbeats 1000000 in
theorem AcombN_0_1_4 (u : ℝ) : AcombN 0 1 4 u = 0 := by
  simp only [AcombN, S3N, Q3, tA, tD, tN, tF]
  linear_combination (0) * cU_sq u

set_option maxHeartbeats 1000000 in
theorem AcombN_0_1_5 (u : ℝ) : AcombN 0 1 5 u = 0 := by
  simp only [AcombN, S3N, Q3, tA, tD, tN, tF]
  linear_combination (0) * cU_sq u

set_option maxHeartbeats 1000000 in
theorem AcombN_0_1_6 (u : ℝ) : AcombN 0 1 6 u = 0 := by
  simp only [AcombN, S3N, Q3, tA, tD, tN, tF]
  linear_combination (0) * cU_sq u

set_option maxHeartbeats 1000000 in
theorem AcombN_0_1_7 (u : ℝ) : AcombN 0 1 7 u = 0 := by
  simp only [AcombN, S3N, Q3, tA, tD, tN, tF]
  linear_combination (0) * cU_sq u

set_option maxHeartbeats 1000000 in
theorem AcombN_0_1_8 (u : ℝ) : AcombN 0 1 8 u = 0 := by
  simp only [AcombN, S3N, Q3, tA, tD, tN, tF]
  linear_combination (0) * cU_sq u

theorem AcombN_0_2_0 (u : ℝ) : AcombN 0 2 0 u = (768 : ℝ) * u ^ 2 + (-512 : ℝ) * u + (256 : ℝ) := by
  rw [AcombN_symm]; exact AcombN_0_0_2 u

theorem AcombN_0_2_1 (u : ℝ) : AcombN 0 2 1 u = 0 := by
  rw [AcombN_symm]; exact AcombN_0_1_2 u

set_option maxHeartbeats 1000000 in
theorem AcombN_0_2_2 (u : ℝ) : AcombN 0 2 2 u = (1152 : ℝ) * u ^ 4 + (-1536 : ℝ) * u ^ 3 + (1280 : ℝ) * u ^ 2 + (-512 : ℝ) * u + (128 : ℝ) := by
  simp only [AcombN, S3N, Q3, tA, tD, tN, tF]
  linear_combination ((704 : ℝ) * u ^ 2 + (-384 : ℝ) * u + (128 : ℝ) * cU u ^ 2 + (192 : ℝ)) * cU_sq u

set_option maxHeartbeats 1000000 in
theorem AcombN_0_2_3 (u : ℝ) : AcombN 0 2 3 u = 0 := by
  simp only [AcombN, S3N, Q3, tA, tD, tN, tF]
  linear_combination ((-960 : ℝ) * u ^ 3 + (384 : ℝ) * u ^ 2 + (-384 : ℝ) * u * cU u ^ 2 + (-192 : ℝ) * u) * cU_sq u

set_option maxHeartbeats 1000000 in
theorem AcombN_0_2_4 (u : ℝ) : AcombN 0 2 4 u = (3360 : ℝ) * u ^ 6 + (-8000 : ℝ) * u ^ 5 + (8992 : ℝ) * u ^ 4 + (-5760 : ℝ) * u ^ 3 + (2400 : ℝ) * u ^ 2 + (-576 : ℝ) * u + (96 : ℝ) := by
  simp only [AcombN, S3N, Q3, tA, tD, tN, tF]
  linear_combination ((3200 : ℝ) * u ^ 4 + (-3072 : ℝ) * u ^ 3 + (1152 : ℝ) * u ^ 2 * cU u ^ 2 + (2048 : ℝ) * u ^ 2 + (-256 : ℝ) * u * cU u ^ 2 + (-512 : ℝ) * u + (128 : ℝ) * cU u ^ 4 + (128 : ℝ) * cU u ^ 2 + (128 : ℝ)) * cU_sq u

set_option maxHeartbeats 1000000 in
theorem AcombN_0_2_5 (u : ℝ) : AcombN 0 2 5 u = (480 : ℝ) * u ^ 7 + (-2240 : ℝ) * u ^ 6 + (4320 : ℝ) * u ^ 5 + (-4480 : ℝ) * u ^ 4 + (2720 : ℝ) * u ^ 3 + (-960 : ℝ) * u ^ 2 + (160 : ℝ) * u := by
  simp only [AcombN, S3N, Q3, tA, tD, tN, tF]
  linear_combination ((-3840 : ℝ) * u ^ 5 + (2560 : ℝ) * u ^ 4 + (-3200 : ℝ) * u ^ 3 * cU u ^ 2 + (-1280 : ℝ) * u ^ 3 + (1280 : ℝ) * u ^ 2 * cU u ^ 2 + (-640 : ℝ) * u * cU u ^ 4 + (-640 : ℝ) * u * cU u ^ 2) * cU_sq u

set_option maxHeartbeats 1000000 in
theorem AcombN_0_2_6 (u : ℝ) : AcombN 0 2 6 u = (11088 : ℝ) * u ^ 8 + (-37632 : ℝ) * u ^ 7 + (59136 : ℝ) * u ^ 6 + (-55680 : ℝ) * u ^ 5 + (34400 : ℝ) * u ^ 4 + (-14080 : ℝ) * u ^ 3 + (3840 : ℝ) * u ^ 2 + (-640 : ℝ) * u + (80 : ℝ) := by
  simp only [AcombN, S3N, Q3, tA, tD, tN, tF]
  linear_combination ((10976 : ℝ) * u ^ 6 + (-18112 : ℝ) * u ^ 5 + (7872 : ℝ) * u ^ 4 * cU u ^ 2 + (18144 : ℝ) * u ^ 4 + (-4352 : ℝ) * u ^ 3 * cU u ^ 2 + (-9856 : ℝ) * u ^ 3 + (2304 : ℝ) * u ^ 2 * cU u ^ 4 + (2432 : ℝ) * u ^ 2 * cU u ^ 2 + (3424 : ℝ) * u ^ 2 + (-256 : ℝ) * u * cU u ^ 4 + (-256 : ℝ) * u * cU u ^ 2 + (-576 : ℝ) * u + (128 : ℝ) * cU u ^ 6 + (128 : ℝ) * cU u ^ 4 + (64 : ℝ) * cU u ^ 2 + (96 : ℝ)) * cU_sq u

set_option maxHeartbeats 1000000 in
theorem AcombN_0_2_7 (u : ℝ) : AcombN 0 2 7 u = (4368 : ℝ) * u ^ 9 + (-22400 : ℝ) * u ^ 8 + (49728 : ℝ) * u ^ 7 + (-63616 : ℝ) * u ^ 6 + (52640 : ℝ) * u ^ 5 + (-29568 : ℝ) * u ^ 4 + (11200 : ℝ) * u ^ 3 + (-2688 : ℝ) * u ^ 2 + (336 : ℝ) * u := by
  simp only [AcombN, S3N, Q3, tA, tD, tN, tF]
  linear_combination ((-11424 : ℝ) * u ^ 7 + (12096 : ℝ) * u ^ 6 + (-17472 : ℝ) * u ^ 5 * cU u ^ 2 + (-5152 : ℝ) * u ^ 5 + (12544 : ℝ) * u ^ 4 * cU u ^ 2 + (-2688 : ℝ) * u ^ 4 + (-7168 : ℝ) * u ^ 3 * cU u ^ 4 + (-8064 : ℝ) * u ^ 3 * cU u ^ 2 + (2912 : ℝ) * u ^ 3 + (1792 : ℝ) * u ^ 2 * cU u ^ 4 + (1792 : ℝ) * u ^ 2 * cU u ^ 2 + (-1344 : ℝ) * u ^ 2 + (-896 : ℝ) * u * cU u ^ 6 + (-896 : ℝ) * u * cU u ^ 4 + (-448 : ℝ) * u * cU u ^ 2 + (224 : ℝ) * u) * cU_sq u

set_option maxHeartbeats 1000000 in
theorem AcombN_0_2_8 (u : ℝ) : AcombN 0 2 8 u = (38616 : ℝ) * u ^ 10 + (-169936 : ℝ) * u ^ 9 + (347560 : ℝ) * u ^ 8 + (-434240 : ℝ) * u ^ 7 + (367024 : ℝ) * u ^ 6 + (-218848 : ℝ) * u ^ 5 + (93072 : ℝ) * u ^ 4 + (-27712 : ℝ) * u ^ 3 + (5624 : ℝ) * u ^ 2 + (-720 : ℝ) * u + (72 : ℝ) := by
  simp only [AcombN, S3N, Q3, tA, tD, tN, tF]
  linear_combination ((35312 : ℝ) * u ^ 8 + (-88640 : ℝ) * u ^ 7 + (35936 : ℝ) * u ^ 6 * cU u ^ 2 + (121888 : ℝ) * u ^ 6 + (-32704 : ℝ) * u ^ 5 * cU u ^ 2 + (-101888 : ℝ) * u ^ 5 + (19904 : ℝ) * u ^ 4 * cU u ^ 4 + (24160 : ℝ) * u ^ 4 * cU u ^ 2 + (57152 : ℝ) * u ^ 4 + (-7680 : ℝ) * u ^ 3 * cU u ^ 4 + (-8064 : ℝ) * u ^ 3 * cU u ^ 2 + (-20800 : ℝ) * u ^ 3 + (3968 : ℝ) * u ^ 2 * cU u ^ 6 + (4096 : ℝ) * u ^ 2 * cU u ^ 4 + (2336 : ℝ) * u ^ 2 * cU u ^ 2 + (4960 : ℝ) * u ^ 2 + (-256 : ℝ) * u * cU u ^ 6 + (-256 : ℝ) * u * cU u ^ 4 + (-192 : ℝ) * u * cU u ^ 2 + (-640 : ℝ) * u + (128 : ℝ) * cU u ^ 8 + (128 : ℝ) * cU u ^ 6 + (64 : ℝ) * cU u ^ 4 + (32 : ℝ) * cU u ^ 2 + (80 : ℝ)) * cU_sq u

theorem AcombN_0_3_0 (u : ℝ) : AcombN 0 3 0 u = 0 := by
  rw [AcombN_symm]; exact AcombN_0_0_3 u

theorem AcombN_0_3_1 (u : ℝ) : AcombN 0 3 1 u = 0 := by
  rw [AcombN_symm]; exact AcombN_0_1_3 u

theorem AcombN_0_3_2 (u : ℝ) : AcombN 0 3 2 u = 0 := by
  rw [AcombN_symm]; exact AcombN_0_2_3 u

set_option maxHeartbeats 1000000 in
theorem AcombN_0_3_3 (u : ℝ) : AcombN 0 3 3 u = 0 := by
  simp only [AcombN, S3N, Q3, tA, tD, tN, tF]
  linear_combination ((-576 : ℝ) * u ^ 4 + (1152 : ℝ) * u ^ 3 + (1152 : ℝ) * u ^ 2 * cU u ^ 2 + (-576 : ℝ) * u ^ 2) * cU_sq u

set_option maxHeartbeats 1000000 in
theorem AcombN_0_3_4 (u : ℝ) : AcombN 0 3 4 u = 0 := by
  simp only [AcombN, S3N, Q3, tA, tD, tN, tF]
  linear_combination ((-2112 : ℝ) * u ^ 5 + (3072 : ℝ) * u ^ 4 + (-2304 : ℝ) * u ^ 3 * cU u ^ 2 + (-2304 : ℝ) * u ^ 3 + (768 : ℝ) * u ^ 2 + (-384 : ℝ) * u * cU u ^ 4 + (-192 : ℝ) * u) * cU_sq u

set_option maxHeartbeats 1000000 in
theorem AcombN_0_3_5 (u : ℝ) : AcombN 0 3 5 u = 0 := by
  simp only [AcombN, S3N, Q3, tA, tD, tN, tF]
  linear_combination ((-2880 : ℝ) * u ^ 6 + (7680 : ℝ) * u ^ 5 + (3840 : ℝ) * u ^ 4 * cU u ^ 2 + (-7680 : ℝ) * u ^ 4 + (3840 : ℝ) * u ^ 3 + (1920 : ℝ) * u ^ 2 * cU u ^ 4 + (-960 : ℝ) * u ^ 2) * cU_sq u

set_option maxHeartbeats 1000000 in
theorem AcombN_0_3_6 (u : ℝ) : AcombN 0 3 6 u = 0 := by
  simp only [AcombN, S3N, Q3, tA, tD, tN, tF]
  linear_combination ((-6720 : ℝ) * u ^ 7 + (18432 : ℝ) * u ^ 6 + (-5760 : ℝ) * u ^ 5 * cU u ^ 2 + (-23040 : ℝ) * u ^ 5 + (15360 : ℝ) * u ^ 4 + (-5760 : ℝ) * u ^ 3 * cU u ^ 4 + (-5760 : ℝ) * u ^ 3 + (1152 : ℝ) * u ^ 2 + (-384 : ℝ) * u * cU u ^ 6 + (-192 : ℝ) * u) * cU_sq u

set_option maxHeartbeats 1000000 in
theorem AcombN_0_3_7 (u : ℝ) : AcombN 0 3 7 u = 0 := by
  simp only [AcombN, S3N, Q3, tA, tD, tN, tF]
  linear_combination ((-12096 : ℝ) * u ^ 8 + (43008 : ℝ) * u ^ 7 + (8064 : ℝ) * u ^ 6 * cU u ^ 2 + (-64512 : ℝ) * u ^ 6 + (53760 : ℝ) * u ^ 5 + (13440 : ℝ) * u ^ 4 * cU u ^ 4 + (-26880 : ℝ) * u ^ 4 + (8064 : ℝ) * u ^ 3 + (2688 : ℝ) * u ^ 2 * cU u ^ 6 + (-1344 : ℝ) * u ^ 2) * cU_sq u

set_option maxHeartbeats 1000000 in
theorem AcombN_0_3_8 (u : ℝ) : AcombN 0 3 8 u = 0 := by
  simp only [AcombN, S3N, Q3, tA, tD, tN, tF]
  linear_combination ((-25152 : ℝ) * u ^ 9 + (98304 : ℝ) * u ^ 8 + (-10752 : ℝ) * u ^ 7 * cU u ^ 2 + (-172032 : ℝ) * u ^ 7 + (172032 : ℝ) * u ^ 6 + (-26880 : ℝ) * u ^ 5 * cU u ^ 4 + (-107520 : ℝ) * u ^ 5 + (43008 : ℝ) * u ^ 4 + (-10752 : ℝ) * u ^ 3 * cU u ^ 6 + (-10752 : ℝ) * u ^ 3 + (1536 : ℝ) * u ^ 2 + (-384 : ℝ) * u * cU u ^ 8 + (-192 : ℝ) * u) * cU_sq u

theorem AcombN_0_4_0 (u : ℝ) : AcombN 0 4 0 u = (2240 : ℝ) * u ^ 4 + (-3840 : ℝ) * u ^ 3 + (2688 : ℝ) * u ^ 2 + (-768 : ℝ) * u + (192 : ℝ) := by
  rw [AcombN_symm]; exact AcombN_0_0_4 u

theorem AcombN_0_4_1 (u : ℝ) : AcombN 0 4 1 u = 0 := by
  rw [AcombN_symm]; exact AcombN_0_1_4 u

theorem AcombN_0_4_2 (u : ℝ) : AcombN 0 4 2 u = (3360 : ℝ) * u ^ 6 + (-8000 : ℝ) * u ^ 5 + (8992 : ℝ) * u ^ 4 + (-5760 : ℝ) * u ^ 3 + (2400 : ℝ) * u ^ 2 + (-576 : ℝ) * u + (96 : ℝ) := by
  rw [AcombN_symm]; exact AcombN_0_2_4 u

theorem AcombN_0_4_3 (u : ℝ) : AcombN 0 4 3 u = 0 := by
  rw [AcombN_symm]; exact AcombN_0_3_4 u

set_option maxHeartbeats 1000000 in
theorem AcombN_0_4_4 (u : ℝ) : AcombN 0 4 4 u = (9800 : ℝ) * u ^ 8 + (-33600 : ℝ) * u ^ 7 + (52320 : ℝ) * u ^ 6 + (-47040 : ℝ) * u ^ 5 + (27312 : ℝ) * u ^ 4 + (-10944 : ℝ) * u ^ 3 + (3168 : ℝ) * u ^ 2 + (-576 : ℝ) * u + (72 : ℝ) := by
  simp only [AcombN, S3N, Q3, tA, tD, tN, tF]
  linear_combination ((11856 : ℝ) * u ^ 6 + (-20960 : ℝ) * u ^ 5 + (6816 : ℝ) * u ^ 4 * cU u ^ 2 + (17584 : ℝ) * u ^ 4 + (-3712 : ℝ) * u ^ 3 * cU u ^ 2 + (-7744 : ℝ) * u ^ 3 + (1600 : ℝ) * u ^ 2 * cU u ^ 4 + (2496 : ℝ) * u ^ 2 * cU u ^ 2 + (2736 : ℝ) * u ^ 2 + (-128 : ℝ) * u * cU u ^ 4 + (-640 : ℝ) * u * cU u ^ 2 + (-480 : ℝ) * u + (128 : ℝ) * cU u ^ 6 + (64 : ℝ) * cU u ^ 4 + (160 : ℝ) * cU u ^ 2 + (80 : ℝ)) * cU_sq u

set_option maxHeartbeats 1000000 in
theorem AcombN_0_4_5 (u : ℝ) : AcombN 0 4 5 u = (1400 : ℝ) * u ^ 9 + (-8000 : ℝ) * u ^ 8 + (19680 : ℝ) * u ^ 7 + (-27200 : ℝ) * u ^ 6 + (23120 : ℝ) * u ^ 5 + (-12480 : ℝ) * u ^ 4 + (4320 : ℝ) * u ^ 3 + (-960 : ℝ) * u ^ 2 + (120 : ℝ) * u := by
  simp only [AcombN, S3N, Q3, tA, tD, tN, tF]
  linear_combination ((-7760 : ℝ) * u ^ 7 + (12000 : ℝ) * u ^ 6 + (-12960 : ℝ) * u ^ 5 * cU u ^ 2 + (-9520 : ℝ) * u ^ 5 + (8320 : ℝ) * u ^ 4 * cU u ^ 2 + (4160 : ℝ) * u ^ 4 + (-5440 : ℝ) * u ^ 3 * cU u ^ 4 + (-4800 : ℝ) * u ^ 3 * cU u ^ 2 + (-1840 : ℝ) * u ^ 3 + (640 : ℝ) * u ^ 2 * cU u ^ 4 + (640 : ℝ) * u ^ 2 * cU u ^ 2 + (480 : ℝ) * u ^ 2 + (-640 : ℝ) * u * cU u ^ 6 + (-320 : ℝ) * u * cU u ^ 4 + (-160 : ℝ) * u * cU u ^ 2 + (-80 : ℝ) * u) * cU_sq u

set_option maxHeartbeats 1000000 in
theorem AcombN_0_4_6 (u : ℝ) : AcombN 0 4 6 u = (32340 : ℝ) * u ^ 10 + (-143640 : ℝ) * u ^ 9 + (292908 : ℝ) * u ^ 8 + (-357728 : ℝ) * u ^ 7 + (289992 : ℝ) * u ^ 6 + (-163920 : ℝ) * u ^ 5 + (66520 : ℝ) * u ^ 4 + (-19680 : ℝ) * u ^ 3 + (4260 : ℝ) * u ^ 2 + (-600 : ℝ) * u + (60 : ℝ) := by
  simp only [AcombN, S3N, Q3, tA, tD, tN, tF]
  linear_combination ((40040 : ℝ) * u ^ 8 + (-103776 : ℝ) * u ^ 7 + (32080 : ℝ) * u ^ 6 * cU u ^ 2 + (128560 : ℝ) * u ^ 6 + (-38944 : ℝ) * u ^ 5 * cU u ^ 2 + (-92672 : ℝ) * u ^ 5 + (15520 : ℝ) * u ^ 4 * cU u ^ 4 + (31952 : ℝ) * u ^ 4 * cU u ^ 2 + (44064 : ℝ) * u ^ 4 + (-3840 : ℝ) * u ^ 3 * cU u ^ 4 + (-13376 : ℝ) * u ^ 3 * cU u ^ 2 + (-13792 : ℝ) * u ^ 3 + (2752 : ℝ) * u ^ 2 * cU u ^ 6 + (2304 : ℝ) * u ^ 2 * cU u ^ 4 + (4464 : ℝ) * u ^ 2 * cU u ^ 2 + (3344 : ℝ) * u ^ 2 + (-128 : ℝ) * u * cU u ^ 6 + (-384 : ℝ) * u * cU u ^ 4 + (-672 : ℝ) * u * cU u ^ 2 + (-448 : ℝ) * u + (128 : ℝ) * cU u ^ 8 + (64 : ℝ) * cU u ^ 6 + (96 : ℝ) * cU u ^ 4 + (112 : ℝ) * cU u ^ 2 + (56 : ℝ)) * cU_sq u

set_option maxHeartbeats 1000000 in
theorem AcombN_0_4_7 (u : ℝ) : AcombN 0 4 7 u = (12740 : ℝ) * u ^ 11 + (-78680 : ℝ) * u ^ 10 + (215628 : ℝ) * u ^ 9 + (-346976 : ℝ) * u ^ 8 + (365960 : ℝ) * u ^ 7 + (-267792 : ℝ) * u ^ 6 + (140280 : ℝ) * u ^ 5 + (-53088 : ℝ) * u ^ 4 + (14196 : ℝ) * u ^ 3 + (-2520 : ℝ) * u ^ 2 + (252 : ℝ) * u := by
  simp only [AcombN, S3N, Q3, tA, tD, tN, tF]
  linear_combination ((-18872 : ℝ) * u ^ 9 + (27104 : ℝ) * u ^ 8 + (-56560 : ℝ) * u ^ 7 * cU u ^ 2 + (-9968 : ℝ) * u ^ 7 + (70112 : ℝ) * u ^ 6 * cU u ^ 2 + (-11648 : ℝ) * u ^ 6 + (-39648 : ℝ) * u ^ 5 * cU u ^ 4 + (-48944 : ℝ) * u ^ 5 * cU u ^ 2 + (13888 : ℝ) * u ^ 5 + (17920 : ℝ) * u ^ 4 * cU u ^ 4 + (12992 : ℝ) * u ^ 4 * cU u ^ 2 + (-7840 : ℝ) * u ^ 4 + (-10304 : ℝ) * u ^ 3 * cU u ^ 6 + (-11648 : ℝ) * u ^ 3 * cU u ^ 4 + (-2128 : ℝ) * u ^ 3 * cU u ^ 2 + (2352 : ℝ) * u ^ 3 + (896 : ℝ) * u ^ 2 * cU u ^ 6 + (2688 : ℝ) * u ^ 2 * cU u ^ 4 + (-672 : ℝ) * u ^ 2 * cU u ^ 2 + (-448 : ℝ) * u ^ 2 + (-896 : ℝ) * u * cU u ^ 8 + (-448 : ℝ) * u * cU u ^ 6 + (-672 : ℝ) * u * cU u ^ 4 + (112 : ℝ) * u * cU u ^ 2 + (56 : ℝ) * u) * cU_sq u

set_option maxHeartbeats 1000000 in
theorem AcombN_0_4_8 (u : ℝ) : AcombN 0 4 8 u = (112630 : ℝ) * u ^ 12 + (-613640 : ℝ) * u ^ 11 + (1551916 : ℝ) * u ^ 10 + (-2398568 : ℝ) * u ^ 9 + (2521386 : ℝ) * u ^ 8 + (-1902864 : ℝ) * u ^ 7 + (1062376 : ℝ) * u ^ 6 + (-445200 : ℝ) * u ^ 5 + (140394 : ℝ) * u ^ 4 + (-33000 : ℝ) * u ^ 3 + (5676 : ℝ) * u ^ 2 + (-648 : ℝ) * u + (54 : ℝ) := by
  simp only [AcombN, S3N, Q3, tA, tD, tN, tF]
  linear_combination ((133036 : ℝ) * u ^ 10 + (-466616 : ℝ) * u ^ 9 + (126040 : ℝ) * u ^ 8 * cU u ^ 2 + (781884 : ℝ) * u ^ 8 + (-230592 : ℝ) * u ^ 7 * cU u ^ 2 + (-791712 : ℝ) * u ^ 7 + (93744 : ℝ) * u ^ 6 * cU u ^ 4 + (245408 : ℝ) * u ^ 6 * cU u ^ 2 + (538136 : ℝ) * u ^ 6 + (-64800 : ℝ) * u ^ 5 * cU u ^ 4 + (-159552 : ℝ) * u ^ 5 * cU u ^ 2 + (-256336 : ℝ) * u ^ 5 + (33376 : ℝ) * u ^ 4 * cU u ^ 6 + (45264 : ℝ) * u ^ 4 * cU u ^ 4 + (78096 : ℝ) * u ^ 4 * cU u ^ 2 + (88344 : ℝ) * u ^ 4 + (-5504 : ℝ) * u ^ 3 * cU u ^ 6 + (-13248 : ℝ) * u ^ 3 * cU u ^ 4 + (-24896 : ℝ) * u ^ 3 * cU u ^ 2 + (-21664 : ℝ) * u ^ 3 + (4416 : ℝ) * u ^ 2 * cU u ^ 8 + (3136 : ℝ) * u ^ 2 * cU u ^ 6 + (3792 : ℝ) * u ^ 2 * cU u ^ 4 + (5792 : ℝ) * u ^ 2 * cU u ^ 2 + (4028 : ℝ) * u ^ 2 + (-128 : ℝ) * u * cU u ^ 8 + (-384 : ℝ) * u * cU u ^ 6 + (-288 : ℝ) * u * cU u ^ 4 + (-704 : ℝ) * u * cU u ^ 2 + (-440 : ℝ) * u + (128 : ℝ) * cU u ^ 10 + (64 : ℝ) * cU u ^ 8 + (96 : ℝ) * cU u ^ 6 + (48 : ℝ) * cU u ^ 4 + (88 : ℝ) * cU u ^ 2 + (44 : ℝ)) * cU_sq u

theorem AcombN_0_5_0 (u : ℝ) : AcombN 0 5 0 u = (320 : ℝ) * u ^ 5 + (-1280 : ℝ) * u ^ 4 + (1920 : ℝ) * u ^ 3 + (-1280 : ℝ) * u ^ 2 + (320 : ℝ) * u := by
  rw [AcombN_symm]; exact AcombN_0_0_5 u

theorem AcombN_0_5_1 (u : ℝ) : AcombN 0 5 1 u = 0 := by
  rw [AcombN_symm]; exact AcombN_0_1_5 u

theorem AcombN_0_5_2 (u : ℝ) : AcombN 0 5 2 u = (480 : ℝ) * u ^ 7 + (-2240 : ℝ) * u ^ 6 + (4320 : ℝ) * u ^ 5 + (-4480 : ℝ) * u ^ 4 + (2720 : ℝ) * u ^ 3 + (-960 : ℝ) * u ^ 2 + (160 : ℝ) * u := by
  rw [AcombN_symm]; exact AcombN_0_2_5 u

theorem AcombN_0_5_3 (u : ℝ) : AcombN 0 5 3 u = 0 := by
  rw [AcombN_symm]; exact AcombN_0_3_5 u

theorem AcombN_0_5_4 (u : ℝ) : AcombN 0 5 4 u = (1400 : ℝ) * u ^ 9 + (-8000 : ℝ) * u ^ 8 + (19680 : ℝ) * u ^ 7 + (-27200 : ℝ) * u ^ 6 + (23120 : ℝ) * u ^ 5 + (-12480 : ℝ) * u ^ 4 + (4320 : ℝ) * u ^ 3 + (-960 : ℝ) * u ^ 2 + (120 : ℝ) * u := by
  rw [AcombN_symm]; exact AcombN_0_4_5 u

set_option maxHeartbeats 1000000 in
theorem AcombN_0_5_5 (u : ℝ) : AcombN 0 5 5 u = (200 : ℝ) * u ^ 10 + (-1600 : ℝ) * u ^ 9 + (5600 : ℝ) * u ^ 8 + (-11200 : ℝ) * u ^ 7 + (14000 : ℝ) * u ^ 6 + (-11200 : ℝ) * u ^ 5 + (5600 : ℝ) * u ^ 4 + (-1600 : ℝ) * u ^ 3 + (200 : ℝ) * u ^ 2 := by
  simp only [AcombN, S3N, Q3, tA, tD, tN, tF]
  linear_combination ((-14000 : ℝ) * u ^ 8 + (45600 : ℝ) * u ^ 7 + (10400 : ℝ) * u ^ 6 * cU u ^ 2 + (-62800 : ℝ) * u ^ 6 + (9600 : ℝ) * u ^ 5 * cU u ^ 2 + (49600 : ℝ) * u ^ 5 + (14400 : ℝ) * u ^ 4 * cU u ^ 4 + (-14400 : ℝ) * u ^ 4 * cU u ^ 2 + (-24400 : ℝ) * u ^ 4 + (-3200 : ℝ) * u ^ 3 * cU u ^ 4 + (9600 : ℝ) * u ^ 3 * cU u ^ 2 + (7200 : ℝ) * u ^ 3 + (3200 : ℝ) * u ^ 2 * cU u ^ 6 + (1600 : ℝ) * u ^ 2 * cU u ^ 4 + (-2400 : ℝ) * u ^ 2 * cU u ^ 2 + (-1200 : ℝ) * u ^ 2) * cU_sq u

set_option maxHeartbeats 1000000 in
theorem AcombN_0_5_6 (u : ℝ) : AcombN 0 5 6 u = (4620 : ℝ) * u ^ 11 + (-31080 : ℝ) * u ^ 10 + (92820 : ℝ) * u ^ 9 + (-162080 : ℝ) * u ^ 8 + (183320 : ℝ) * u ^ 7 + (-140400 : ℝ) * u ^ 6 + (73800 : ℝ) * u ^ 5 + (-26400 : ℝ) * u ^ 4 + (6300 : ℝ) * u ^ 3 + (-1000 : ℝ) * u ^ 2 + (100 : ℝ) * u := by
  simp only [AcombN, S3N, Q3, tA, tD, tN, tF]
  linear_combination ((-24360 : ℝ) * u ^ 9 + (70880 : ℝ) * u ^ 8 + (-32720 : ℝ) * u ^ 7 * cU u ^ 2 + (-98800 : ℝ) * u ^ 7 + (30240 : ℝ) * u ^ 6 * cU u ^ 2 + (81920 : ℝ) * u ^ 6 + (-33440 : ℝ) * u ^ 5 * cU u ^ 4 + (-27600 : ℝ) * u ^ 5 * cU u ^ 2 + (-45600 : ℝ) * u ^ 5 + (8960 : ℝ) * u ^ 4 * cU u ^ 4 + (14400 : ℝ) * u ^ 4 * cU u ^ 2 + (17760 : ℝ) * u ^ 4 + (-11200 : ℝ) * u ^ 3 * cU u ^ 6 + (-3840 : ℝ) * u ^ 3 * cU u ^ 4 + (-6000 : ℝ) * u ^ 3 * cU u ^ 2 + (-5200 : ℝ) * u ^ 3 + (640 : ℝ) * u ^ 2 * cU u ^ 6 + (-640 : ℝ) * u ^ 2 * cU u ^ 4 + (1440 : ℝ) * u ^ 2 * cU u ^ 2 + (960 : ℝ) * u ^ 2 + (-640 : ℝ) * u * cU u ^ 8 + (-320 : ℝ) * u * cU u ^ 6 + (160 : ℝ) * u * cU u ^ 4 + (-240 : ℝ) * u * cU u ^ 2 + (-120 : ℝ) * u) * cU_sq u

set_option maxHeartbeats 1000000 in
theorem AcombN_0_5_7 (u : ℝ) : AcombN 0 5 7 u = (1820 : ℝ) * u ^ 12 + (-15400 : ℝ) * u ^ 11 + (58100 : ℝ) * u ^ 10 + (-128800 : ℝ) * u ^ 9 + (186200 : ℝ) * u ^ 8 + (-184240 : ℝ) * u ^ 7 + (127400 : ℝ) * u ^ 6 + (-61600 : ℝ) * u ^ 5 + (20300 : ℝ) * u ^ 4 + (-4200 : ℝ) * u ^ 3 + (420 : ℝ) * u ^ 2 := by
  simp only [AcombN, S3N, Q3, tA, tD, tN, tF]
  linear_combination ((-56840 : ℝ) * u ^ 10 + (231840 : ℝ) * u ^ 9 + (7280 : ℝ) * u ^ 8 * cU u ^ 2 + (-420560 : ℝ) * u ^ 8 + (84000 : ℝ) * u ^ 7 * cU u ^ 2 + (452480 : ℝ) * u ^ 7 + (68320 : ℝ) * u ^ 6 * cU u ^ 4 + (-142800 : ℝ) * u ^ 6 * cU u ^ 2 + (-320320 : ℝ) * u ^ 6 + (-17920 : ℝ) * u ^ 5 * cU u ^ 4 + (123200 : ℝ) * u ^ 5 * cU u ^ 2 + (155680 : ℝ) * u ^ 5 + (33600 : ℝ) * u ^ 4 * cU u ^ 6 + (4480 : ℝ) * u ^ 4 * cU u ^ 4 + (-58800 : ℝ) * u ^ 4 * cU u ^ 2 + (-52080 : ℝ) * u ^ 4 + (-4480 : ℝ) * u ^ 3 * cU u ^ 6 + (4480 : ℝ) * u ^ 3 * cU u ^ 4 + (16800 : ℝ) * u ^ 3 * cU u ^ 2 + (11200 : ℝ) * u ^ 3 + (4480 : ℝ) * u ^ 2 * cU u ^ 8 + (2240 : ℝ) * u ^ 2 * cU u ^ 6 + (-1120 : ℝ) * u ^ 2 * cU u ^ 4 + (-2800 : ℝ) * u ^ 2 * cU u ^ 2 + (-1400 : ℝ) * u ^ 2) * cU_sq u

set_option maxHeartbeats 1000000 in
theorem AcombN_0_5_8 (u : ℝ) : AcombN 0 5 8 u = (16090 : ℝ) * u ^ 13 + (-124440 : ℝ) * u ^ 12 + (436260 : ℝ) * u ^ 11 + (-917080 : ℝ) * u ^ 10 + (1288070 : ℝ) * u ^ 9 + (-1274160 : ℝ) * u ^ 8 + (910840 : ℝ) * u ^ 7 + (-474480 : ℝ) * u ^ 6 + (178950 : ℝ) * u ^ 5 + (-47800 : ℝ) * u ^ 4 + (8740 : ℝ) * u ^ 3 + (-1080 : ℝ) * u ^ 2 + (90 : ℝ) * u := by
  simp only [AcombN, S3N, Q3, tA, tD, tN, tF]
  linear_combination ((-93580 : ℝ) * u ^ 11 + (390840 : ℝ) * u ^ 10 + (-73240 : ℝ) * u ^ 9 * cU u ^ 2 + (-758460 : ℝ) * u ^ 9 + (123200 : ℝ) * u ^ 8 * cU u ^ 2 + (890400 : ℝ) * u ^ 8 + (-125360 : ℝ) * u ^ 7 * cU u ^ 4 + (-193760 : ℝ) * u ^ 7 * cU u ^ 2 + (-707000 : ℝ) * u ^ 7 + (26400 : ℝ) * u ^ 6 * cU u ^ 4 + (194880 : ℝ) * u ^ 6 * cU u ^ 2 + (400400 : ℝ) * u ^ 6 + (-89440 : ℝ) * u ^ 5 * cU u ^ 6 + (5680 : ℝ) * u ^ 5 * cU u ^ 4 + (-131600 : ℝ) * u ^ 5 * cU u ^ 2 + (-164920 : ℝ) * u ^ 5 + (17280 : ℝ) * u ^ 4 * cU u ^ 6 + (-19520 : ℝ) * u ^ 4 * cU u ^ 4 + (56000 : ℝ) * u ^ 4 * cU u ^ 2 + (48800 : ℝ) * u ^ 4 + (-19520 : ℝ) * u ^ 3 * cU u ^ 8 + (-8000 : ℝ) * u ^ 3 * cU u ^ 6 + (5680 : ℝ) * u ^ 3 * cU u ^ 4 + (-14560 : ℝ) * u ^ 3 * cU u ^ 2 + (-10300 : ℝ) * u ^ 3 + (640 : ℝ) * u ^ 2 * cU u ^ 8 + (-640 : ℝ) * u ^ 2 * cU u ^ 6 + (-480 : ℝ) * u ^ 2 * cU u ^ 4 + (2240 : ℝ) * u ^ 2 * cU u ^ 2 + (1400 : ℝ) * u ^ 2 + (-640 : ℝ) * u * cU u ^ 10 + (-320 : ℝ) * u * cU u ^ 8 + (160 : ℝ) * u * cU u ^ 6 + (80 : ℝ) * u * cU u ^ 4 + (-280 : ℝ) * u * cU u ^ 2 + (-140 : ℝ) * u) * cU_sq u

theorem AcombN_0_6_0 (u : ℝ) : AcombN 0 6 0 u = (7392 : ℝ) * u ^ 6 + (-20160 : ℝ) * u ^ 5 + (23520 : ℝ) * u ^ 4 + (-14720 : ℝ) * u ^ 3 + (5280 : ℝ) * u ^ 2 + (-960 : ℝ) * u + (160 : ℝ) := by
  rw [AcombN_symm]; exact AcombN_0_0_6 u

theorem AcombN_0_6_1 (u : ℝ) : AcombN 0 6 1 u = 0 := by
  rw [AcombN_symm]; exact AcombN_0_1_6 u

theorem AcombN_0_6_2 (u : ℝ) : AcombN 0 6 2 u = (11088 : ℝ) * u ^ 8 + (-37632 : ℝ) * u ^ 7 + (59136 : ℝ) * u ^ 6 + (-55680 : ℝ) * u ^ 5 + (34400 : ℝ) * u ^ 4 + (-14080 : ℝ) * u ^ 3 + (3840 : ℝ) * u ^ 2 + (-640 : ℝ) * u + (80 : ℝ) := by
  rw [AcombN_symm]; exact AcombN_0_2_6 u

theorem AcombN_0_6_3 (u : ℝ) : AcombN 0 6 3 u = 0 := by
  rw [AcombN_symm]; exact AcombN_0_3_6 u

theorem AcombN_0_6_4 (u : ℝ) : AcombN 0 6 4 u = (32340 : ℝ) * u ^ 10 + (-143640 : ℝ) * u ^ 9 + (292908 : ℝ) * u ^ 8 + (-357728 : ℝ) * u ^ 7 + (289992 : ℝ) * u ^ 6 + (-163920 : ℝ) * u ^ 5 + (66520 : ℝ) * u ^ 4 + (-19680 : ℝ) * u ^ 3 + (4260 : ℝ) * u ^ 2 + (-600 : ℝ) * u + (60 : ℝ) := by
  rw [AcombN_symm]; exact AcombN_0_4_6 u

theorem AcombN_0_6_5 (u : ℝ) : AcombN 0 6 5 u = (4620 : ℝ) * u ^ 11 + (-31080 : ℝ) * u ^ 10 + (92820 : ℝ) * u ^ 9 + (-162080 : ℝ) * u ^ 8 + (183320 : ℝ) * u ^ 7 + (-140400 : ℝ) * u ^ 6 + (73800 : ℝ) * u ^ 5 + (-26400 : ℝ) * u ^ 4 + (6300 : ℝ) * u ^ 3 + (-1000 : ℝ) * u ^ 2 + (100 : ℝ) * u := by
  rw [AcombN_symm]; exact AcombN_0_5_6 u

set_option maxHeartbeats 1000000 in
theorem AcombN_0_6_6 (u : ℝ) : AcombN 0 6 6 u = (106722 : ℝ) * u ^ 12 + (-582120 : ℝ) * u ^ 11 + (1472940 : ℝ) * u ^ 10 + (-2277240 : ℝ) * u ^ 9 + (2392110 : ℝ) * u ^ 8 + (-1795920 : ℝ) * u ^ 7 + (988520 : ℝ) * u ^ 6 + (-404400 : ℝ) * u ^ 5 + (124350 : ℝ) * u ^ 4 + (-29000 : ℝ) * u ^ 3 + (5100 : ℝ) * u ^ 2 + (-600 : ℝ) * u + (50 : ℝ) := by
  simp only [AcombN, S3N, Q3, tA, tD, tN, tF]
  linear_combination ((135044 : ℝ) * u ^ 10 + (-464072 : ℝ) * u ^ 9 + (135688 : ℝ) * u ^ 8 * cU u ^ 2 + (755268 : ℝ) * u ^ 8 + (-288128 : ℝ) * u ^ 7 * cU u ^ 2 + (-746912 : ℝ) * u ^ 7 + (79376 : ℝ) * u ^ 6 * cU u ^ 4 + (337792 : ℝ) * u ^ 6 * cU u ^ 2 + (496088 : ℝ) * u ^ 6 + (-48864 : ℝ) * u ^ 5 * cU u ^ 4 + (-222912 : ℝ) * u ^ 5 * cU u ^ 2 + (-228432 : ℝ) * u ^ 5 + (34592 : ℝ) * u ^ 4 * cU u ^ 6 + (37680 : ℝ) * u ^ 4 * cU u ^ 4 + (93360 : ℝ) * u ^ 4 * cU u ^ 2 + (75480 : ℝ) * u ^ 4 + (-3968 : ℝ) * u ^ 3 * cU u ^ 6 + (-14400 : ℝ) * u ^ 3 * cU u ^ 4 + (-24192 : ℝ) * u ^ 3 * cU u ^ 2 + (-17760 : ℝ) * u ^ 3 + (3904 : ℝ) * u ^ 2 * cU u ^ 8 + (2112 : ℝ) * u ^ 2 * cU u ^ 6 + (5040 : ℝ) * u ^ 2 * cU u ^ 4 + (5376 : ℝ) * u ^ 2 * cU u ^ 2 + (3300 : ℝ) * u ^ 2 + (-128 : ℝ) * u * cU u ^ 8 + (-128 : ℝ) * u * cU u ^ 6 + (-864 : ℝ) * u * cU u ^ 4 + (-576 : ℝ) * u * cU u ^ 2 + (-360 : ℝ) * u + (128 : ℝ) * cU u ^ 10 + (64 : ℝ) * cU u ^ 8 + (32 : ℝ) * cU u ^ 6 + (144 : ℝ) * cU u ^ 4 + (72 : ℝ) * cU u ^ 2 + (36 : ℝ)) * cU_sq u

set_option maxHeartbeats 1000000 in
theorem AcombN_0_6_7 (u : ℝ) : AcombN 0 6 7 u = (42042 : ℝ) * u ^ 13 + (-302232 : ℝ) * u ^ 12 + (984900 : ℝ) * u ^ 11 + (-1930040 : ℝ) * u ^ 10 + (2543870 : ℝ) * u ^ 9 + (-2387952 : ℝ) * u ^ 8 + (1646232 : ℝ) * u ^ 7 + (-845040 : ℝ) * u ^ 6 + (323190 : ℝ) * u ^ 5 + (-91000 : ℝ) * u ^ 4 + (18340 : ℝ) * u ^ 3 + (-2520 : ℝ) * u ^ 2 + (210 : ℝ) * u := by
  simp only [AcombN, S3N, Q3, tA, tD, tN, tF]
  linear_combination ((-57036 : ℝ) * u ^ 11 + (170296 : ℝ) * u ^ 10 + (-140952 : ℝ) * u ^ 9 * cU u ^ 2 + (-245308 : ℝ) * u ^ 9 + (230720 : ℝ) * u ^ 8 * cU u ^ 2 + (213472 : ℝ) * u ^ 8 + (-165424 : ℝ) * u ^ 7 * cU u ^ 4 + (-210784 : ℝ) * u ^ 7 * cU u ^ 2 + (-122248 : ℝ) * u ^ 7 + (130592 : ℝ) * u ^ 6 * cU u ^ 4 + (97216 : ℝ) * u ^ 6 * cU u ^ 2 + (45360 : ℝ) * u ^ 6 + (-92512 : ℝ) * u ^ 5 * cU u ^ 6 + (-102480 : ℝ) * u ^ 5 * cU u ^ 4 + (-27440 : ℝ) * u ^ 5 * cU u ^ 2 + (-12264 : ℝ) * u ^ 5 + (18816 : ℝ) * u ^ 4 * cU u ^ 6 + (38080 : ℝ) * u ^ 4 * cU u ^ 4 + (3136 : ℝ) * u ^ 4 * cU u ^ 2 + (3360 : ℝ) * u ^ 4 + (-18368 : ℝ) * u ^ 3 * cU u ^ 8 + (-10304 : ℝ) * u ^ 3 * cU u ^ 6 + (-10640 : ℝ) * u ^ 3 * cU u ^ 4 + (-1568 : ℝ) * u ^ 3 * cU u ^ 2 + (-1260 : ℝ) * u ^ 3 + (896 : ℝ) * u ^ 2 * cU u ^ 8 + (896 : ℝ) * u ^ 2 * cU u ^ 6 + (672 : ℝ) * u ^ 2 * cU u ^ 4 + (448 : ℝ) * u ^ 2 * cU u ^ 2 + (280 : ℝ) * u ^ 2 + (-896 : ℝ) * u * cU u ^ 10 + (-448 : ℝ) * u * cU u ^ 8 + (-224 : ℝ) * u * cU u ^ 6 + (-112 : ℝ) * u * cU u ^ 4 + (-56 : ℝ) * u * cU u ^ 2 + (-28 : ℝ) * u) * cU_sq u

set_option maxHeartbeats 1000000 in
theorem AcombN_0_6_8 (u : ℝ) : AcombN 0 6 8 u = (371679 : ℝ) * u ^ 14 + (-2401518 : ℝ) * u ^ 13 + (7263795 : ℝ) * u ^ 12 + (-13604404 : ℝ) * u ^ 11 + (17607155 : ℝ) * u ^ 10 + (-16644634 : ℝ) * u ^ 9 + (11848087 : ℝ) * u ^ 8 + (-6455032 : ℝ) * u ^ 7 + (2712269 : ℝ) * u ^ 6 + (-881090 : ℝ) * u ^ 5 + (221385 : ℝ) * u ^ 4 + (-42900 : ℝ) * u ^ 3 + (6305 : ℝ) * u ^ 2 + (-630 : ℝ) * u + (45 : ℝ) := by
  simp only [AcombN, S3N, Q3, tA, tD, tN, tF]
  linear_combination ((449918 : ℝ) * u ^ 12 + (-1951456 : ℝ) * u ^ 11 + (522876 : ℝ) * u ^ 10 * cU u ^ 2 + (4015912 : ℝ) * u ^ 10 + (-1530056 : ℝ) * u ^ 9 * cU u ^ 2 + (-5110584 : ℝ) * u ^ 9 + (373112 : ℝ) * u ^ 8 * cU u ^ 4 + (2298436 : ℝ) * u ^ 8 * cU u ^ 2 + (4463566 : ℝ) * u ^ 8 + (-470688 : ℝ) * u ^ 7 * cU u ^ 4 + (-2087200 : ℝ) * u ^ 7 * cU u ^ 2 + (-2807008 : ℝ) * u ^ 7 + (227696 : ℝ) * u ^ 6 * cU u ^ 6 + (486864 : ℝ) * u ^ 6 * cU u ^ 4 + (1271576 : ℝ) * u ^ 6 * cU u ^ 2 + (1303264 : ℝ) * u ^ 6 + (-76384 : ℝ) * u ^ 5 * cU u ^ 6 + (-292864 : ℝ) * u ^ 5 * cU u ^ 4 + (-532080 : ℝ) * u ^ 5 * cU u ^ 2 + (-449872 : ℝ) * u ^ 5 + (67424 : ℝ) * u ^ 4 * cU u ^ 8 + (48496 : ℝ) * u ^ 4 * cU u ^ 6 + (126560 : ℝ) * u ^ 4 * cU u ^ 4 + (159688 : ℝ) * u ^ 4 * cU u ^ 2 + (116570 : ℝ) * u ^ 4 + (-5632 : ℝ) * u ^ 3 * cU u ^ 8 + (-10944 : ℝ) * u ^ 3 * cU u ^ 6 + (-34336 : ℝ) * u ^ 3 * cU u ^ 4 + (-32928 : ℝ) * u ^ 3 * cU u ^ 2 + (-22400 : ℝ) * u ^ 3 + (5568 : ℝ) * u ^ 2 * cU u ^ 10 + (2944 : ℝ) * u ^ 2 * cU u ^ 8 + (3536 : ℝ) * u ^ 2 * cU u ^ 6 + (7664 : ℝ) * u ^ 2 * cU u ^ 4 + (5676 : ℝ) * u ^ 2 * cU u ^ 2 + (3384 : ℝ) * u ^ 2 + (-128 : ℝ) * u * cU u ^ 10 + (-128 : ℝ) * u * cU u ^ 8 + (-480 : ℝ) * u * cU u ^ 6 + (-832 : ℝ) * u * cU u ^ 4 + (-520 : ℝ) * u * cU u ^ 2 + (-312 : ℝ) * u + (128 : ℝ) * cU u ^ 12 + (64 : ℝ) * cU u ^ 10 + (32 : ℝ) * cU u ^ 8 + (80 : ℝ) * cU u ^ 6 + (104 : ℝ) * cU u ^ 4 + (52 : ℝ) * cU u ^ 2 + (26 : ℝ)) * cU_sq u

theorem AcombN_0_7_0 (u : ℝ) : AcombN 0 7 0 u = (2912 : ℝ) * u ^ 7 + (-12992 : ℝ) * u ^ 6 + (23520 : ℝ) * u ^ 5 + (-22400 : ℝ) * u ^ 4 + (12320 : ℝ) * u ^ 3 + (-4032 : ℝ) * u ^ 2 + (672 : ℝ) * u := by
  rw [AcombN_symm]; exact AcombN_0_0_7 u

theorem AcombN_0_7_1 (u : ℝ) : AcombN 0 7 1 u = 0 := by
  rw [AcombN_symm]; exact AcombN_0_1_7 u

theorem AcombN_0_7_2 (u : ℝ) : AcombN 0 7 2 u = (4368 : ℝ) * u ^ 9 + (-22400 : ℝ) * u ^ 8 + (49728 : ℝ) * u ^ 7 + (-63616 : ℝ) * u ^ 6 + (52640 : ℝ) * u ^ 5 + (-29568 : ℝ) * u ^ 4 + (11200 : ℝ) * u ^ 3 + (-2688 : ℝ) * u ^ 2 + (336 : ℝ) * u := by
  rw [AcombN_symm]; exact AcombN_0_2_7 u

theorem AcombN_0_7_3 (u : ℝ) : AcombN 0 7 3 u = 0 := by
  rw [AcombN_symm]; exact AcombN_0_3_7 u

theorem AcombN_0_7_4 (u : ℝ) : AcombN 0 7 4 u = (12740 : ℝ) * u ^ 11 + (-78680 : ℝ) * u ^ 10 + (215628 : ℝ) * u ^ 9 + (-346976 : ℝ) * u ^ 8 + (365960 : ℝ) * u ^ 7 + (-267792 : ℝ) * u ^ 6 + (140280 : ℝ) * u ^ 5 + (-53088 : ℝ) * u ^ 4 + (14196 : ℝ) * u ^ 3 + (-2520 : ℝ) * u ^ 2 + (252 : ℝ) * u := by
  rw [AcombN_symm]; exact AcombN_0_4_7 u

theorem AcombN_0_7_5 (u : ℝ) : AcombN 0 7 5 u = (1820 : ℝ) * u ^ 12 + (-15400 : ℝ) * u ^ 11 + (58100 : ℝ) * u ^ 10 + (-128800 : ℝ) * u ^ 9 + (186200 : ℝ) * u ^ 8 + (-184240 : ℝ) * u ^ 7 + (127400 : ℝ) * u ^ 6 + (-61600 : ℝ) * u ^ 5 + (20300 : ℝ) * u ^ 4 + (-4200 : ℝ) * u ^ 3 + (420 : ℝ) * u ^ 2 := by
  rw [AcombN_symm]; exact AcombN_0_5_7 u

theorem AcombN_0_7_6 (u : ℝ) : AcombN 0 7 6 u = (42042 : ℝ) * u ^ 13 + (-302232 : ℝ) * u ^ 12 + (984900 : ℝ) * u ^ 11 + (-1930040 : ℝ) * u ^ 10 + (2543870 : ℝ) * u ^ 9 + (-2387952 : ℝ) * u ^ 8 + (1646232 : ℝ) * u ^ 7 + (-845040 : ℝ) * u ^ 6 + (323190 : ℝ) * u ^ 5 + (-91000 : ℝ) * u ^ 4 + (18340 : ℝ) * u ^ 3 + (-2520 : ℝ) * u ^ 2 + (210 : ℝ) * u := by
  rw [AcombN_symm]; exact AcombN_0_6_7 u

set_option maxHeartbeats 1000000 in
theorem AcombN_0_7_7 (u : ℝ) : AcombN 0 7 7 u = (16562 : ℝ) * u ^ 14 + (-147784 : ℝ) * u ^ 13 + (597212 : ℝ) * u ^ 12 + (-1448440 : ℝ) * u ^ 11 + (2357390 : ℝ) * u ^ 10 + (-2729104 : ℝ) * u ^ 9 + (2324168 : ℝ) * u ^ 8 + (-1482544 : ℝ) * u ^ 7 + (710990 : ℝ) * u ^ 6 + (-252840 : ℝ) * u ^ 5 + (64092 : ℝ) * u ^ 4 + (-10584 : ℝ) * u ^ 3 + (882 : ℝ) * u ^ 2 := by
  simp only [AcombN, S3N, Q3, tA, tD, tN, tF]
  linear_combination ((-220892 : ℝ) * u ^ 12 + (1068984 : ℝ) * u ^ 11 + (-103096 : ℝ) * u ^ 10 * cU u ^ 2 + (-2367484 : ℝ) * u ^ 10 + (727552 : ℝ) * u ^ 9 * cU u ^ 2 + (3190880 : ℝ) * u ^ 9 + (245392 : ℝ) * u ^ 8 * cU u ^ 4 + (-1370432 : ℝ) * u ^ 8 * cU u ^ 2 + (-2918440 : ℝ) * u ^ 8 + (-61152 : ℝ) * u ^ 7 * cU u ^ 4 + (1408064 : ℝ) * u ^ 7 * cU u ^ 2 + (1909040 : ℝ) * u ^ 7 + (227360 : ℝ) * u ^ 6 * cU u ^ 6 + (-98000 : ℝ) * u ^ 6 * cU u ^ 4 + (-897680 : ℝ) * u ^ 6 * cU u ^ 2 + (-914536 : ℝ) * u ^ 6 + (-68992 : ℝ) * u ^ 5 * cU u ^ 6 + (172480 : ℝ) * u ^ 5 * cU u ^ 4 + (388864 : ℝ) * u ^ 5 * cU u ^ 2 + (321440 : ℝ) * u ^ 5 + (65856 : ℝ) * u ^ 4 * cU u ^ 8 + (40768 : ℝ) * u ^ 4 * cU u ^ 6 + (-98000 : ℝ) * u ^ 4 * cU u ^ 4 + (-116032 : ℝ) * u ^ 4 * cU u ^ 2 + (-81340 : ℝ) * u ^ 4 + (-6272 : ℝ) * u ^ 3 * cU u ^ 8 + (-6272 : ℝ) * u ^ 3 * cU u ^ 6 + (32928 : ℝ) * u ^ 3 * cU u ^ 4 + (21952 : ℝ) * u ^ 3 * cU u ^ 2 + (13720 : ℝ) * u ^ 3 + (6272 : ℝ) * u ^ 2 * cU u ^ 10 + (3136 : ℝ) * u ^ 2 * cU u ^ 8 + (1568 : ℝ) * u ^ 2 * cU u ^ 6 + (-5488 : ℝ) * u ^ 2 * cU u ^ 4 + (-2744 : ℝ) * u ^ 2 * cU u ^ 2 + (-1372 : ℝ) * u ^ 2) * cU_sq u

set_option maxHeartbeats 1000000 in
theorem AcombN_0_7_8 (u : ℝ) : AcombN 0 7 8 u = (146419 : ℝ) * u ^ 15 + (-1199982 : ℝ) * u ^ 14 + (4526403 : ℝ) * u ^ 13 + (-10439044 : ℝ) * u ^ 12 + (16489319 : ℝ) * u ^ 11 + (-18930618 : ℝ) * u ^ 10 + (16345063 : ℝ) * u ^ 9 + (-10819032 : ℝ) * u ^ 8 + (5534025 : ℝ) * u ^ 7 + (-2182978 : ℝ) * u ^ 6 + (656089 : ℝ) * u ^ 5 + (-146916 : ℝ) * u ^ 4 + (23709 : ℝ) * u ^ 3 + (-2646 : ℝ) * u ^ 2 + (189 : ℝ) * u := by
  simp only [AcombN, S3N, Q3, tA, tD, tN, tF]
  linear_combination ((-235354 : ℝ) * u ^ 13 + (1071728 : ℝ) * u ^ 12 + (-344372 : ℝ) * u ^ 11 * cU u ^ 2 + (-2338112 : ℝ) * u ^ 11 + (881272 : ℝ) * u ^ 10 * cU u ^ 2 + (3189256 : ℝ) * u ^ 10 + (-515816 : ℝ) * u ^ 9 * cU u ^ 4 + (-1365084 : ℝ) * u ^ 9 * cU u ^ 2 + (-3024098 : ℝ) * u ^ 9 + (444192 : ℝ) * u ^ 8 * cU u ^ 4 + (1362144 : ℝ) * u ^ 8 * cU u ^ 2 + (2096192 : ℝ) * u ^ 8 + (-512848 : ℝ) * u ^ 7 * cU u ^ 6 + (-322448 : ℝ) * u ^ 7 * cU u ^ 4 + (-955304 : ℝ) * u ^ 7 * cU u ^ 2 + (-1092112 : ℝ) * u ^ 7 + (206752 : ℝ) * u ^ 6 * cU u ^ 6 + (129920 : ℝ) * u ^ 6 * cU u ^ 4 + (468048 : ℝ) * u ^ 6 * cU u ^ 2 + (434672 : ℝ) * u ^ 6 + (-205856 : ℝ) * u ^ 5 * cU u ^ 8 + (-119952 : ℝ) * u ^ 5 * cU u ^ 6 + (-73920 : ℝ) * u ^ 5 * cU u ^ 4 + (-167384 : ℝ) * u ^ 5 * cU u ^ 2 + (-134974 : ℝ) * u ^ 5 + (30464 : ℝ) * u ^ 4 * cU u ^ 8 + (13888 : ℝ) * u ^ 4 * cU u ^ 6 + (31136 : ℝ) * u ^ 4 * cU u ^ 4 + (45024 : ℝ) * u ^ 4 * cU u ^ 2 + (33040 : ℝ) * u ^ 4 + (-30016 : ℝ) * u ^ 3 * cU u ^ 10 + (-16128 : ℝ) * u ^ 3 * cU u ^ 8 + (-112 : ℝ) * u ^ 3 * cU u ^ 6 + (-10416 : ℝ) * u ^ 3 * cU u ^ 4 + (-9828 : ℝ) * u ^ 3 * cU u ^ 2 + (-6384 : ℝ) * u ^ 3 + (896 : ℝ) * u ^ 2 * cU u ^ 10 + (896 : ℝ) * u ^ 2 * cU u ^ 8 + (-2016 : ℝ) * u ^ 2 * cU u ^ 6 + (2240 : ℝ) * u ^ 2 * cU u ^ 4 + (1400 : ℝ) * u ^ 2 * cU u ^ 2 + (840 : ℝ) * u ^ 2 + (-896 : ℝ) * u * cU u ^ 12 + (-448 : ℝ) * u * cU u ^ 10 + (-224 : ℝ) * u * cU u ^ 8 + (336 : ℝ) * u * cU u ^ 6 + (-280 : ℝ) * u * cU u ^ 4 + (-140 : ℝ) * u * cU u ^ 2 + (-70 : ℝ) * u) * cU_sq u

theorem AcombN_0_8_0 (u : ℝ) : AcombN 0 8 0 u = (25744 : ℝ) * u ^ 8 + (-96128 : ℝ) * u ^ 7 + (159040 : ℝ) * u ^ 6 + (-151424 : ℝ) * u ^ 5 + (90720 : ℝ) * u ^ 4 + (-34944 : ℝ) * u ^ 3 + (8512 : ℝ) * u ^ 2 + (-1152 : ℝ) * u + (144 : ℝ) := by
  rw [AcombN_symm]; exact AcombN_0_0_8 u

theorem AcombN_0_8_1 (u : ℝ) : AcombN 0 8 1 u = 0 := by
  rw [AcombN_symm]; exact AcombN_0_1_8 u

theorem AcombN_0_8_2 (u : ℝ) : AcombN 0 8 2 u = (38616 : ℝ) * u ^ 10 + (-169936 : ℝ) * u ^ 9 + (347560 : ℝ) * u ^ 8 + (-434240 : ℝ) * u ^ 7 + (367024 : ℝ) * u ^ 6 + (-218848 : ℝ) * u ^ 5 + (93072 : ℝ) * u ^ 4 + (-27712 : ℝ) * u ^ 3 + (5624 : ℝ) * u ^ 2 + (-720 : ℝ) * u + (72 : ℝ) := by
  rw [AcombN_symm]; exact AcombN_0_2_8 u

theorem AcombN_0_8_3 (u : ℝ) : AcombN 0 8 3 u = 0 := by
  rw [AcombN_symm]; exact AcombN_0_3_8 u

theorem AcombN_0_8_4 (u : ℝ) : AcombN 0 8 4 u = (112630 : ℝ) * u ^ 12 + (-613640 : ℝ) * u ^ 11 + (1551916 : ℝ) * u ^ 10 + (-2398568 : ℝ) * u ^ 9 + (2521386 : ℝ) * u ^ 8 + (-1902864 : ℝ) * u ^ 7 + (1062376 : ℝ) * u ^ 6 + (-445200 : ℝ) * u ^ 5 + (140394 : ℝ) * u ^ 4 + (-33000 : ℝ) * u ^ 3 + (5676 : ℝ) * u ^ 2 + (-648 : ℝ) * u + (54 : ℝ) := by
  rw [AcombN_symm]; exact AcombN_0_4_8 u

theorem AcombN_0_8_5 (u : ℝ) : AcombN 0 8 5 u = (16090 : ℝ) * u ^ 13 + (-124440 : ℝ) * u ^ 12 + (436260 : ℝ) * u ^ 11 + (-917080 : ℝ) * u ^ 10 + (1288070 : ℝ) * u ^ 9 + (-1274160 : ℝ) * u ^ 8 + (910840 : ℝ) * u ^ 7 + (-474480 : ℝ) * u ^ 6 + (178950 : ℝ) * u ^ 5 + (-47800 : ℝ) * u ^ 4 + (8740 : ℝ) * u ^ 3 + (-1080 : ℝ) * u ^ 2 + (90 : ℝ) * u := by
  rw [AcombN_symm]; exact AcombN_0_5_8 u

theorem AcombN_0_8_6 (u : ℝ) : AcombN 0 8 6 u = (371679 : ℝ) * u ^ 14 + (-2401518 : ℝ) * u ^ 13 + (7263795 : ℝ) * u ^ 12 + (-13604404 : ℝ) * u ^ 11 + (17607155 : ℝ) * u ^ 10 + (-16644634 : ℝ) * u ^ 9 + (11848087 : ℝ) * u ^ 8 + (-6455032 : ℝ) * u ^ 7 + (2712269 : ℝ) * u ^ 6 + (-881090 : ℝ) * u ^ 5 + (221385 : ℝ) * u ^ 4 + (-42900 : ℝ) * u ^ 3 + (6305 : ℝ) * u ^ 2 + (-630 : ℝ) * u + (45 : ℝ) := by
  rw [AcombN_symm]; exact AcombN_0_6_8 u

theorem AcombN_0_8_7 (u : ℝ) : AcombN 0 8 7 u = (146419 : ℝ) * u ^ 15 + (-1199982 : ℝ) * u ^ 14 + (4526403 : ℝ) * u ^ 13 + (-10439044 : ℝ) * u ^ 12 + (16489319 : ℝ) * u ^ 11 + (-18930618 : ℝ) * u ^ 10 + (16345063 : ℝ) * u ^ 9 + (-10819032 : ℝ) * u ^ 8 + (5534025 : ℝ) * u ^ 7 + (-2182978 : ℝ) * u ^ 6 + (656089 : ℝ) * u ^ 5 + (-146916 : ℝ) * u ^ 4 + (23709 : ℝ) * u ^ 3 + (-2646 : ℝ) * u ^ 2 + (189 : ℝ) * u := by
  rw [AcombN_symm]; exact AcombN_0_7_8 u

set_option maxHeartbeats 1000000 in
theorem AcombN_0_8_8 (u : ℝ) : AcombN 0 8 8 u = (2588881 / 2 : ℝ) * u ^ 16 + (-9666872 : ℝ) * u ^ 15 + (34041492 : ℝ) * u ^ 14 + (-74947096 : ℝ) * u ^ 13 + (115384542 : ℝ) * u ^ 12 + (-131651576 : ℝ) * u ^ 11 + (115120908 : ℝ) * u ^ 10 + (-78681944 : ℝ) * u ^ 9 + (42478963 : ℝ) * u ^ 8 + (-18187880 : ℝ) * u ^ 7 + (6172236 : ℝ) * u ^ 6 + (-1655304 : ℝ) * u ^ 5 + (349790 : ℝ) * u ^ 4 + (-57960 : ℝ) * u ^ 3 + (7380 : ℝ) * u ^ 2 + (-648 : ℝ) * u + (81 / 2 : ℝ) := by
  simp only [AcombN, S3N, Q3, tA, tD, tN, tF]
  linear_combination ((1490577 : ℝ) * u ^ 14 + (-7767374 : ℝ) * u ^ 13 + (2042146 : ℝ) * u ^ 12 * cU u ^ 2 + (19256315 : ℝ) * u ^ 12 + (-7780440 : ℝ) * u ^ 11 * cU u ^ 2 + (-29869804 : ℝ) * u ^ 11 + (1536068 : ℝ) * u ^ 10 * cU u ^ 4 + (14487076 : ℝ) * u ^ 10 * cU u ^ 2 + (32282601 : ℝ) * u ^ 10 + (-3313704 : ℝ) * u ^ 9 * cU u ^ 4 + (-16562488 : ℝ) * u ^ 9 * cU u ^ 2 + (-25651506 : ℝ) * u ^ 9 + (1129608 : ℝ) * u ^ 8 * cU u ^ 6 + (4754356 : ℝ) * u ^ 8 * cU u ^ 4 + (12939070 : ℝ) * u ^ 8 * cU u ^ 2 + (15431627 : ℝ) * u ^ 8 + (-698176 : ℝ) * u ^ 7 * cU u ^ 6 + (-4246240 : ℝ) * u ^ 7 * cU u ^ 4 + (-7256752 : ℝ) * u ^ 7 * cU u ^ 2 + (-7129576 : ℝ) * u ^ 7 + (569872 : ℝ) * u ^ 6 * cU u ^ 8 + (560224 : ℝ) * u ^ 6 * cU u ^ 6 + (2596104 : ℝ) * u ^ 6 * cU u ^ 4 + (3009272 : ℝ) * u ^ 6 * cU u ^ 2 + (2543051 : ℝ) * u ^ 6 + (-125536 : ℝ) * u ^ 5 * cU u ^ 8 + (-251328 : ℝ) * u ^ 5 * cU u ^ 6 + (-1060976 : ℝ) * u ^ 5 * cU u ^ 4 + (-926512 : ℝ) * u ^ 5 * cU u ^ 2 + (-698194 : ℝ) * u ^ 5 + (121888 : ℝ) * u ^ 4 * cU u ^ 10 + (70128 : ℝ) * u ^ 4 * cU u ^ 8 + (115248 : ℝ) * u ^ 4 * cU u ^ 6 + (296968 : ℝ) * u ^ 4 * cU u ^ 4 + (216638 : ℝ) * u ^ 4 * cU u ^ 2 + (147497 : ℝ) * u ^ 4 + (-7296 : ℝ) * u ^ 3 * cU u ^ 10 + (-7488 : ℝ) * u ^ 3 * cU u ^ 8 + (-34496 : ℝ) * u ^ 3 * cU u ^ 6 + (-54752 : ℝ) * u ^ 3 * cU u ^ 4 + (-36600 : ℝ) * u ^ 3 * cU u ^ 2 + (-23660 : ℝ) * u ^ 3 + (7232 : ℝ) * u ^ 2 * cU u ^ 12 + (3776 : ℝ) * u ^ 2 * cU u ^ 10 + (2032 : ℝ) * u ^ 2 * cU u ^ 8 + (8288 : ℝ) * u ^ 2 * cU u ^ 6 + (8884 : ℝ) * u ^ 2 * cU u ^ 4 + (5156 : ℝ) * u ^ 2 * cU u ^ 2 + (3003 : ℝ) * u ^ 2 + (-128 : ℝ) * u * cU u ^ 12 + (-128 : ℝ) * u * cU u ^ 10 + (-96 : ℝ) * u * cU u ^ 8 + (-1088 : ℝ) * u * cU u ^ 6 + (-680 : ℝ) * u * cU u ^ 4 + (-408 : ℝ) * u * cU u ^ 2 + (-238 : ℝ) * u + (128 : ℝ) * cU u ^ 14 + (64 : ℝ) * cU u ^ 12 + (32 : ℝ) * cU u ^ 10 + (16 : ℝ) * cU u ^ 8 + (136 : ℝ) * cU u ^ 6 + (68 : ℝ) * cU u ^ 4 + (34 : ℝ) * cU u ^ 2 + (17 : ℝ)) * cU_sq u

end Thomson
