import Thomson.Tri5b.Part000
import Thomson.Tri5b.Part001
import Thomson.Tri5b.Part002
import Thomson.Tri5b.Part003
import Thomson.Tri5b.Part004
import Thomson.Tri5b.Part005
import Thomson.Tri5b.Part006
import Thomson.Tri5b.Part007
import Thomson.Tri5b.Part008
import Thomson.Tri5b.Part009
import Thomson.Tri5b.Part010
import Thomson.Tri5b.Part011
import Thomson.Tri5b.Part012
import Thomson.Tri5b.Part013
import Thomson.Tri5b.Part014
import Thomson.Tri5b.Part015
import Thomson.Tri5b.Part016
import Thomson.Tri5b.Part017
import Thomson.Tri5b.Part018
import Thomson.Tri5b.Part019
import Thomson.Tri5b.Part020
import Thomson.Tri5b.Part021
import Thomson.Tri5b.Part022
import Thomson.Tri5b.Part023
import Thomson.Tri5b.Part024
import Thomson.Tri5b.Part025
import Thomson.Tri5b.Part026
import Thomson.Tri5b.Part027
import Thomson.Tri5b.Part028
import Thomson.Tri5b.Part029
import Thomson.Tri5b.Part030
import Thomson.Tri5b.Part031
import Thomson.Tri5b.Part032
import Thomson.Tri5b.Part033
import Thomson.Tri5b.Part034
import Thomson.Tri5b.Part035
import Thomson.Tri5b.Part036
import Thomson.Tri5b.Part037
import Thomson.Tri5b.Part038
import Thomson.Tri5b.Part039
import Thomson.Tri5b.Part040
import Thomson.Tri5b.Part041
import Thomson.Tri5b.Part042
import Thomson.Tri5b.Part043
import Thomson.Tri5b.Part044
import Thomson.Tri5b.Part045
import Thomson.Tri5b.Part046
import Thomson.Tri5b.Part047
import Thomson.Tri5b.Part048
import Thomson.Tri5b.Part049
import Thomson.Tri5b.Part050
import Thomson.Tri5b.Part051
import Thomson.Tri5b.Part052
import Thomson.Tri5b.Part053
import Thomson.Tri5b.Part054
import Thomson.Tri5b.Part055
import Thomson.Tri5b.Part056
import Thomson.Tri5b.Part057
import Thomson.Tri5b.Part058
import Thomson.Tri5b.Part059
import Thomson.Tri5b.Part060
import Thomson.Tri5b.Part061
import Thomson.Tri5b.Part062
import Thomson.Tri5b.Part063
import Thomson.Tri5b.Part064
import Thomson.Tri5b.Part065
import Thomson.Tri5b.Part066
import Thomson.Tri5b.Part067
import Thomson.Tri5b.Part068
import Thomson.Tri5b.Part069
import Thomson.Tri5b.Part070
import Thomson.Tri5b.Part071
import Thomson.Tri5b.Part072
import Thomson.Tri5b.Part073
import Thomson.Tri5b.Part074
import Thomson.Tri5b.Part075
import Thomson.Tri5b.Part076
import Thomson.Tri5b.Part077
import Thomson.Tri5b.Part078
import Thomson.Tri5b.Part079
import Thomson.Tri5b.Part080
import Thomson.Tri5b.Part081
import Thomson.Tri5b.Part082
import Thomson.Tri5b.Part083
import Thomson.Tri5b.Part084
import Thomson.Tri5b.Part085
import Thomson.Tri5b.Part086
import Thomson.Tri5b.Part087
import Thomson.Tri5b.Part088
import Thomson.Tri5b.Part089
import Thomson.Tri5b.Part090
import Thomson.Tri5b.Part091
import Thomson.Tri5b.Part092
import Thomson.Tri5b.Part093
import Thomson.Tri5b.Part094
import Thomson.Tri5b.Part095
import Thomson.Tri5b.Part096
import Thomson.Tri5b.Part097
import Thomson.Tri5b.Part098
import Thomson.Tri5b.Part099
import Thomson.Tri5b.Part100
import Thomson.Tri5b.Part101
import Thomson.Tri5b.Part102
import Thomson.Tri5b.Part103
import Thomson.Tri5b.Part104
import Thomson.Tri5b.Part105
import Thomson.Tri5b.Part106

/-! # Task 5b, step 18: the covering — GENERATED

The tree of `59347` nodes (`29674` leaves) is cut into `107` pieces, each checked by its own
`native_decide` in its own module; `covers_split` puts them back together.  Generated by
`threepoint/tri5b_parts.py`. -/

namespace Thomson.Tri5b

open Thomson

/-- **The covering.**  Every sorted triple in the root box satisfies the certificate's bound. -/
theorem cert_cover {c : RT} (hC : ITMem CFtab c) {ρ : Fin 5 → ℝ} (hD : CubeSound cubeD ρ) :
    Covers c MG ρ rootBx :=
  covers_split 0 (-8028972130377038563878509234266961721897)
    (covers_split 1 (-8028972130377038563878509234266961721897)
    (covers_of_bcheck hC hD FUEL Part036.cert Part036.box 1 Part036.ok)
    (covers_split 2 (1683453043120081310837733146781486508045)
    (covers_split 1 (-7953096412476931449293254873309128479077)
    (covers_of_bcheck hC hD FUEL Part101.cert Part101.box 1 Part101.ok)
    (covers_split 1 (-3751360530940982196128572032606513950176)
    (covers_split 2 (-4158273478439959344581133426609256745978)
    (covers_of_bcheck hC hD FUEL Part104.cert Part104.box 1 Part104.ok)
    (covers_split 2 (-1237410217659939016871700139913885118967)
    (covers_of_bcheck hC hD FUEL Part085.cert Part085.box 1 Part085.ok)
    (covers_split 1 (-5852228471708956822710913452957821214627)
    (covers_of_bcheck hC hD FUEL Part058.cert Part058.box 1 Part058.ok)
    (covers_split 2 (223021412730071146983016503433800694539)
    (covers_of_bcheck hC hD FUEL Part073.cert Part073.box 1 Part073.ok)
    (covers_split 1 (-4801794501324969509419742742782167582402)
    (covers_of_bcheck hC hD FUEL Part032.cert Part032.box 1 Part032.ok)
    (covers_of_bcheck hC hD FUEL Part021.cert Part021.box 1 Part021.ok))))))
    (covers_split 2 (-4158273478439959344581133426609256745978)
    (covers_of_bcheck hC hD FUEL Part106.cert Part106.box 1 Part106.ok)
    (covers_split 1 (-3685104753490943108622097488962546107951)
    (covers_of_bcheck hC hD FUEL Part051.cert Part051.box 1 Part051.ok)
    (covers_of_bcheck hC hD FUEL Part000.cert Part000.box 1 Part000.ok)))))
    (covers_split 1 (-7953096412476931449293254873309128479077)
    (covers_of_bcheck hC hD FUEL Part065.cert Part065.box 1 Part065.ok)
    (covers_split 1 (-3751360530940982196128572032606513950176)
    (covers_of_bcheck hC hD FUEL Part023.cert Part023.box 1 Part023.ok)
    (covers_split 1 (-3685104753490943108622097488962546107951)
    (covers_of_bcheck hC hD FUEL Part081.cert Part081.box 1 Part081.ok)
    (covers_split 1 (1683453043120081310837733146781486508045)
    (covers_split 1 (-1000825855185430898892182171090529799953)
    (covers_of_bcheck hC hD FUEL Part008.cert Part008.box 1 Part008.ok)
    (covers_split 2 (1734960784165814007084700482363657261281)
    (covers_of_bcheck hC hD FUEL Part093.cert Part093.box 1 Part093.ok)
    (covers_split 2 (3117448724128163984436613313837871208033)
    (covers_split 1 (341313593967325205972775487845478354046)
    (covers_of_bcheck hC hD FUEL Part040.cert Part040.box 1 Part040.ok)
    (covers_of_bcheck hC hD FUEL Part017.cert Part017.box 1 Part017.ok))
    (covers_of_bcheck hC hD FUEL Part045.cert Part045.box 1 Part045.ok))))
    (covers_of_bcheck hC hD FUEL Part003.cert Part003.box 1 Part003.ok)))))))
    (covers_split 1 (-8028972130377038563878509234266961721897)
    (covers_of_bcheck hC hD FUEL Part070.cert Part070.box 1 Part070.ok)
    (covers_split 2 (1683453043120081310837733146781486508045)
    (covers_split 0 (-7953096412476931449293254873309128479077)
    (covers_of_bcheck hC hD FUEL Part011.cert Part011.box 1 Part011.ok)
    (covers_of_bcheck hC hD FUEL Part002.cert Part002.box 1 Part002.ok))
    (covers_split 0 (-7953096412476931449293254873309128479077)
    (covers_split 1 (-7953096412476931449293254873309128479077)
    (covers_of_bcheck hC hD FUEL Part044.cert Part044.box 1 Part044.ok)
    (covers_split 1 (-3751360530940982196128572032606513950176)
    (covers_of_bcheck hC hD FUEL Part029.cert Part029.box 1 Part029.ok)
    (covers_split 1 (-3685104753490943108622097488962546107951)
    (covers_of_bcheck hC hD FUEL Part060.cert Part060.box 1 Part060.ok)
    (covers_split 1 (1683453043120081310837733146781486508045)
    (covers_split 1 (-1000825855185430898892182171090529799953)
    (covers_of_bcheck hC hD FUEL Part039.cert Part039.box 1 Part039.ok)
    (covers_of_bcheck hC hD FUEL Part013.cert Part013.box 1 Part013.ok))
    (covers_of_bcheck hC hD FUEL Part007.cert Part007.box 1 Part007.ok)))))
    (covers_split 1 (-7953096412476931449293254873309128479077)
    (covers_of_bcheck hC hD FUEL Part069.cert Part069.box 1 Part069.ok)
    (covers_split 0 (-3751360530940982196128572032606513950176)
    (covers_split 1 (-3751360530940982196128572032606513950176)
    (covers_split 0 (-5852228471708956822710913452957821214627)
    (covers_split 1 (-5852228471708956822710913452957821214627)
    (covers_of_bcheck hC hD FUEL Part028.cert Part028.box 1 Part028.ok)
    (covers_of_bcheck hC hD FUEL Part022.cert Part022.box 1 Part022.ok))
    (covers_of_bcheck hC hD FUEL Part076.cert Part076.box 1 Part076.ok))
    (covers_split 1 (-3685104753490943108622097488962546107951)
    (covers_of_bcheck hC hD FUEL Part077.cert Part077.box 1 Part077.ok)
    (covers_split 1 (1683453043120081310837733146781486508045)
    (covers_split 1 (-1000825855185430898892182171090529799953)
    (covers_of_bcheck hC hD FUEL Part054.cert Part054.box 1 Part054.ok)
    (covers_split 0 (-5852228471708956822710913452957821214627)
    (covers_split 2 (1734960784165814007084700482363657261281)
    (covers_of_bcheck hC hD FUEL Part089.cert Part089.box 1 Part089.ok)
    (covers_split 2 (3117448724128163984436613313837871208033)
    (covers_split 1 (341313593967325205972775487845478354046)
    (covers_of_bcheck hC hD FUEL Part064.cert Part064.box 1 Part064.ok)
    (covers_split 0 (-6902662442092944136002084163133474846852)
    (covers_split 2 (2426204754146988995760656898100764234657)
    (covers_of_bcheck hC hD FUEL Part080.cert Part080.box 1 Part080.ok)
    (covers_split 1 (1012383318543703258405254317313482431045)
    (covers_of_bcheck hC hD FUEL Part042.cert Part042.box 1 Part042.ok)
    (covers_split 0 (-7427879427284937792647669518221301662965)
    (covers_split 2 (2771826739137576490098635105969317721345)
    (covers_of_bcheck hC hD FUEL Part074.cert Part074.box 1 Part074.ok)
    (covers_split 1 (1347918180831892284621493732047484469545)
    (covers_split 0 (-7690487919880934620970462195765215071021)
    (covers_of_bcheck hC hD FUEL Part048.cert Part048.box 1 Part048.ok)
    (covers_split 2 (2944637731632870237267624209903594464689)
    (covers_of_bcheck hC hD FUEL Part010.cert Part010.box 1 Part010.ok)
    (covers_split 1 (1180150749687797771513374024680483450295)
    (covers_of_bcheck hC hD FUEL Part084.cert Part084.box 1 Part084.ok)
    (covers_split 0 (-7559183673582936206809065856993258366993)
    (covers_of_bcheck hC hD FUEL Part059.cert Part059.box 1 Part059.ok)
    (covers_split 2 (3031043227880517110852118761870732836361)
    (covers_split 1 (1264034465259845028067433878363983959920)
    (covers_of_bcheck hC hD FUEL Part083.cert Part083.box 1 Part083.ok)
    (covers_split 0 (-7493531550433936999728367687607280014979)
    (covers_of_bcheck hC hD FUEL Part049.cert Part049.box 1 Part049.ok)
    (covers_of_bcheck hC hD FUEL Part012.cert Part012.box 1 Part012.ok)))
    (covers_of_bcheck hC hD FUEL Part092.cert Part092.box 1 Part092.ok))))))
    (covers_split 0 (-7690487919880934620970462195765215071021)
    (covers_of_bcheck hC hD FUEL Part053.cert Part053.box 1 Part053.ok)
    (covers_of_bcheck hC hD FUEL Part006.cert Part006.box 1 Part006.ok))))
    (covers_split 2 (2771826739137576490098635105969317721345)
    (covers_of_bcheck hC hD FUEL Part082.cert Part082.box 1 Part082.ok)
    (covers_split 1 (1347918180831892284621493732047484469545)
    (covers_of_bcheck hC hD FUEL Part041.cert Part041.box 1 Part041.ok)
    (covers_split 0 (-7165270934688940964324876840677388254909)
    (covers_split 2 (2944637731632870237267624209903594464689)
    (covers_of_bcheck hC hD FUEL Part071.cert Part071.box 1 Part071.ok)
    (covers_split 1 (1515685611975986797729613439414485488795)
    (covers_split 0 (-7296575180986939378486273179449344958937)
    (covers_of_bcheck hC hD FUEL Part004.cert Part004.box 1 Part004.ok)
    (covers_of_bcheck hC hD FUEL Part052.cert Part052.box 1 Part052.ok))
    (covers_of_bcheck hC hD FUEL Part061.cert Part061.box 1 Part061.ok)))
    (covers_of_bcheck hC hD FUEL Part047.cert Part047.box 1 Part047.ok)))))))
    (covers_of_bcheck hC hD FUEL Part057.cert Part057.box 1 Part057.ok)))
    (covers_of_bcheck hC hD FUEL Part015.cert Part015.box 1 Part015.ok)))
    (covers_of_bcheck hC hD FUEL Part072.cert Part072.box 1 Part072.ok)))
    (covers_split 0 (-5852228471708956822710913452957821214627)
    (covers_split 1 (1734960784165814007084700482363657261281)
    (covers_of_bcheck hC hD FUEL Part034.cert Part034.box 1 Part034.ok)
    (covers_split 2 (1734960784165814007084700482363657261281)
    (covers_of_bcheck hC hD FUEL Part094.cert Part094.box 1 Part094.ok)
    (covers_split 1 (3117448724128163984436613313837871208033)
    (covers_split 2 (3117448724128163984436613313837871208033)
    (covers_of_bcheck hC hD FUEL Part037.cert Part037.box 1 Part037.ok)
    (covers_split 2 (3164298633655873363188051925377675108937)
    (covers_of_bcheck hC hD FUEL Part055.cert Part055.box 1 Part055.ok)
    (covers_split 2 (4269020291827936681594025962688837554468)
    (covers_split 0 (-6902662442092944136002084163133474846852)
    (covers_of_bcheck hC hD FUEL Part018.cert Part018.box 1 Part018.ok)
    (covers_of_bcheck hC hD FUEL Part024.cert Part024.box 1 Part024.ok))
    (covers_of_bcheck hC hD FUEL Part086.cert Part086.box 1 Part086.ok))))
    (covers_of_bcheck hC hD FUEL Part063.cert Part063.box 1 Part063.ok))))
    (covers_split 1 (1734960784165814007084700482363657261281)
    (covers_of_bcheck hC hD FUEL Part088.cert Part088.box 1 Part088.ok)
    (covers_split 2 (1734960784165814007084700482363657261281)
    (covers_of_bcheck hC hD FUEL Part097.cert Part097.box 1 Part097.ok)
    (covers_split 1 (3117448724128163984436613313837871208033)
    (covers_split 2 (3117448724128163984436613313837871208033)
    (covers_of_bcheck hC hD FUEL Part031.cert Part031.box 1 Part031.ok)
    (covers_split 2 (3164298633655873363188051925377675108937)
    (covers_of_bcheck hC hD FUEL Part046.cert Part046.box 1 Part046.ok)
    (covers_split 2 (4269020291827936681594025962688837554468)
    (covers_split 0 (-4801794501324969509419742742782167582402)
    (covers_of_bcheck hC hD FUEL Part030.cert Part030.box 1 Part030.ok)
    (covers_split 1 (2426204754146988995760656898100764234657)
    (covers_of_bcheck hC hD FUEL Part079.cert Part079.box 1 Part079.ok)
    (covers_split 2 (3716659462741905022391038944033256331702)
    (covers_split 0 (-4276577516132975852774157387694340766289)
    (covers_of_bcheck hC hD FUEL Part043.cert Part043.box 1 Part043.ok)
    (covers_split 1 (2771826739137576490098635105969317721345)
    (covers_of_bcheck hC hD FUEL Part062.cert Part062.box 1 Part062.ok)
    (covers_split 2 (3440479048198889192789545434705465720319)
    (covers_split 0 (-4013969023536979024451364710150427358233)
    (covers_of_bcheck hC hD FUEL Part056.cert Part056.box 1 Part056.ok)
    (covers_of_bcheck hC hD FUEL Part005.cert Part005.box 1 Part005.ok))
    (covers_of_bcheck hC hD FUEL Part078.cert Part078.box 1 Part078.ok))))
    (covers_of_bcheck hC hD FUEL Part090.cert Part090.box 1 Part090.ok))))
    (covers_of_bcheck hC hD FUEL Part087.cert Part087.box 1 Part087.ok))))
    (covers_of_bcheck hC hD FUEL Part027.cert Part027.box 1 Part027.ok))))))))
    (covers_split 1 (-3751360530940982196128572032606513950176)
    (covers_of_bcheck hC hD FUEL Part096.cert Part096.box 1 Part096.ok)
    (covers_split 0 (-3685104753490943108622097488962546107951)
    (covers_split 1 (-3685104753490943108622097488962546107951)
    (covers_of_bcheck hC hD FUEL Part102.cert Part102.box 1 Part102.ok)
    (covers_split 1 (1683453043120081310837733146781486508045)
    (covers_of_bcheck hC hD FUEL Part091.cert Part091.box 1 Part091.ok)
    (covers_split 1 (1734960784165814007084700482363657261281)
    (covers_of_bcheck hC hD FUEL Part100.cert Part100.box 1 Part100.ok)
    (covers_split 2 (1734960784165814007084700482363657261281)
    (covers_of_bcheck hC hD FUEL Part105.cert Part105.box 1 Part105.ok)
    (covers_split 1 (3117448724128163984436613313837871208033)
    (covers_of_bcheck hC hD FUEL Part001.cert Part001.box 1 Part001.ok)
    (covers_of_bcheck hC hD FUEL Part050.cert Part050.box 1 Part050.ok))))))
    (covers_split 1 (-3685104753490943108622097488962546107951)
    (covers_of_bcheck hC hD FUEL Part098.cert Part098.box 1 Part098.ok)
    (covers_split 0 (1683453043120081310837733146781486508045)
    (covers_split 1 (1683453043120081310837733146781486508045)
    (covers_of_bcheck hC hD FUEL Part033.cert Part033.box 1 Part033.ok)
    (covers_split 0 (-1000825855185430898892182171090529799953)
    (covers_split 1 (1734960784165814007084700482363657261281)
    (covers_of_bcheck hC hD FUEL Part095.cert Part095.box 1 Part095.ok)
    (covers_split 2 (1734960784165814007084700482363657261281)
    (covers_of_bcheck hC hD FUEL Part103.cert Part103.box 1 Part103.ok)
    (covers_split 1 (3117448724128163984436613313837871208033)
    (covers_of_bcheck hC hD FUEL Part009.cert Part009.box 1 Part009.ok)
    (covers_of_bcheck hC hD FUEL Part014.cert Part014.box 1 Part014.ok))))
    (covers_split 1 (1734960784165814007084700482363657261281)
    (covers_of_bcheck hC hD FUEL Part035.cert Part035.box 1 Part035.ok)
    (covers_split 2 (1734960784165814007084700482363657261281)
    (covers_of_bcheck hC hD FUEL Part099.cert Part099.box 1 Part099.ok)
    (covers_split 1 (3117448724128163984436613313837871208033)
    (covers_split 2 (3117448724128163984436613313837871208033)
    (covers_split 0 (341313593967325205972775487845478354046)
    (covers_of_bcheck hC hD FUEL Part068.cert Part068.box 1 Part068.ok)
    (covers_split 1 (2426204754146988995760656898100764234657)
    (covers_of_bcheck hC hD FUEL Part016.cert Part016.box 1 Part016.ok)
    (covers_of_bcheck hC hD FUEL Part038.cert Part038.box 1 Part038.ok)))
    (covers_split 0 (341313593967325205972775487845478354046)
    (covers_of_bcheck hC hD FUEL Part066.cert Part066.box 1 Part066.ok)
    (covers_split 2 (3164298633655873363188051925377675108937)
    (covers_of_bcheck hC hD FUEL Part019.cert Part019.box 1 Part019.ok)
    (covers_of_bcheck hC hD FUEL Part026.cert Part026.box 1 Part026.ok))))
    (covers_of_bcheck hC hD FUEL Part067.cert Part067.box 1 Part067.ok))))))
    (covers_split 1 (1683453043120081310837733146781486508045)
    (covers_of_bcheck hC hD FUEL Part075.cert Part075.box 1 Part075.ok)
    (covers_split 0 (1734960784165814007084700482363657261281)
    (covers_of_bcheck hC hD FUEL Part025.cert Part025.box 1 Part025.ok)
    (covers_of_bcheck hC hD FUEL Part020.cert Part020.box 1 Part020.ok))))))))))))

end Thomson.Tri5b
