import Thomson.Tri5b.Params

/-! # Task 5b: piece 102 of the covering — GENERATED

`3` leaves of the tree, over the box below.  Generated by `threepoint/tri5b_parts.py`. -/

namespace Thomson.Tri5b.Part102

open Thomson.Tri5b

def box : Bx := ⟨-3751360530940982196128572032606513950176, -3685104753490943108622097488962546107951, -3751360530940982196128572032606513950176, -3685104753490943108622097488962546107951, 1683453043120081310837733146781486508045, 5373741950000000000000000000000000000000⟩

def cert : ℕ :=
  37

theorem ok : bcheck CFtab MG cubeD FUEL cert box = some 1 := by native_decide

end Thomson.Tri5b.Part102
