import Thomson.Tri5b.Params

/-! # Task 5b: piece 93 of the covering — GENERATED

`14` leaves of the tree, over the box below.  Generated by `threepoint/tri5b_parts.py`. -/

namespace Thomson.Tri5b.Part093

open Thomson.Tri5b

def box : Bx := ⟨-10000000000000000000000000000000000000000, -8028972130377038563878509234266961721897, -1000825855185430898892182171090529799953, 1683453043120081310837733146781486508045, 1683453043120081310837733146781486508045, 1734960784165814007084700482363657261281⟩

def cert : ℕ :=
  154323303

theorem ok : bcheck CFtab MG cubeD FUEL cert box = some 1 := by native_decide

end Thomson.Tri5b.Part093
