import Thomson.Tri5b.Params

/-! # Task 5b: piece 73 of the covering — GENERATED

`67` leaves of the tree, over the box below.  Generated by `threepoint/tri5b_parts.py`. -/

namespace Thomson.Tri5b.Part073

open Thomson.Tri5b

def box : Bx := ⟨-10000000000000000000000000000000000000000, -8028972130377038563878509234266961721897, -5852228471708956822710913452957821214627, -3751360530940982196128572032606513950176, -1237410217659939016871700139913885118967, 223021412730071146983016503433800694539⟩

def cert : ℕ :=
  12522126230615529977564751705604052896955

theorem ok : bcheck CFtab MG cubeD FUEL cert box = some 1 := by native_decide

end Thomson.Tri5b.Part073
