import Thomson.Tri5b.Params

/-! # Task 5b: piece 101 of the covering — GENERATED

`3` leaves of the tree, over the box below.  Generated by `threepoint/tri5b_parts.py`. -/

namespace Thomson.Tri5b.Part101

open Thomson.Tri5b

def box : Bx := ⟨-10000000000000000000000000000000000000000, -8028972130377038563878509234266961721897, -8028972130377038563878509234266961721897, -7953096412476931449293254873309128479077, -10000000000000000000000000000000000000000, 1683453043120081310837733146781486508045⟩

def cert : ℕ :=
  37

theorem ok : bcheck CFtab MG cubeD FUEL cert box = some 1 := by native_decide

end Thomson.Tri5b.Part101
