import Thomson.Tri5b.Params

/-! # Task 5b: piece 85 of the covering — GENERATED

`21` leaves of the tree, over the box below.  Generated by `threepoint/tri5b_parts.py`. -/

namespace Thomson.Tri5b.Part085

open Thomson.Tri5b

def box : Bx := ⟨-10000000000000000000000000000000000000000, -8028972130377038563878509234266961721897, -7953096412476931449293254873309128479077, -3751360530940982196128572032606513950176, -4158273478439959344581133426609256745978, -1237410217659939016871700139913885118967⟩

def cert : ℕ :=
  2528826797229

theorem ok : bcheck CFtab MG cubeD FUEL cert box = some 1 := by native_decide

end Thomson.Tri5b.Part085
