import Thomson.Tri5b.Params

/-! # Task 5b: piece 89 of the covering — GENERATED

`17` leaves of the tree, over the box below.  Generated by `threepoint/tri5b_parts.py`. -/

namespace Thomson.Tri5b.Part089

open Thomson.Tri5b

def box : Bx := ⟨-7953096412476931449293254873309128479077, -5852228471708956822710913452957821214627, -1000825855185430898892182171090529799953, 1683453043120081310837733146781486508045, 1683453043120081310837733146781486508045, 1734960784165814007084700482363657261281⟩

def cert : ℕ :=
  9448288847

theorem ok : bcheck CFtab MG cubeD FUEL cert box = some 1 := by native_decide

end Thomson.Tri5b.Part089
