import Thomson.Tri5b.Params

/-! # Task 5b: piece 87 of the covering — GENERATED

`21` leaves of the tree, over the box below.  Generated by `threepoint/tri5b_parts.py`. -/

namespace Thomson.Tri5b.Part087

open Thomson.Tri5b

def box : Bx := ⟨-5852228471708956822710913452957821214627, -3751360530940982196128572032606513950176, 1734960784165814007084700482363657261281, 3117448724128163984436613313837871208033, 4269020291827936681594025962688837554468, 5373741950000000000000000000000000000000⟩

def cert : ℕ :=
  2526712056415

theorem ok : bcheck CFtab MG cubeD FUEL cert box = some 1 := by native_decide

end Thomson.Tri5b.Part087
