import Thomson.Tri5b.Params

/-! # Task 5b: piece 103 of the covering — GENERATED

`3` leaves of the tree, over the box below.  Generated by `threepoint/tri5b_parts.py`. -/

namespace Thomson.Tri5b.Part103

open Thomson.Tri5b

def box : Bx := ⟨-3685104753490943108622097488962546107951, -1000825855185430898892182171090529799953, 1734960784165814007084700482363657261281, 5373741950000000000000000000000000000000, 1683453043120081310837733146781486508045, 1734960784165814007084700482363657261281⟩

def cert : ℕ :=
  35

theorem ok : bcheck CFtab MG cubeD FUEL cert box = some 1 := by native_decide

end Thomson.Tri5b.Part103
