import Thomson.Tri5b.Params

/-! # Task 5b: piece 88 of the covering — GENERATED

`19` leaves of the tree, over the box below.  Generated by `threepoint/tri5b_parts.py`. -/

namespace Thomson.Tri5b.Part088

open Thomson.Tri5b

def box : Bx := ⟨-5852228471708956822710913452957821214627, -3751360530940982196128572032606513950176, 1683453043120081310837733146781486508045, 1734960784165814007084700482363657261281, 1683453043120081310837733146781486508045, 5373741950000000000000000000000000000000⟩

def cert : ℕ :=
  157923091261

theorem ok : bcheck CFtab MG cubeD FUEL cert box = some 1 := by native_decide

end Thomson.Tri5b.Part088
