import Thomson.Tri5b.Params

/-! # Task 5b: piece 74 of the covering — GENERATED

`67` leaves of the tree, over the box below.  Generated by `threepoint/tri5b_parts.py`. -/

namespace Thomson.Tri5b.Part074

open Thomson.Tri5b

def box : Bx := ⟨-7953096412476931449293254873309128479077, -7427879427284937792647669518221301662965, 1012383318543703258405254317313482431045, 1683453043120081310837733146781486508045, 2426204754146988995760656898100764234657, 2771826739137576490098635105969317721345⟩

def cert : ℕ :=
  11722579952318551217578524427820365035295

theorem ok : bcheck CFtab MG cubeD FUEL cert box = some 1 := by native_decide

end Thomson.Tri5b.Part074
