import Thomson.Tri5b.Params

/-! # Task 5b: piece 104 of the covering — GENERATED

`2` leaves of the tree, over the box below.  Generated by `threepoint/tri5b_parts.py`. -/

namespace Thomson.Tri5b.Part104

open Thomson.Tri5b

def box : Bx := ⟨-10000000000000000000000000000000000000000, -8028972130377038563878509234266961721897, -7953096412476931449293254873309128479077, -3751360530940982196128572032606513950176, -10000000000000000000000000000000000000000, -4158273478439959344581133426609256745978⟩

def cert : ℕ :=
  9

theorem ok : bcheck CFtab MG cubeD FUEL cert box = some 1 := by native_decide

end Thomson.Tri5b.Part104
