-- GENERATED by scripts/threepoint/tri5b_kparts.py; do not edit
import Thomson.TriangleGlobal.KernelLeaf
import Thomson.TriangleGlobal.KernelTable
import Thomson.TriangleGlobal.Params

/-! # Task 5b: piece 554 of the covering, kernel-checked — GENERATED

`5` leaves of the tree in `2` groups, over the box below.  Each group is one `decide +kernel`. -/

namespace Thomson.TriangleGlobal.Covering.Part554

open Thomson.Tri5b

def box_0 : Bx := ⟨-3685104753490943108622097488962546107951, -3014035028914565056189618659494542030952, 3716659462741905022391038944033256331702, 4269020291827936681594025962688837554468, 3164298633655873363188051925377675108937, 3716659462741905022391038944033256331702⟩

def cert_0 : ℕ :=
  147

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem ok_0 : kbcheck CFtabL MG cubeD FUEL cert_0 box_0 = some 1 := by decide +kernel

def box_1 : Bx := ⟨-3685104753490943108622097488962546107951, -3014035028914565056189618659494542030952, 3716659462741905022391038944033256331702, 4269020291827936681594025962688837554468, 3716659462741905022391038944033256331702, 4269020291827936681594025962688837554468⟩

def cert_1 : ℕ :=
  2

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem ok_1 : kbcheck CFtabL MG cubeD FUEL cert_1 box_1 = some 1 := by decide +kernel

set_option maxRecDepth 100000 in
/-- The covering of this piece's box. -/
theorem cover {c : RT} (hC : Mem3 CFtabL (ofRT c)) {ρ : Fin 5 → ℝ} (hD : CubeSound cubeD ρ) :
    Covers c MG ρ (⟨-3685104753490943108622097488962546107951, -3014035028914565056189618659494542030952, 3716659462741905022391038944033256331702, 4269020291827936681594025962688837554468, 3164298633655873363188051925377675108937, 4269020291827936681594025962688837554468⟩) :=
  covers_split 2 (3716659462741905022391038944033256331702)
    (covers_of_kbcheck hC hD FUEL cert_0 box_0 1 ok_0)
    (covers_of_kbcheck hC hD FUEL cert_1 box_1 1 ok_1)

end Thomson.TriangleGlobal.Covering.Part554
