-- GENERATED by scripts/threepoint/tri5b_kparts.py; do not edit
import Thomson.TriangleGlobal.KernelLeaf
import Thomson.TriangleGlobal.KernelTable
import Thomson.TriangleGlobal.Params

/-! # Task 5b: piece 625 of the covering, kernel-checked — GENERATED

`1` leaves of the tree in `1` groups, over the box below.  Each group is one `decide +kernel`. -/

namespace Thomson.TriangleGlobal.Covering.Part625

open Thomson.Tri5b

def box_0 : Bx := ⟨-5852228471708956822710913452957821214627, -4801794501324969509419742742782167582402, 3117448724128163984436613313837871208033, 3164298633655873363188051925377675108937, 3117448724128163984436613313837871208033, 3164298633655873363188051925377675108937⟩

def cert_0 : ℕ :=
  2

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem ok_0 : kbcheck CFtabL MG cubeD FUEL cert_0 box_0 = some 1 := by decide +kernel

set_option maxRecDepth 100000 in
/-- The covering of this piece's box. -/
theorem cover {c : RT} (hC : Mem3 CFtabL (ofRT c)) {ρ : Fin 5 → ℝ} (hD : CubeSound cubeD ρ) :
    Covers c MG ρ (⟨-5852228471708956822710913452957821214627, -4801794501324969509419742742782167582402, 3117448724128163984436613313837871208033, 3164298633655873363188051925377675108937, 3117448724128163984436613313837871208033, 3164298633655873363188051925377675108937⟩) :=
  covers_of_kbcheck hC hD FUEL cert_0 box_0 1 ok_0

end Thomson.TriangleGlobal.Covering.Part625
