-- GENERATED by scripts/threepoint/tri5b_kparts.py; do not edit
import Thomson.TriangleGlobal.KernelLeaf
import Thomson.TriangleGlobal.KernelTable
import Thomson.TriangleGlobal.Params

/-! # Task 5b: piece 510 of the covering, kernel-checked — GENERATED

`9` leaves of the tree in `3` groups, over the box below.  Each group is one `decide +kernel`. -/

namespace Thomson.TriangleGlobal.Covering.Part510

open Thomson.Tri5b

def box_0 : Bx := ⟨1515685611975986797729613439414485488795, 1557627469762010426006643366256235743607, 1683453043120081310837733146781486508045, 1734960784165814007084700482363657261281, 3117448724128163984436613313837871208033, 3164298633655873363188051925377675108937⟩

def cert_0 : ℕ :=
  37

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem ok_0 : kbcheck CFtabL MG cubeD FUEL cert_0 box_0 = some 1 := by decide +kernel

def box_1 : Bx := ⟨1557627469762010426006643366256235743607, 1599569327548034054283673293097985998420, 1683453043120081310837733146781486508045, 1709206913642947658961216814572571884663, 3117448724128163984436613313837871208033, 3164298633655873363188051925377675108937⟩

def cert_1 : ℕ :=
  9

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem ok_1 : kbcheck CFtabL MG cubeD FUEL cert_1 box_1 = some 1 := by decide +kernel

def box_2 : Bx := ⟨1557627469762010426006643366256235743607, 1599569327548034054283673293097985998420, 1709206913642947658961216814572571884663, 1734960784165814007084700482363657261281, 3117448724128163984436613313837871208033, 3164298633655873363188051925377675108937⟩

def cert_2 : ℕ :=
  149

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem ok_2 : kbcheck CFtabL MG cubeD FUEL cert_2 box_2 = some 1 := by decide +kernel

set_option maxRecDepth 100000 in
/-- The covering of this piece's box. -/
theorem cover {c : RT} (hC : Mem3 CFtabL (ofRT c)) {ρ : Fin 5 → ℝ} (hD : CubeSound cubeD ρ) :
    Covers c MG ρ (⟨1515685611975986797729613439414485488795, 1599569327548034054283673293097985998420, 1683453043120081310837733146781486508045, 1734960784165814007084700482363657261281, 3117448724128163984436613313837871208033, 3164298633655873363188051925377675108937⟩) :=
  covers_split 0 (1557627469762010426006643366256235743607)
    (covers_of_kbcheck hC hD FUEL cert_0 box_0 1 ok_0)
    (covers_split 1 (1709206913642947658961216814572571884663)
    (covers_of_kbcheck hC hD FUEL cert_1 box_1 1 ok_1)
    (covers_of_kbcheck hC hD FUEL cert_2 box_2 1 ok_2))

end Thomson.TriangleGlobal.Covering.Part510
