-- GENERATED by scripts/threepoint/tri5b_kparts.py; do not edit
import Thomson.TriangleGlobal.KernelLeaf
import Thomson.TriangleGlobal.KernelTable
import Thomson.TriangleGlobal.Params

/-! # Task 5b: piece 506 of the covering, kernel-checked — GENERATED

`9` leaves of the tree in `3` groups, over the box below.  Each group is one `decide +kernel`. -/

namespace Thomson.TriangleGlobal.Covering.Part506

open Thomson.Tri5b

def box_0 : Bx := ⟨-7427879427284937792647669518221301662965, -7296575180986939378486273179449344958937, 1012383318543703258405254317313482431045, 1180150749687797771513374024680483450295, 2944637731632870237267624209903594464689, 3031043227880517110852118761870732836361⟩

def cert_0 : ℕ :=
  141

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem ok_0 : kbcheck CFtabL MG cubeD FUEL cert_0 box_0 = some 1 := by decide +kernel

def box_1 : Bx := ⟨-7427879427284937792647669518221301662965, -7296575180986939378486273179449344958937, 1012383318543703258405254317313482431045, 1180150749687797771513374024680483450295, 3031043227880517110852118761870732836361, 3117448724128163984436613313837871208033⟩

def cert_1 : ℕ :=
  9

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem ok_1 : kbcheck CFtabL MG cubeD FUEL cert_1 box_1 = some 1 := by decide +kernel

def box_2 : Bx := ⟨-7296575180986939378486273179449344958937, -7165270934688940964324876840677388254909, 1012383318543703258405254317313482431045, 1180150749687797771513374024680483450295, 2944637731632870237267624209903594464689, 3117448724128163984436613313837871208033⟩

def cert_2 : ℕ :=
  35

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem ok_2 : kbcheck CFtabL MG cubeD FUEL cert_2 box_2 = some 1 := by decide +kernel

set_option maxRecDepth 100000 in
/-- The covering of this piece's box. -/
theorem cover {c : RT} (hC : Mem3 CFtabL (ofRT c)) {ρ : Fin 5 → ℝ} (hD : CubeSound cubeD ρ) :
    Covers c MG ρ (⟨-7427879427284937792647669518221301662965, -7165270934688940964324876840677388254909, 1012383318543703258405254317313482431045, 1180150749687797771513374024680483450295, 2944637731632870237267624209903594464689, 3117448724128163984436613313837871208033⟩) :=
  covers_split 0 (-7296575180986939378486273179449344958937)
    (covers_split 2 (3031043227880517110852118761870732836361)
    (covers_of_kbcheck hC hD FUEL cert_0 box_0 1 ok_0)
    (covers_of_kbcheck hC hD FUEL cert_1 box_1 1 ok_1))
    (covers_of_kbcheck hC hD FUEL cert_2 box_2 1 ok_2)

end Thomson.TriangleGlobal.Covering.Part506
