-- GENERATED by scripts/threepoint/tri5b_kparts.py; do not edit
import Thomson.TriangleGlobal.KernelLeaf
import Thomson.TriangleGlobal.KernelTable
import Thomson.TriangleGlobal.Params

/-! # Task 5b: piece 532 of the covering, kernel-checked — GENERATED

`6` leaves of the tree in `3` groups, over the box below.  Each group is one `decide +kernel`. -/

namespace Thomson.TriangleGlobal.Covering.Part532

open Thomson.Tri5b

def box_0 : Bx := ⟨-5852228471708956822710913452957821214627, -4801794501324969509419742742782167582402, 1734960784165814007084700482363657261281, 3117448724128163984436613313837871208033, 1683453043120081310837733146781486508045, 1734960784165814007084700482363657261281⟩

def cert_0 : ℕ :=
  35

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem ok_0 : kbcheck CFtabL MG cubeD FUEL cert_0 box_0 = some 1 := by decide +kernel

def box_1 : Bx := ⟨-4801794501324969509419742742782167582402, -3751360530940982196128572032606513950176, 1734960784165814007084700482363657261281, 3117448724128163984436613313837871208033, 1683453043120081310837733146781486508045, 1734960784165814007084700482363657261281⟩

def cert_1 : ℕ :=
  9

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem ok_1 : kbcheck CFtabL MG cubeD FUEL cert_1 box_1 = some 1 := by decide +kernel

def box_2 : Bx := ⟨-5852228471708956822710913452957821214627, -3751360530940982196128572032606513950176, 3117448724128163984436613313837871208033, 5373741950000000000000000000000000000000, 1683453043120081310837733146781486508045, 1734960784165814007084700482363657261281⟩

def cert_2 : ℕ :=
  2

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem ok_2 : kbcheck CFtabL MG cubeD FUEL cert_2 box_2 = some 1 := by decide +kernel

set_option maxRecDepth 100000 in
/-- The covering of this piece's box. -/
theorem cover {c : RT} (hC : Mem3 CFtabL (ofRT c)) {ρ : Fin 5 → ℝ} (hD : CubeSound cubeD ρ) :
    Covers c MG ρ (⟨-5852228471708956822710913452957821214627, -3751360530940982196128572032606513950176, 1734960784165814007084700482363657261281, 5373741950000000000000000000000000000000, 1683453043120081310837733146781486508045, 1734960784165814007084700482363657261281⟩) :=
  covers_split 1 (3117448724128163984436613313837871208033)
    (covers_split 0 (-4801794501324969509419742742782167582402)
    (covers_of_kbcheck hC hD FUEL cert_0 box_0 1 ok_0)
    (covers_of_kbcheck hC hD FUEL cert_1 box_1 1 ok_1))
    (covers_of_kbcheck hC hD FUEL cert_2 box_2 1 ok_2)

end Thomson.TriangleGlobal.Covering.Part532
