-- GENERATED by scripts/threepoint/tri5b_kparts.py; do not edit
import Thomson.TriangleGlobal.KernelLeaf
import Thomson.TriangleGlobal.KernelTable
import Thomson.TriangleGlobal.Params

/-! # Task 5b: piece 515 of the covering, kernel-checked — GENERATED

`8` leaves of the tree in `3` groups, over the box below.  Each group is one `decide +kernel`. -/

namespace Thomson.TriangleGlobal.Covering.Part515

open Thomson.Tri5b

def box_0 : Bx := ⟨-3517337322346848595513977781595545088702, -3475395464560824967236947854753794833890, 3117448724128163984436613313837871208033, 3164298633655873363188051925377675108937, 3117448724128163984436613313837871208033, 3164298633655873363188051925377675108937⟩

def cert_0 : ℕ :=
  147

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem ok_0 : kbcheck CFtabL MG cubeD FUEL cert_0 box_0 = some 1 := by decide +kernel

def box_1 : Bx := ⟨-3475395464560824967236947854753794833890, -3433453606774801338959917927912044579077, 3117448724128163984436613313837871208033, 3164298633655873363188051925377675108937, 3117448724128163984436613313837871208033, 3164298633655873363188051925377675108937⟩

def cert_1 : ℕ :=
  9

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem ok_1 : kbcheck CFtabL MG cubeD FUEL cert_1 box_1 = some 1 := by decide +kernel

def box_2 : Bx := ⟨-3433453606774801338959917927912044579077, -3349569891202754082405858074228544069452, 3117448724128163984436613313837871208033, 3164298633655873363188051925377675108937, 3117448724128163984436613313837871208033, 3164298633655873363188051925377675108937⟩

def cert_2 : ℕ :=
  9

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem ok_2 : kbcheck CFtabL MG cubeD FUEL cert_2 box_2 = some 1 := by decide +kernel

set_option maxRecDepth 100000 in
/-- The covering of this piece's box. -/
theorem cover {c : RT} (hC : Mem3 CFtabL (ofRT c)) {ρ : Fin 5 → ℝ} (hD : CubeSound cubeD ρ) :
    Covers c MG ρ (⟨-3517337322346848595513977781595545088702, -3349569891202754082405858074228544069452, 3117448724128163984436613313837871208033, 3164298633655873363188051925377675108937, 3117448724128163984436613313837871208033, 3164298633655873363188051925377675108937⟩) :=
  covers_split 0 (-3433453606774801338959917927912044579077)
    (covers_split 0 (-3475395464560824967236947854753794833890)
    (covers_of_kbcheck hC hD FUEL cert_0 box_0 1 ok_0)
    (covers_of_kbcheck hC hD FUEL cert_1 box_1 1 ok_1))
    (covers_of_kbcheck hC hD FUEL cert_2 box_2 1 ok_2)

end Thomson.TriangleGlobal.Covering.Part515
