-- GENERATED by scripts/threepoint/tri5b_kparts.py; do not edit
import Thomson.TriangleGlobal.KernelLeaf
import Thomson.TriangleGlobal.KernelTable
import Thomson.TriangleGlobal.Params

/-! # Task 5b: piece 598 of the covering, kernel-checked — GENERATED

`2` leaves of the tree in `1` groups, over the box below.  Each group is one `decide +kernel`. -/

namespace Thomson.TriangleGlobal.Covering.Part598

open Thomson.Tri5b

def box_0 : Bx := ⟨-8028972130377038563878509234266961721897, -7953096412476931449293254873309128479077, -3751360530940982196128572032606513950176, -3685104753490943108622097488962546107951, -4158273478439959344581133426609256745978, -1237410217659939016871700139913885118967⟩

def cert_0 : ℕ :=
  9

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem ok_0 : kbcheck CFtabL MG cubeD FUEL cert_0 box_0 = some 1 := by decide +kernel

set_option maxRecDepth 100000 in
/-- The covering of this piece's box. -/
theorem cover {c : RT} (hC : Mem3 CFtabL (ofRT c)) {ρ : Fin 5 → ℝ} (hD : CubeSound cubeD ρ) :
    Covers c MG ρ (⟨-8028972130377038563878509234266961721897, -7953096412476931449293254873309128479077, -3751360530940982196128572032606513950176, -3685104753490943108622097488962546107951, -4158273478439959344581133426609256745978, -1237410217659939016871700139913885118967⟩) :=
  covers_of_kbcheck hC hD FUEL cert_0 box_0 1 ok_0

end Thomson.TriangleGlobal.Covering.Part598
