-- GENERATED by scripts/threepoint/tri5b_kparts.py; do not edit
import Thomson.TriangleGlobal.KernelLeaf
import Thomson.TriangleGlobal.KernelTable
import Thomson.TriangleGlobal.Params

/-! # Task 5b: piece 519 of the covering, kernel-checked — GENERATED

`7` leaves of the tree in `3` groups, over the box below.  Each group is one `decide +kernel`. -/

namespace Thomson.TriangleGlobal.Covering.Part519

open Thomson.Tri5b

def box_0 : Bx := ⟨-8028972130377038563878509234266961721897, -7953096412476931449293254873309128479077, -3751360530940982196128572032606513950176, -3685104753490943108622097488962546107951, 953237227925076228910374825107643601292, 1135791181723827499392214405526104327980⟩

def cert_0 : ℕ :=
  9

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem ok_0 : kbcheck CFtabL MG cubeD FUEL cert_0 box_0 = some 1 := by decide +kernel

def box_1 : Bx := ⟨-8028972130377038563878509234266961721897, -7953096412476931449293254873309128479077, -3751360530940982196128572032606513950176, -3685104753490943108622097488962546107951, 1135791181723827499392214405526104327980, 1227068158623203134633134195735334691324⟩

def cert_1 : ℕ :=
  9

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem ok_1 : kbcheck CFtabL MG cubeD FUEL cert_1 box_1 = some 1 := by decide +kernel

def box_2 : Bx := ⟨-8028972130377038563878509234266961721897, -7953096412476931449293254873309128479077, -3751360530940982196128572032606513950176, -3685104753490943108622097488962546107951, 1227068158623203134633134195735334691324, 1318345135522578769874053985944565054668⟩

def cert_2 : ℕ :=
  37

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem ok_2 : kbcheck CFtabL MG cubeD FUEL cert_2 box_2 = some 1 := by decide +kernel

set_option maxRecDepth 100000 in
/-- The covering of this piece's box. -/
theorem cover {c : RT} (hC : Mem3 CFtabL (ofRT c)) {ρ : Fin 5 → ℝ} (hD : CubeSound cubeD ρ) :
    Covers c MG ρ (⟨-8028972130377038563878509234266961721897, -7953096412476931449293254873309128479077, -3751360530940982196128572032606513950176, -3685104753490943108622097488962546107951, 953237227925076228910374825107643601292, 1318345135522578769874053985944565054668⟩) :=
  covers_split 2 (1135791181723827499392214405526104327980)
    (covers_of_kbcheck hC hD FUEL cert_0 box_0 1 ok_0)
    (covers_split 2 (1227068158623203134633134195735334691324)
    (covers_of_kbcheck hC hD FUEL cert_1 box_1 1 ok_1)
    (covers_of_kbcheck hC hD FUEL cert_2 box_2 1 ok_2))

end Thomson.TriangleGlobal.Covering.Part519
