-- GENERATED by scripts/threepoint/tri5b_kparts.py; do not edit
import Thomson.TriangleGlobal.KernelLeaf
import Thomson.TriangleGlobal.KernelTable
import Thomson.TriangleGlobal.Params

/-! # Task 5b: piece 490 of the covering, kernel-checked — GENERATED

`10` leaves of the tree in `3` groups, over the box below.  Each group is one `decide +kernel`. -/

namespace Thomson.TriangleGlobal.Covering.Part490

open Thomson.Tri5b

def box_0 : Bx := ⟨-8028972130377038563878509234266961721897, -7953096412476931449293254873309128479077, -4801794501324969509419742742782167582402, -4539186008728972681096950065238254174346, 1734960784165814007084700482363657261281, 2080582769156401501422678690232210747969⟩

def cert_0 : ℕ :=
  9

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem ok_0 : kbcheck CFtabL MG cubeD FUEL cert_0 box_0 = some 1 := by decide +kernel

def box_1 : Bx := ⟨-8028972130377038563878509234266961721897, -7953096412476931449293254873309128479077, -4539186008728972681096950065238254174346, -4276577516132975852774157387694340766289, 1734960784165814007084700482363657261281, 2080582769156401501422678690232210747969⟩

def cert_1 : ℕ :=
  147

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem ok_1 : kbcheck CFtabL MG cubeD FUEL cert_1 box_1 = some 1 := by decide +kernel

def box_2 : Bx := ⟨-8028972130377038563878509234266961721897, -7953096412476931449293254873309128479077, -4801794501324969509419742742782167582402, -4276577516132975852774157387694340766289, 2080582769156401501422678690232210747969, 2426204754146988995760656898100764234657⟩

def cert_2 : ℕ :=
  147

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem ok_2 : kbcheck CFtabL MG cubeD FUEL cert_2 box_2 = some 1 := by decide +kernel

set_option maxRecDepth 100000 in
/-- The covering of this piece's box. -/
theorem cover {c : RT} (hC : Mem3 CFtabL (ofRT c)) {ρ : Fin 5 → ℝ} (hD : CubeSound cubeD ρ) :
    Covers c MG ρ (⟨-8028972130377038563878509234266961721897, -7953096412476931449293254873309128479077, -4801794501324969509419742742782167582402, -4276577516132975852774157387694340766289, 1734960784165814007084700482363657261281, 2426204754146988995760656898100764234657⟩) :=
  covers_split 2 (2080582769156401501422678690232210747969)
    (covers_split 1 (-4539186008728972681096950065238254174346)
    (covers_of_kbcheck hC hD FUEL cert_0 box_0 1 ok_0)
    (covers_of_kbcheck hC hD FUEL cert_1 box_1 1 ok_1))
    (covers_of_kbcheck hC hD FUEL cert_2 box_2 1 ok_2)

end Thomson.TriangleGlobal.Covering.Part490
