-- GENERATED by scripts/threepoint/tri5b_kparts.py; do not edit
import Thomson.TriangleGlobal.KernelLeaf
import Thomson.TriangleGlobal.KernelTable
import Thomson.TriangleGlobal.Params

/-! # Task 5b: piece 495 of the covering, kernel-checked — GENERATED

`10` leaves of the tree in `3` groups, over the box below.  Each group is one `decide +kernel`. -/

namespace Thomson.TriangleGlobal.Covering.Part495

open Thomson.Tri5b

def box_0 : Bx := ⟨-3685104753490943108622097488962546107951, -3014035028914565056189618659494542030952, 2426204754146988995760656898100764234657, 2771826739137576490098635105969317721345, 3716659462741905022391038944033256331702, 4269020291827936681594025962688837554468⟩

def cert_0 : ℕ :=
  147

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem ok_0 : kbcheck CFtabL MG cubeD FUEL cert_0 box_0 = some 1 := by decide +kernel

def box_1 : Bx := ⟨-3685104753490943108622097488962546107951, -3349569891202754082405858074228544069452, 2771826739137576490098635105969317721345, 3117448724128163984436613313837871208033, 3716659462741905022391038944033256331702, 4269020291827936681594025962688837554468⟩

def cert_1 : ℕ :=
  35

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem ok_1 : kbcheck CFtabL MG cubeD FUEL cert_1 box_1 = some 1 := by decide +kernel

def box_2 : Bx := ⟨-3349569891202754082405858074228544069452, -3014035028914565056189618659494542030952, 2771826739137576490098635105969317721345, 3117448724128163984436613313837871208033, 3716659462741905022391038944033256331702, 4269020291827936681594025962688837554468⟩

def cert_2 : ℕ :=
  35

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem ok_2 : kbcheck CFtabL MG cubeD FUEL cert_2 box_2 = some 1 := by decide +kernel

set_option maxRecDepth 100000 in
/-- The covering of this piece's box. -/
theorem cover {c : RT} (hC : Mem3 CFtabL (ofRT c)) {ρ : Fin 5 → ℝ} (hD : CubeSound cubeD ρ) :
    Covers c MG ρ (⟨-3685104753490943108622097488962546107951, -3014035028914565056189618659494542030952, 2426204754146988995760656898100764234657, 3117448724128163984436613313837871208033, 3716659462741905022391038944033256331702, 4269020291827936681594025962688837554468⟩) :=
  covers_split 1 (2771826739137576490098635105969317721345)
    (covers_of_kbcheck hC hD FUEL cert_0 box_0 1 ok_0)
    (covers_split 0 (-3349569891202754082405858074228544069452)
    (covers_of_kbcheck hC hD FUEL cert_1 box_1 1 ok_1)
    (covers_of_kbcheck hC hD FUEL cert_2 box_2 1 ok_2))

end Thomson.TriangleGlobal.Covering.Part495
