-- GENERATED by scripts/threepoint/tri5b_kparts.py; do not edit
import Thomson.TriangleGlobal.KernelLeaf
import Thomson.TriangleGlobal.KernelTable
import Thomson.TriangleGlobal.Params

/-! # Task 5b: piece 560 of the covering, kernel-checked — GENERATED

`4` leaves of the tree in `1` groups, over the box below.  Each group is one `decide +kernel`. -/

namespace Thomson.TriangleGlobal.Covering.Part560

open Thomson.Tri5b

def box_0 : Bx := ⟨-9014486065188519281939254617133480860949, -8521729097782778922908881925700221291423, -3685104753490943108622097488962546107951, -3014035028914565056189618659494542030952, 953237227925076228910374825107643601292, 1683453043120081310837733146781486508045⟩

def cert_0 : ℕ :=
  147

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem ok_0 : kbcheck CFtabL MG cubeD FUEL cert_0 box_0 = some 1 := by decide +kernel

set_option maxRecDepth 100000 in
/-- The covering of this piece's box. -/
theorem cover {c : RT} (hC : Mem3 CFtabL (ofRT c)) {ρ : Fin 5 → ℝ} (hD : CubeSound cubeD ρ) :
    Covers c MG ρ (⟨-9014486065188519281939254617133480860949, -8521729097782778922908881925700221291423, -3685104753490943108622097488962546107951, -3014035028914565056189618659494542030952, 953237227925076228910374825107643601292, 1683453043120081310837733146781486508045⟩) :=
  covers_of_kbcheck hC hD FUEL cert_0 box_0 1 ok_0

end Thomson.TriangleGlobal.Covering.Part560
