-- GENERATED by scripts/threepoint/tri5b_kparts.py; do not edit
import Thomson.TriangleGlobal.KernelLeaf
import Thomson.TriangleGlobal.KernelTable
import Thomson.TriangleGlobal.Params

/-! # Task 5b: piece 600 of the covering, kernel-checked — GENERATED

`2` leaves of the tree in `1` groups, over the box below.  Each group is one `decide +kernel`. -/

namespace Thomson.TriangleGlobal.Covering.Part600

open Thomson.Tri5b

def box_0 : Bx := ⟨-8028972130377038563878509234266961721897, -7953096412476931449293254873309128479077, -8028972130377038563878509234266961721897, -7953096412476931449293254873309128479077, 3440479048198889192789545434705465720319, 3716659462741905022391038944033256331702⟩

def cert_0 : ℕ :=
  9

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem ok_0 : kbcheck CFtabL MG cubeD FUEL cert_0 box_0 = some 1 := by decide +kernel

set_option maxRecDepth 100000 in
/-- The covering of this piece's box. -/
theorem cover {c : RT} (hC : Mem3 CFtabL (ofRT c)) {ρ : Fin 5 → ℝ} (hD : CubeSound cubeD ρ) :
    Covers c MG ρ (⟨-8028972130377038563878509234266961721897, -7953096412476931449293254873309128479077, -8028972130377038563878509234266961721897, -7953096412476931449293254873309128479077, 3440479048198889192789545434705465720319, 3716659462741905022391038944033256331702⟩) :=
  covers_of_kbcheck hC hD FUEL cert_0 box_0 1 ok_0

end Thomson.TriangleGlobal.Covering.Part600
