-- GENERATED by scripts/threepoint/tri5b_kparts.py; do not edit
import Thomson.TriangleGlobal.KernelLeaf
import Thomson.TriangleGlobal.KernelTable
import Thomson.TriangleGlobal.Params

/-! # Task 5b: piece 517 of the covering, kernel-checked — GENERATED

`7` leaves of the tree in `2` groups, over the box below.  Each group is one `decide +kernel`. -/

namespace Thomson.TriangleGlobal.Covering.Part517

open Thomson.Tri5b

def box_0 : Bx := ⟨-9014486065188519281939254617133480860949, -8521729097782778922908881925700221291423, -4276577516132975852774157387694340766289, -3751360530940982196128572032606513950176, 953237227925076228910374825107643601292, 1318345135522578769874053985944565054668⟩

def cert_0 : ℕ :=
  147

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem ok_0 : kbcheck CFtabL MG cubeD FUEL cert_0 box_0 = some 1 := by decide +kernel

def box_1 : Bx := ⟨-9014486065188519281939254617133480860949, -8521729097782778922908881925700221291423, -4276577516132975852774157387694340766289, -3751360530940982196128572032606513950176, 1318345135522578769874053985944565054668, 1683453043120081310837733146781486508045⟩

def cert_1 : ℕ :=
  35

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem ok_1 : kbcheck CFtabL MG cubeD FUEL cert_1 box_1 = some 1 := by decide +kernel

set_option maxRecDepth 100000 in
/-- The covering of this piece's box. -/
theorem cover {c : RT} (hC : Mem3 CFtabL (ofRT c)) {ρ : Fin 5 → ℝ} (hD : CubeSound cubeD ρ) :
    Covers c MG ρ (⟨-9014486065188519281939254617133480860949, -8521729097782778922908881925700221291423, -4276577516132975852774157387694340766289, -3751360530940982196128572032606513950176, 953237227925076228910374825107643601292, 1683453043120081310837733146781486508045⟩) :=
  covers_split 2 (1318345135522578769874053985944565054668)
    (covers_of_kbcheck hC hD FUEL cert_0 box_0 1 ok_0)
    (covers_of_kbcheck hC hD FUEL cert_1 box_1 1 ok_1)

end Thomson.TriangleGlobal.Covering.Part517
