-- GENERATED by scripts/threepoint/tri5b_kparts.py; do not edit
import Thomson.TriangleGlobal.KernelLeaf
import Thomson.TriangleGlobal.KernelTable
import Thomson.TriangleGlobal.Params

/-! # Task 5b: piece 524 of the covering, kernel-checked — GENERATED

`7` leaves of the tree in `2` groups, over the box below.  Each group is one `decide +kernel`. -/

namespace Thomson.TriangleGlobal.Covering.Part524

open Thomson.Tri5b

def box_0 : Bx := ⟨-3751360530940982196128572032606513950176, -3718232642215962652375334760784530029064, 3117448724128163984436613313837871208033, 3164298633655873363188051925377675108937, 3198821185473750341888238614043648935359, 3233343737291627320588425302709622761782⟩

def cert_0 : ℕ :=
  35

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem ok_0 : kbcheck CFtabL MG cubeD FUEL cert_0 box_0 = some 1 := by decide +kernel

def box_1 : Bx := ⟨-3718232642215962652375334760784530029064, -3685104753490943108622097488962546107951, 3117448724128163984436613313837871208033, 3164298633655873363188051925377675108937, 3198821185473750341888238614043648935359, 3233343737291627320588425302709622761782⟩

def cert_1 : ℕ :=
  135

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem ok_1 : kbcheck CFtabL MG cubeD FUEL cert_1 box_1 = some 1 := by decide +kernel

set_option maxRecDepth 100000 in
/-- The covering of this piece's box. -/
theorem cover {c : RT} (hC : Mem3 CFtabL (ofRT c)) {ρ : Fin 5 → ℝ} (hD : CubeSound cubeD ρ) :
    Covers c MG ρ (⟨-3751360530940982196128572032606513950176, -3685104753490943108622097488962546107951, 3117448724128163984436613313837871208033, 3164298633655873363188051925377675108937, 3198821185473750341888238614043648935359, 3233343737291627320588425302709622761782⟩) :=
  covers_split 0 (-3718232642215962652375334760784530029064)
    (covers_of_kbcheck hC hD FUEL cert_0 box_0 1 ok_0)
    (covers_of_kbcheck hC hD FUEL cert_1 box_1 1 ok_1)

end Thomson.TriangleGlobal.Covering.Part524
