-- GENERATED by scripts/threepoint/tri5b_kparts.py; do not edit
import Thomson.TriangleGlobal.KernelLeaf
import Thomson.TriangleGlobal.KernelTable
import Thomson.TriangleGlobal.Params

/-! # Task 5b: piece 531 of the covering, kernel-checked — GENERATED

`6` leaves of the tree in `2` groups, over the box below.  Each group is one `decide +kernel`. -/

namespace Thomson.TriangleGlobal.Covering.Part531

open Thomson.Tri5b

def box_0 : Bx := ⟨-7953096412476931449293254873309128479077, -7427879427284937792647669518221301662965, 341313593967325205972775487845478354046, 1012383318543703258405254317313482431045, 3117448724128163984436613313837871208033, 3164298633655873363188051925377675108937⟩

def cert_0 : ℕ :=
  37

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem ok_0 : kbcheck CFtabL MG cubeD FUEL cert_0 box_0 = some 1 := by decide +kernel

def box_1 : Bx := ⟨-7427879427284937792647669518221301662965, -6902662442092944136002084163133474846852, 341313593967325205972775487845478354046, 1012383318543703258405254317313482431045, 3117448724128163984436613313837871208033, 3164298633655873363188051925377675108937⟩

def cert_1 : ℕ :=
  37

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem ok_1 : kbcheck CFtabL MG cubeD FUEL cert_1 box_1 = some 1 := by decide +kernel

set_option maxRecDepth 100000 in
/-- The covering of this piece's box. -/
theorem cover {c : RT} (hC : Mem3 CFtabL (ofRT c)) {ρ : Fin 5 → ℝ} (hD : CubeSound cubeD ρ) :
    Covers c MG ρ (⟨-7953096412476931449293254873309128479077, -6902662442092944136002084163133474846852, 341313593967325205972775487845478354046, 1012383318543703258405254317313482431045, 3117448724128163984436613313837871208033, 3164298633655873363188051925377675108937⟩) :=
  covers_split 0 (-7427879427284937792647669518221301662965)
    (covers_of_kbcheck hC hD FUEL cert_0 box_0 1 ok_0)
    (covers_of_kbcheck hC hD FUEL cert_1 box_1 1 ok_1)

end Thomson.TriangleGlobal.Covering.Part531
