-- GENERATED by scripts/threepoint/tri5b_kparts.py; do not edit
import Thomson.TriangleGlobal.KernelLeaf
import Thomson.TriangleGlobal.KernelTable
import Thomson.TriangleGlobal.Params

/-! # Task 5b: piece 545 of the covering, kernel-checked — GENERATED

`5` leaves of the tree in `2` groups, over the box below.  Each group is one `decide +kernel`. -/

namespace Thomson.TriangleGlobal.Covering.Part545

open Thomson.Tri5b

def box_0 : Bx := ⟨-5852228471708956822710913452957821214627, -3751360530940982196128572032606513950176, -3685104753490943108622097488962546107951, -1000825855185430898892182171090529799953, -1237410217659939016871700139913885118967, 223021412730071146983016503433800694539⟩

def cert_0 : ℕ :=
  9

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem ok_0 : kbcheck CFtabL MG cubeD FUEL cert_0 box_0 = some 1 := by decide +kernel

def box_1 : Bx := ⟨-5852228471708956822710913452957821214627, -3751360530940982196128572032606513950176, -3685104753490943108622097488962546107951, -1000825855185430898892182171090529799953, 223021412730071146983016503433800694539, 1683453043120081310837733146781486508045⟩

def cert_1 : ℕ :=
  35

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem ok_1 : kbcheck CFtabL MG cubeD FUEL cert_1 box_1 = some 1 := by decide +kernel

set_option maxRecDepth 100000 in
/-- The covering of this piece's box. -/
theorem cover {c : RT} (hC : Mem3 CFtabL (ofRT c)) {ρ : Fin 5 → ℝ} (hD : CubeSound cubeD ρ) :
    Covers c MG ρ (⟨-5852228471708956822710913452957821214627, -3751360530940982196128572032606513950176, -3685104753490943108622097488962546107951, -1000825855185430898892182171090529799953, -1237410217659939016871700139913885118967, 1683453043120081310837733146781486508045⟩) :=
  covers_split 2 (223021412730071146983016503433800694539)
    (covers_of_kbcheck hC hD FUEL cert_0 box_0 1 ok_0)
    (covers_of_kbcheck hC hD FUEL cert_1 box_1 1 ok_1)

end Thomson.TriangleGlobal.Covering.Part545
