-- GENERATED by scripts/threepoint/tri5b_kparts.py; do not edit
import Thomson.TriangleGlobal.KernelLeaf
import Thomson.TriangleGlobal.KernelTable
import Thomson.TriangleGlobal.Params

/-! # Task 5b: piece 544 of the covering, kernel-checked — GENERATED

`5` leaves of the tree in `2` groups, over the box below.  Each group is one `decide +kernel`. -/

namespace Thomson.TriangleGlobal.Covering.Part544

open Thomson.Tri5b

def box_0 : Bx := ⟨-8028972130377038563878509234266961721897, -7953096412476931449293254873309128479077, 1683453043120081310837733146781486508045, 5373741950000000000000000000000000000000, -4158273478439959344581133426609256745978, -1237410217659939016871700139913885118967⟩

def cert_0 : ℕ :=
  2

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem ok_0 : kbcheck CFtabL MG cubeD FUEL cert_0 box_0 = some 1 := by decide +kernel

def box_1 : Bx := ⟨-8028972130377038563878509234266961721897, -7953096412476931449293254873309128479077, 1683453043120081310837733146781486508045, 5373741950000000000000000000000000000000, -1237410217659939016871700139913885118967, 1683453043120081310837733146781486508045⟩

def cert_1 : ℕ :=
  139

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem ok_1 : kbcheck CFtabL MG cubeD FUEL cert_1 box_1 = some 1 := by decide +kernel

set_option maxRecDepth 100000 in
/-- The covering of this piece's box. -/
theorem cover {c : RT} (hC : Mem3 CFtabL (ofRT c)) {ρ : Fin 5 → ℝ} (hD : CubeSound cubeD ρ) :
    Covers c MG ρ (⟨-8028972130377038563878509234266961721897, -7953096412476931449293254873309128479077, 1683453043120081310837733146781486508045, 5373741950000000000000000000000000000000, -4158273478439959344581133426609256745978, 1683453043120081310837733146781486508045⟩) :=
  covers_split 2 (-1237410217659939016871700139913885118967)
    (covers_of_kbcheck hC hD FUEL cert_0 box_0 1 ok_0)
    (covers_of_kbcheck hC hD FUEL cert_1 box_1 1 ok_1)

end Thomson.TriangleGlobal.Covering.Part544
