-- GENERATED by scripts/threepoint/trilocal_gen.py; do not edit
import Thomson.TriangleLocal.Types.Type2

/-! # Task 5a: type `2`, face `e_0 = +ρ` — GENERATED (148 patches) -/

namespace Thomson.TriLocalCert

set_option maxHeartbeats 4000000 in
def tree2_0p : QT := (.node (.node (.node .leaf .leaf .leaf .leaf) (.node .leaf .leaf .leaf .leaf) .leaf .leaf) (.node (.node .leaf (.node .leaf .leaf .leaf .leaf) .leaf (.node .leaf .leaf .leaf .leaf)) (.node .leaf .leaf (.node .leaf .leaf .leaf .leaf) .leaf) (.node .leaf (.node .leaf .leaf .leaf .leaf) .leaf (.node .leaf .leaf .leaf .leaf)) (.node (.node .leaf .leaf .leaf .leaf) (.node .leaf .leaf .leaf .leaf) (.node .leaf .leaf .leaf .leaf) (.node .leaf .leaf .leaf .leaf))) (.node .leaf .leaf .leaf .leaf) (.node (.node .leaf (.node .leaf .leaf .leaf .leaf) .leaf (.node .leaf .leaf .leaf .leaf)) (.node (.node .leaf .leaf .leaf .leaf) (.node .leaf .leaf .leaf .leaf) (.node .leaf .leaf .leaf .leaf) (.node .leaf .leaf (.node .leaf .leaf .leaf .leaf) .leaf)) (.node .leaf (.node .leaf .leaf .leaf .leaf) .leaf (.node .leaf .leaf .leaf .leaf)) (.node (.node .leaf (.node .leaf .leaf .leaf .leaf) .leaf (.node .leaf .leaf .leaf .leaf)) (.node (.node .leaf .leaf .leaf .leaf) (.node .leaf .leaf .leaf .leaf) (.node .leaf .leaf .leaf .leaf) (.node .leaf .leaf .leaf .leaf)) (.node .leaf (.node .leaf .leaf .leaf .leaf) .leaf (.node .leaf .leaf .leaf .leaf)) (.node (.node .leaf .leaf .leaf .leaf) (.node .leaf .leaf .leaf .leaf) (.node .leaf .leaf .leaf .leaf) (.node .leaf .leaf .leaf .leaf)))))

set_option maxHeartbeats 0 in
set_option maxRecDepth 1000000 in
theorem face2_0p : faceOK D2 0 true tree2_0p = true := by decide +kernel

end Thomson.TriLocalCert
