-- GENERATED by threepoint/trilocal_gen.py; do not edit
import Thomson.TriLocalCert.Type1

/-! # Task 5a: type `1`, face `e_0 = −ρ` — GENERATED (1 patches) -/

namespace Thomson.TriLocalCert

set_option maxHeartbeats 4000000 in
def tree1_0n : QT := .leaf

set_option maxRecDepth 1000000 in
theorem face1_0n : faceOK D1 0 false tree1_0n = true := by decide +kernel

end Thomson.TriLocalCert
