-- GENERATED by threepoint/trilocal_gen.py; do not edit
import Thomson.TriLocalCert.Type2

/-! # Task 5a: type `2`, face `e_0 = −ρ` — GENERATED (148 patches) -/

namespace Thomson.TriLocalCert

set_option maxHeartbeats 4000000 in
def bits2_0n : List Bool := [true, true, true, true, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, true, true, false, false, false, false, false, true, false, false, false, false, false, true, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, true, true, false, false, false, false, false, true, false, false, false, false, false, true, true, false, false, false, false, false, true, false, false, false, false, false, true, true, false, true, false, false, false, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, true, true, false, false, false, false, false, true, false, false, false, false, false, true, false, false, false, false, true, true, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, true, true, false, false, false, false, false, true, false, false, false, false, false, true, false, true, false, false, false, false, false, false, true, true, false, false, false, false, false, true, false, false, false, false, false, true, false, false, true, false, false, false, false, true, false, false, false, false]

set_option maxRecDepth 1000000 in
theorem face2_0n : faceOK D2 0 false 7 bits2_0n = true := by decide +kernel

end Thomson.TriLocalCert
