-- GENERATED by threepoint/trilocal_gen.py; do not edit
import Thomson.TriLocalCert.Type4

/-! # Task 5a: type `4`, face `e_2 = +ρ` — GENERATED (67 patches) -/

namespace Thomson.TriLocalCert

set_option maxHeartbeats 4000000 in
def bits4_2p : List Bool := [true, true, true, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, true, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, false, true, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, false, true, false, false, false, false, true, true, false, false, false, false, true, false, false, false, false, false, false, true, true, false, false, false, false, false, true, false, false, false, false, false, false]

set_option maxRecDepth 1000000 in
theorem face4_2p : faceOK D4 2 true 6 bits4_2p = true := by decide +kernel

end Thomson.TriLocalCert
