-- GENERATED by threepoint/trilocal_gen.py; do not edit
import Thomson.TriLocalCert.Type1

/-! # Task 5a: type `1`, face `e_0 = +ρ` — GENERATED (1 patches) -/

namespace Thomson.TriLocalCert

set_option maxHeartbeats 4000000 in
def bits1_0p : List Bool := [false]

set_option maxRecDepth 1000000 in
theorem face1_0p : faceOK D1 0 true 2 bits1_0p = true := by decide +kernel

end Thomson.TriLocalCert
