-- GENERATED by threepoint/trilocal_gen.py; do not edit
import Thomson.TriLocalCert.Type0

/-! # Task 5a: type `0`, face `e_1 = −ρ` — GENERATED (13 patches) -/

namespace Thomson.TriLocalCert

set_option maxHeartbeats 4000000 in
def tree0_1n : QT := (.node .leaf (.node .leaf .leaf .leaf .leaf) (.node .leaf .leaf .leaf .leaf) (.node .leaf .leaf .leaf .leaf))

set_option maxRecDepth 1000000 in
theorem face0_1n : faceOK D0 1 false tree0_1n = true := by decide +kernel

end Thomson.TriLocalCert
