-- GENERATED by threepoint/trilocal_gen.py; do not edit
import Thomson.TriLocalCert.Type2

/-! # Task 5a: type `2`, face `e_2 = −ρ` — GENERATED (100 patches) -/

namespace Thomson.TriLocalCert

set_option maxHeartbeats 4000000 in
def bits2_2n : List Bool := [true, true, true, true, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, true, true, false, false, false, false, false, true, false, false, false, false, false, true, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, true, true, false, false, false, false, false, false, false, true, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, false, true, true, true, false, false, false, false, false, false, false, true, false, false, false, false, true, false, false, false, false, false, true, false, false, false, false, true, true, false, false, false, false, true, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false, false]

set_option maxRecDepth 1000000 in
theorem face2_2n : faceOK D2 2 false 7 bits2_2n = true := by decide +kernel

end Thomson.TriLocalCert
