-- GENERATED by threepoint/trilocal_gen.py; do not edit
import Thomson.TriLocalCert.Type0

/-! # Task 5a: type `0`, face `e_0 = +ρ` — GENERATED (13 patches) -/

namespace Thomson.TriLocalCert

set_option maxHeartbeats 4000000 in
def bits0_0p : List Bool := [true, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, false]

set_option maxRecDepth 1000000 in
theorem face0_0p : faceOK D0 0 true 4 bits0_0p = true := by decide +kernel

end Thomson.TriLocalCert
