-- GENERATED by threepoint/trilocal_gen.py; do not edit
import Thomson.TriLocalCert.Type0

/-! # Task 5a: type `0`, face `e_0 = +ρ` — GENERATED (13 patches) -/

namespace Thomson.TriLocalCert

set_option maxHeartbeats 4000000 in
def tree0_0p : QT := (.node (.node .leaf .leaf .leaf .leaf) (.node .leaf .leaf .leaf .leaf) (.node .leaf .leaf .leaf .leaf) .leaf)

set_option maxRecDepth 1000000 in
theorem face0_0p : faceOK D0 0 true tree0_0p = true := by decide +kernel

end Thomson.TriLocalCert
