-- GENERATED by threepoint/trilocal_gen.py; do not edit
import Thomson.TriLocalCert.Face0_0p
import Thomson.TriLocalCert.Face0_0n
import Thomson.TriLocalCert.Face0_1p
import Thomson.TriLocalCert.Face0_1n
import Thomson.TriLocalCert.Face0_2p
import Thomson.TriLocalCert.Face0_2n
import Thomson.TriLocalCert.Face1_0p
import Thomson.TriLocalCert.Face1_0n
import Thomson.TriLocalCert.Face1_1p
import Thomson.TriLocalCert.Face1_1n
import Thomson.TriLocalCert.Face1_2p
import Thomson.TriLocalCert.Face1_2n
import Thomson.TriLocalCert.Face2_0p
import Thomson.TriLocalCert.Face2_0n
import Thomson.TriLocalCert.Face2_1p
import Thomson.TriLocalCert.Face2_1n
import Thomson.TriLocalCert.Face2_2p
import Thomson.TriLocalCert.Face2_2n
import Thomson.TriLocalCert.Face3_0p
import Thomson.TriLocalCert.Face3_0n
import Thomson.TriLocalCert.Face3_1p
import Thomson.TriLocalCert.Face3_1n
import Thomson.TriLocalCert.Face3_2p
import Thomson.TriLocalCert.Face3_2n
import Thomson.TriLocalCert.Face4_0p
import Thomson.TriLocalCert.Face4_0n
import Thomson.TriLocalCert.Face4_1p
import Thomson.TriLocalCert.Face4_1n
import Thomson.TriLocalCert.Face4_2p
import Thomson.TriLocalCert.Face4_2n
import Thomson.TriLocalCert.Final
import Thomson.ThreePoint.Cert.TriLocalFinal
import Thomson.ThreePoint.Cert.TriLocalPolarBridge

/-! # Task 5a, assembled — GENERATED

The five checked touching types (`type_certificate`), through Task 5a's calculus
(`Thomson.ThreePoint.Cert.triP_local_of_bracket_all`): for any pivots within `10⁻¹²` of
`pivotsNum` at which `triP` has its second-order zeros (`triP_tight`), `triP ≥ 0` on the five cubes
of radius `1/500`.  `decide +kernel` only. -/

namespace Thomson.TriLocalCert

open Thomson Thomson.Tri5b Set

def trees0 : Fin 3 → Bool → QT
  | 0, true => tree0_0p
  | 0, false => tree0_0n
  | 1, true => tree0_1p
  | 1, false => tree0_1n
  | 2, true => tree0_2p
  | 2, false => tree0_2n

theorem typeCert0 {p : Fin 24 → ℝ} (hclose : ∀ j, |p j - pivotsNum j| ≤ 1 / 10 ^ 12) :=
  type_certificate hclose 0 CS0_eq D0_eq (by decide) trees0
    (fun f σ => by fin_cases f <;> cases σ <;> first | exact face0_0p | exact face0_0n | exact face0_1p | exact face0_1n | exact face0_2p | exact face0_2n)

def trees1 : Fin 3 → Bool → QT
  | 0, true => tree1_0p
  | 0, false => tree1_0n
  | 1, true => tree1_1p
  | 1, false => tree1_1n
  | 2, true => tree1_2p
  | 2, false => tree1_2n

theorem typeCert1 {p : Fin 24 → ℝ} (hclose : ∀ j, |p j - pivotsNum j| ≤ 1 / 10 ^ 12) :=
  type_certificate hclose 1 CS1_eq D1_eq (by decide) trees1
    (fun f σ => by fin_cases f <;> cases σ <;> first | exact face1_0p | exact face1_0n | exact face1_1p | exact face1_1n | exact face1_2p | exact face1_2n)

def trees2 : Fin 3 → Bool → QT
  | 0, true => tree2_0p
  | 0, false => tree2_0n
  | 1, true => tree2_1p
  | 1, false => tree2_1n
  | 2, true => tree2_2p
  | 2, false => tree2_2n

theorem typeCert2 {p : Fin 24 → ℝ} (hclose : ∀ j, |p j - pivotsNum j| ≤ 1 / 10 ^ 12) :=
  type_certificate hclose 2 CS2_eq D2_eq (by decide) trees2
    (fun f σ => by fin_cases f <;> cases σ <;> first | exact face2_0p | exact face2_0n | exact face2_1p | exact face2_1n | exact face2_2p | exact face2_2n)

def trees3 : Fin 3 → Bool → QT
  | 0, true => tree3_0p
  | 0, false => tree3_0n
  | 1, true => tree3_1p
  | 1, false => tree3_1n
  | 2, true => tree3_2p
  | 2, false => tree3_2n

theorem typeCert3 {p : Fin 24 → ℝ} (hclose : ∀ j, |p j - pivotsNum j| ≤ 1 / 10 ^ 12) :=
  type_certificate hclose 3 CS3_eq D3_eq (by decide) trees3
    (fun f σ => by fin_cases f <;> cases σ <;> first | exact face3_0p | exact face3_0n | exact face3_1p | exact face3_1n | exact face3_2p | exact face3_2n)

def trees4 : Fin 3 → Bool → QT
  | 0, true => tree4_0p
  | 0, false => tree4_0n
  | 1, true => tree4_1p
  | 1, false => tree4_1n
  | 2, true => tree4_2p
  | 2, false => tree4_2n

theorem typeCert4 {p : Fin 24 → ℝ} (hclose : ∀ j, |p j - pivotsNum j| ≤ 1 / 10 ^ 12) :=
  type_certificate hclose 4 CS4_eq D4_eq (by decide) trees4
    (fun f σ => by fin_cases f <;> cases σ <;> first | exact face4_0p | exact face4_0n | exact face4_1p | exact face4_1n | exact face4_2p | exact face4_2n)


/-- The `M` of each type. -/
noncomputable def Mt : Fin 5 → ℝ
  | 0 => Mreal CS0 (Tt 0).1 (Tt 0).2.1 (Tt 0).2.2 sa0 sb0 sc0
  | 1 => Mreal CS1 (Tt 1).1 (Tt 1).2.1 (Tt 1).2.2 sa1 sb1 sc1
  | 2 => Mreal CS2 (Tt 2).1 (Tt 2).2.1 (Tt 2).2.2 sa2 sb2 sc2
  | 3 => Mreal CS3 (Tt 3).1 (Tt 3).2.1 (Tt 3).2.2 sa3 sb3 sc3
  | 4 => Mreal CS4 (Tt 4).1 (Tt 4).2.1 (Tt 4).2.2 sa4 sb4 sc4

/-- **Task 5a.** -/
theorem triP_local_cert {p : Fin 24 → ℝ} (hclose : ∀ j, |p j - pivotsNum j| ≤ 1 / 10 ^ 12)
    (hval : ∀ m : Fin 5, triP p (touchType m).1 (touchType m).2.1 (touchType m).2.2 = 0)
    (hder : ∀ m : Fin 5, ∀ c : Fin 3, deriv (triD p m c) 0 = 0) :
    ∀ m : Fin 5, ∀ a b c : ℝ, |a - (touchType m).1| ≤ 1 / 500 →
      |b - (touchType m).2.1| ≤ 1 / 500 → |c - (touchType m).2.2| ≤ 1 / 500 →
      0 ≤ triP p a b c := by
  have cert : ∀ m : Fin 5,
      (∀ δ : Fin 3 → ℝ, (∀ i, |δ i| ≤ 1 / 500) →
        0 ≤ bracket (Hpol (Q2 p (touchType m))) (Cpol (K3 p (touchType m))) (Mt m) δ) ∧
      (∀ δ : Fin 3 → ℝ, (∀ i, |δ i| ≤ 1 / 500) → ∀ x ∈ Icc (0 : ℝ) 1,
        |deriv (deriv (deriv (deriv (rayR p (touchType m) δ)))) x| ≤ Mt m * N2 δ ^ 2) := by
    intro m
    fin_cases m
    · exact typeCert0 hclose
    · exact typeCert1 hclose
    · exact typeCert2 hclose
    · exact typeCert3 hclose
    · exact typeCert4 hclose
  refine ThreePoint.Cert.triP_local_of_bracket_all p Mt hval hder (fun m δ hδ => ?_)
    (fun m δ hδ x hx => ?_)
  · have h := (cert m).1 δ hδ
    have e := ThreePoint.Cert.bracket_H_eq_pol p (touchType m) (Mt m) δ
    change 0 ≤ bracket (ThreePoint.Cert.H p (touchType m)) (ThreePoint.Cert.C p (touchType m))
      (Mt m) δ
    rw [e]
    exact h
  · exact (cert m).2 δ hδ x hx

end Thomson.TriLocalCert
