-- GENERATED by Thomson/Pivots/gen/mk_tables.py; do not edit
import Thomson.Pivots.KBase

/-! # Task 1b: the tensor of `Gh 0`, and column 0 — GENERATED

Three literal tables, each checked against its definition by `decide +kernel` in pieces small
enough for the kernel's cache (see `KBase`): the blocks `M_k = B_k H_k B_kᵀ` of the indicator block of pivot 0,
three rows at a time; the coefficient tensor built from those blocks, one `(p, q)` row of nine
at a time; and the 24 entries of column 0 of the pivot system, one at a time. -/

namespace Thomson.Task1b

open Thomson Thomson.Tri5b

/-- The blocks `M_k`. -/
def MItab00 : ITab :=
  [[[⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨10000000000000000000000000000000000000000, 10000000000000000000000000000000000000000⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨10000000000000000000000000000000000000000, 10000000000000000000000000000000000000000⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]]]

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab00_eq_0_0 : ∀ j : Fin (9 - ((0 : Fin 6) : ℕ)),
    mif MItab00 0 ⟨0, by omega⟩ j = MI BI (eHI 0) 0 ⟨0, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab00_eq_0_1 : ∀ j : Fin (9 - ((0 : Fin 6) : ℕ)),
    mif MItab00 0 ⟨1, by omega⟩ j = MI BI (eHI 0) 0 ⟨1, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab00_eq_0_2 : ∀ j : Fin (9 - ((0 : Fin 6) : ℕ)),
    mif MItab00 0 ⟨2, by omega⟩ j = MI BI (eHI 0) 0 ⟨2, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab00_eq_0_3 : ∀ j : Fin (9 - ((0 : Fin 6) : ℕ)),
    mif MItab00 0 ⟨3, by omega⟩ j = MI BI (eHI 0) 0 ⟨3, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab00_eq_0_4 : ∀ j : Fin (9 - ((0 : Fin 6) : ℕ)),
    mif MItab00 0 ⟨4, by omega⟩ j = MI BI (eHI 0) 0 ⟨4, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab00_eq_0_5 : ∀ j : Fin (9 - ((0 : Fin 6) : ℕ)),
    mif MItab00 0 ⟨5, by omega⟩ j = MI BI (eHI 0) 0 ⟨5, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab00_eq_0_6 : ∀ j : Fin (9 - ((0 : Fin 6) : ℕ)),
    mif MItab00 0 ⟨6, by omega⟩ j = MI BI (eHI 0) 0 ⟨6, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab00_eq_0_7 : ∀ j : Fin (9 - ((0 : Fin 6) : ℕ)),
    mif MItab00 0 ⟨7, by omega⟩ j = MI BI (eHI 0) 0 ⟨7, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab00_eq_0_8 : ∀ j : Fin (9 - ((0 : Fin 6) : ℕ)),
    mif MItab00 0 ⟨8, by omega⟩ j = MI BI (eHI 0) 0 ⟨8, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab00_eq_1_0 : ∀ j : Fin (9 - ((1 : Fin 6) : ℕ)),
    mif MItab00 1 ⟨0, by omega⟩ j = MI BI (eHI 0) 1 ⟨0, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab00_eq_1_1 : ∀ j : Fin (9 - ((1 : Fin 6) : ℕ)),
    mif MItab00 1 ⟨1, by omega⟩ j = MI BI (eHI 0) 1 ⟨1, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab00_eq_1_2 : ∀ j : Fin (9 - ((1 : Fin 6) : ℕ)),
    mif MItab00 1 ⟨2, by omega⟩ j = MI BI (eHI 0) 1 ⟨2, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab00_eq_1_3 : ∀ j : Fin (9 - ((1 : Fin 6) : ℕ)),
    mif MItab00 1 ⟨3, by omega⟩ j = MI BI (eHI 0) 1 ⟨3, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab00_eq_1_4 : ∀ j : Fin (9 - ((1 : Fin 6) : ℕ)),
    mif MItab00 1 ⟨4, by omega⟩ j = MI BI (eHI 0) 1 ⟨4, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab00_eq_1_5 : ∀ j : Fin (9 - ((1 : Fin 6) : ℕ)),
    mif MItab00 1 ⟨5, by omega⟩ j = MI BI (eHI 0) 1 ⟨5, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab00_eq_1_6 : ∀ j : Fin (9 - ((1 : Fin 6) : ℕ)),
    mif MItab00 1 ⟨6, by omega⟩ j = MI BI (eHI 0) 1 ⟨6, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab00_eq_1_7 : ∀ j : Fin (9 - ((1 : Fin 6) : ℕ)),
    mif MItab00 1 ⟨7, by omega⟩ j = MI BI (eHI 0) 1 ⟨7, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab00_eq_2_0 : ∀ j : Fin (9 - ((2 : Fin 6) : ℕ)),
    mif MItab00 2 ⟨0, by omega⟩ j = MI BI (eHI 0) 2 ⟨0, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab00_eq_2_1 : ∀ j : Fin (9 - ((2 : Fin 6) : ℕ)),
    mif MItab00 2 ⟨1, by omega⟩ j = MI BI (eHI 0) 2 ⟨1, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab00_eq_2_2 : ∀ j : Fin (9 - ((2 : Fin 6) : ℕ)),
    mif MItab00 2 ⟨2, by omega⟩ j = MI BI (eHI 0) 2 ⟨2, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab00_eq_2_3 : ∀ j : Fin (9 - ((2 : Fin 6) : ℕ)),
    mif MItab00 2 ⟨3, by omega⟩ j = MI BI (eHI 0) 2 ⟨3, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab00_eq_2_4 : ∀ j : Fin (9 - ((2 : Fin 6) : ℕ)),
    mif MItab00 2 ⟨4, by omega⟩ j = MI BI (eHI 0) 2 ⟨4, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab00_eq_2_5 : ∀ j : Fin (9 - ((2 : Fin 6) : ℕ)),
    mif MItab00 2 ⟨5, by omega⟩ j = MI BI (eHI 0) 2 ⟨5, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab00_eq_2_6 : ∀ j : Fin (9 - ((2 : Fin 6) : ℕ)),
    mif MItab00 2 ⟨6, by omega⟩ j = MI BI (eHI 0) 2 ⟨6, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab00_eq_3_0 : ∀ j : Fin (9 - ((3 : Fin 6) : ℕ)),
    mif MItab00 3 ⟨0, by omega⟩ j = MI BI (eHI 0) 3 ⟨0, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab00_eq_3_1 : ∀ j : Fin (9 - ((3 : Fin 6) : ℕ)),
    mif MItab00 3 ⟨1, by omega⟩ j = MI BI (eHI 0) 3 ⟨1, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab00_eq_3_2 : ∀ j : Fin (9 - ((3 : Fin 6) : ℕ)),
    mif MItab00 3 ⟨2, by omega⟩ j = MI BI (eHI 0) 3 ⟨2, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab00_eq_3_3 : ∀ j : Fin (9 - ((3 : Fin 6) : ℕ)),
    mif MItab00 3 ⟨3, by omega⟩ j = MI BI (eHI 0) 3 ⟨3, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab00_eq_3_4 : ∀ j : Fin (9 - ((3 : Fin 6) : ℕ)),
    mif MItab00 3 ⟨4, by omega⟩ j = MI BI (eHI 0) 3 ⟨4, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab00_eq_3_5 : ∀ j : Fin (9 - ((3 : Fin 6) : ℕ)),
    mif MItab00 3 ⟨5, by omega⟩ j = MI BI (eHI 0) 3 ⟨5, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab00_eq_4_0 : ∀ j : Fin (9 - ((4 : Fin 6) : ℕ)),
    mif MItab00 4 ⟨0, by omega⟩ j = MI BI (eHI 0) 4 ⟨0, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab00_eq_4_1 : ∀ j : Fin (9 - ((4 : Fin 6) : ℕ)),
    mif MItab00 4 ⟨1, by omega⟩ j = MI BI (eHI 0) 4 ⟨1, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab00_eq_4_2 : ∀ j : Fin (9 - ((4 : Fin 6) : ℕ)),
    mif MItab00 4 ⟨2, by omega⟩ j = MI BI (eHI 0) 4 ⟨2, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab00_eq_4_3 : ∀ j : Fin (9 - ((4 : Fin 6) : ℕ)),
    mif MItab00 4 ⟨3, by omega⟩ j = MI BI (eHI 0) 4 ⟨3, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab00_eq_4_4 : ∀ j : Fin (9 - ((4 : Fin 6) : ℕ)),
    mif MItab00 4 ⟨4, by omega⟩ j = MI BI (eHI 0) 4 ⟨4, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab00_eq_5_0 : ∀ j : Fin (9 - ((5 : Fin 6) : ℕ)),
    mif MItab00 5 ⟨0, by omega⟩ j = MI BI (eHI 0) 5 ⟨0, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab00_eq_5_1 : ∀ j : Fin (9 - ((5 : Fin 6) : ℕ)),
    mif MItab00 5 ⟨1, by omega⟩ j = MI BI (eHI 0) 5 ⟨1, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab00_eq_5_2 : ∀ j : Fin (9 - ((5 : Fin 6) : ℕ)),
    mif MItab00 5 ⟨2, by omega⟩ j = MI BI (eHI 0) 5 ⟨2, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab00_eq_5_3 : ∀ j : Fin (9 - ((5 : Fin 6) : ℕ)),
    mif MItab00 5 ⟨3, by omega⟩ j = MI BI (eHI 0) 5 ⟨3, by omega⟩ j := by
  decide +kernel

theorem MItab00_eq : ∀ (k : Fin 6) (i j : Fin (9 - (k : ℕ))),
    mif MItab00 k i j = MI BI (eHI 0) k i j := by
  intro k i
  fin_cases k <;> fin_cases i
  exacts [MItab00_eq_0_0,
    MItab00_eq_0_1,
    MItab00_eq_0_2,
    MItab00_eq_0_3,
    MItab00_eq_0_4,
    MItab00_eq_0_5,
    MItab00_eq_0_6,
    MItab00_eq_0_7,
    MItab00_eq_0_8,
    MItab00_eq_1_0,
    MItab00_eq_1_1,
    MItab00_eq_1_2,
    MItab00_eq_1_3,
    MItab00_eq_1_4,
    MItab00_eq_1_5,
    MItab00_eq_1_6,
    MItab00_eq_1_7,
    MItab00_eq_2_0,
    MItab00_eq_2_1,
    MItab00_eq_2_2,
    MItab00_eq_2_3,
    MItab00_eq_2_4,
    MItab00_eq_2_5,
    MItab00_eq_2_6,
    MItab00_eq_3_0,
    MItab00_eq_3_1,
    MItab00_eq_3_2,
    MItab00_eq_3_3,
    MItab00_eq_3_4,
    MItab00_eq_3_5,
    MItab00_eq_4_0,
    MItab00_eq_4_1,
    MItab00_eq_4_2,
    MItab00_eq_4_3,
    MItab00_eq_4_4,
    MItab00_eq_5_0,
    MItab00_eq_5_1,
    MItab00_eq_5_2,
    MItab00_eq_5_3]

/-- The coefficient tensor. -/
def Gtab00 : ITab :=
  [[[⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨3333333333333333333333333333333333333333, 3333333333333333333333333333333333333334⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨3333333333333333333333333333333333333333, 3333333333333333333333333333333333333334⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨3333333333333333333333333333333333333333, 3333333333333333333333333333333333333334⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨3333333333333333333333333333333333333333, 3333333333333333333333333333333333333334⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨0, 0⟩, ⟨3333333333333333333333333333333333333333, 3333333333333333333333333333333333333334⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨3333333333333333333333333333333333333333, 3333333333333333333333333333333333333334⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]]]

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_0_0 : ∀ r : Fin 9, getT Gtab00 0 0 r = CF (mif MItab00) 0 0 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_0_1 : ∀ r : Fin 9, getT Gtab00 0 1 r = CF (mif MItab00) 0 1 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_0_2 : ∀ r : Fin 9, getT Gtab00 0 2 r = CF (mif MItab00) 0 2 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_0_3 : ∀ r : Fin 9, getT Gtab00 0 3 r = CF (mif MItab00) 0 3 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_0_4 : ∀ r : Fin 9, getT Gtab00 0 4 r = CF (mif MItab00) 0 4 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_0_5 : ∀ r : Fin 9, getT Gtab00 0 5 r = CF (mif MItab00) 0 5 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_0_6 : ∀ r : Fin 9, getT Gtab00 0 6 r = CF (mif MItab00) 0 6 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_0_7 : ∀ r : Fin 9, getT Gtab00 0 7 r = CF (mif MItab00) 0 7 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_0_8 : ∀ r : Fin 9, getT Gtab00 0 8 r = CF (mif MItab00) 0 8 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_1_0 : ∀ r : Fin 9, getT Gtab00 1 0 r = CF (mif MItab00) 1 0 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_1_1 : ∀ r : Fin 9, getT Gtab00 1 1 r = CF (mif MItab00) 1 1 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_1_2 : ∀ r : Fin 9, getT Gtab00 1 2 r = CF (mif MItab00) 1 2 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_1_3 : ∀ r : Fin 9, getT Gtab00 1 3 r = CF (mif MItab00) 1 3 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_1_4 : ∀ r : Fin 9, getT Gtab00 1 4 r = CF (mif MItab00) 1 4 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_1_5 : ∀ r : Fin 9, getT Gtab00 1 5 r = CF (mif MItab00) 1 5 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_1_6 : ∀ r : Fin 9, getT Gtab00 1 6 r = CF (mif MItab00) 1 6 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_1_7 : ∀ r : Fin 9, getT Gtab00 1 7 r = CF (mif MItab00) 1 7 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_1_8 : ∀ r : Fin 9, getT Gtab00 1 8 r = CF (mif MItab00) 1 8 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_2_0 : ∀ r : Fin 9, getT Gtab00 2 0 r = CF (mif MItab00) 2 0 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_2_1 : ∀ r : Fin 9, getT Gtab00 2 1 r = CF (mif MItab00) 2 1 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_2_2 : ∀ r : Fin 9, getT Gtab00 2 2 r = CF (mif MItab00) 2 2 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_2_3 : ∀ r : Fin 9, getT Gtab00 2 3 r = CF (mif MItab00) 2 3 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_2_4 : ∀ r : Fin 9, getT Gtab00 2 4 r = CF (mif MItab00) 2 4 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_2_5 : ∀ r : Fin 9, getT Gtab00 2 5 r = CF (mif MItab00) 2 5 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_2_6 : ∀ r : Fin 9, getT Gtab00 2 6 r = CF (mif MItab00) 2 6 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_2_7 : ∀ r : Fin 9, getT Gtab00 2 7 r = CF (mif MItab00) 2 7 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_2_8 : ∀ r : Fin 9, getT Gtab00 2 8 r = CF (mif MItab00) 2 8 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_3_0 : ∀ r : Fin 9, getT Gtab00 3 0 r = CF (mif MItab00) 3 0 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_3_1 : ∀ r : Fin 9, getT Gtab00 3 1 r = CF (mif MItab00) 3 1 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_3_2 : ∀ r : Fin 9, getT Gtab00 3 2 r = CF (mif MItab00) 3 2 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_3_3 : ∀ r : Fin 9, getT Gtab00 3 3 r = CF (mif MItab00) 3 3 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_3_4 : ∀ r : Fin 9, getT Gtab00 3 4 r = CF (mif MItab00) 3 4 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_3_5 : ∀ r : Fin 9, getT Gtab00 3 5 r = CF (mif MItab00) 3 5 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_3_6 : ∀ r : Fin 9, getT Gtab00 3 6 r = CF (mif MItab00) 3 6 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_3_7 : ∀ r : Fin 9, getT Gtab00 3 7 r = CF (mif MItab00) 3 7 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_3_8 : ∀ r : Fin 9, getT Gtab00 3 8 r = CF (mif MItab00) 3 8 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_4_0 : ∀ r : Fin 9, getT Gtab00 4 0 r = CF (mif MItab00) 4 0 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_4_1 : ∀ r : Fin 9, getT Gtab00 4 1 r = CF (mif MItab00) 4 1 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_4_2 : ∀ r : Fin 9, getT Gtab00 4 2 r = CF (mif MItab00) 4 2 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_4_3 : ∀ r : Fin 9, getT Gtab00 4 3 r = CF (mif MItab00) 4 3 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_4_4 : ∀ r : Fin 9, getT Gtab00 4 4 r = CF (mif MItab00) 4 4 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_4_5 : ∀ r : Fin 9, getT Gtab00 4 5 r = CF (mif MItab00) 4 5 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_4_6 : ∀ r : Fin 9, getT Gtab00 4 6 r = CF (mif MItab00) 4 6 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_4_7 : ∀ r : Fin 9, getT Gtab00 4 7 r = CF (mif MItab00) 4 7 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_4_8 : ∀ r : Fin 9, getT Gtab00 4 8 r = CF (mif MItab00) 4 8 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_5_0 : ∀ r : Fin 9, getT Gtab00 5 0 r = CF (mif MItab00) 5 0 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_5_1 : ∀ r : Fin 9, getT Gtab00 5 1 r = CF (mif MItab00) 5 1 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_5_2 : ∀ r : Fin 9, getT Gtab00 5 2 r = CF (mif MItab00) 5 2 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_5_3 : ∀ r : Fin 9, getT Gtab00 5 3 r = CF (mif MItab00) 5 3 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_5_4 : ∀ r : Fin 9, getT Gtab00 5 4 r = CF (mif MItab00) 5 4 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_5_5 : ∀ r : Fin 9, getT Gtab00 5 5 r = CF (mif MItab00) 5 5 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_5_6 : ∀ r : Fin 9, getT Gtab00 5 6 r = CF (mif MItab00) 5 6 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_5_7 : ∀ r : Fin 9, getT Gtab00 5 7 r = CF (mif MItab00) 5 7 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_5_8 : ∀ r : Fin 9, getT Gtab00 5 8 r = CF (mif MItab00) 5 8 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_6_0 : ∀ r : Fin 9, getT Gtab00 6 0 r = CF (mif MItab00) 6 0 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_6_1 : ∀ r : Fin 9, getT Gtab00 6 1 r = CF (mif MItab00) 6 1 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_6_2 : ∀ r : Fin 9, getT Gtab00 6 2 r = CF (mif MItab00) 6 2 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_6_3 : ∀ r : Fin 9, getT Gtab00 6 3 r = CF (mif MItab00) 6 3 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_6_4 : ∀ r : Fin 9, getT Gtab00 6 4 r = CF (mif MItab00) 6 4 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_6_5 : ∀ r : Fin 9, getT Gtab00 6 5 r = CF (mif MItab00) 6 5 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_6_6 : ∀ r : Fin 9, getT Gtab00 6 6 r = CF (mif MItab00) 6 6 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_6_7 : ∀ r : Fin 9, getT Gtab00 6 7 r = CF (mif MItab00) 6 7 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_6_8 : ∀ r : Fin 9, getT Gtab00 6 8 r = CF (mif MItab00) 6 8 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_7_0 : ∀ r : Fin 9, getT Gtab00 7 0 r = CF (mif MItab00) 7 0 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_7_1 : ∀ r : Fin 9, getT Gtab00 7 1 r = CF (mif MItab00) 7 1 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_7_2 : ∀ r : Fin 9, getT Gtab00 7 2 r = CF (mif MItab00) 7 2 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_7_3 : ∀ r : Fin 9, getT Gtab00 7 3 r = CF (mif MItab00) 7 3 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_7_4 : ∀ r : Fin 9, getT Gtab00 7 4 r = CF (mif MItab00) 7 4 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_7_5 : ∀ r : Fin 9, getT Gtab00 7 5 r = CF (mif MItab00) 7 5 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_7_6 : ∀ r : Fin 9, getT Gtab00 7 6 r = CF (mif MItab00) 7 6 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_7_7 : ∀ r : Fin 9, getT Gtab00 7 7 r = CF (mif MItab00) 7 7 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_7_8 : ∀ r : Fin 9, getT Gtab00 7 8 r = CF (mif MItab00) 7 8 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_8_0 : ∀ r : Fin 9, getT Gtab00 8 0 r = CF (mif MItab00) 8 0 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_8_1 : ∀ r : Fin 9, getT Gtab00 8 1 r = CF (mif MItab00) 8 1 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_8_2 : ∀ r : Fin 9, getT Gtab00 8 2 r = CF (mif MItab00) 8 2 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_8_3 : ∀ r : Fin 9, getT Gtab00 8 3 r = CF (mif MItab00) 8 3 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_8_4 : ∀ r : Fin 9, getT Gtab00 8 4 r = CF (mif MItab00) 8 4 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_8_5 : ∀ r : Fin 9, getT Gtab00 8 5 r = CF (mif MItab00) 8 5 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_8_6 : ∀ r : Fin 9, getT Gtab00 8 6 r = CF (mif MItab00) 8 6 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_8_7 : ∀ r : Fin 9, getT Gtab00 8 7 r = CF (mif MItab00) 8 7 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab00_eq_8_8 : ∀ r : Fin 9, getT Gtab00 8 8 r = CF (mif MItab00) 8 8 r := by
  decide +kernel

theorem Gtab00_eq : ∀ p q r : Fin 9, getT Gtab00 p q r = CF (mif MItab00) p q r := by
  intro p q
  fin_cases p <;> fin_cases q
  exacts [Gtab00_eq_0_0,
    Gtab00_eq_0_1,
    Gtab00_eq_0_2,
    Gtab00_eq_0_3,
    Gtab00_eq_0_4,
    Gtab00_eq_0_5,
    Gtab00_eq_0_6,
    Gtab00_eq_0_7,
    Gtab00_eq_0_8,
    Gtab00_eq_1_0,
    Gtab00_eq_1_1,
    Gtab00_eq_1_2,
    Gtab00_eq_1_3,
    Gtab00_eq_1_4,
    Gtab00_eq_1_5,
    Gtab00_eq_1_6,
    Gtab00_eq_1_7,
    Gtab00_eq_1_8,
    Gtab00_eq_2_0,
    Gtab00_eq_2_1,
    Gtab00_eq_2_2,
    Gtab00_eq_2_3,
    Gtab00_eq_2_4,
    Gtab00_eq_2_5,
    Gtab00_eq_2_6,
    Gtab00_eq_2_7,
    Gtab00_eq_2_8,
    Gtab00_eq_3_0,
    Gtab00_eq_3_1,
    Gtab00_eq_3_2,
    Gtab00_eq_3_3,
    Gtab00_eq_3_4,
    Gtab00_eq_3_5,
    Gtab00_eq_3_6,
    Gtab00_eq_3_7,
    Gtab00_eq_3_8,
    Gtab00_eq_4_0,
    Gtab00_eq_4_1,
    Gtab00_eq_4_2,
    Gtab00_eq_4_3,
    Gtab00_eq_4_4,
    Gtab00_eq_4_5,
    Gtab00_eq_4_6,
    Gtab00_eq_4_7,
    Gtab00_eq_4_8,
    Gtab00_eq_5_0,
    Gtab00_eq_5_1,
    Gtab00_eq_5_2,
    Gtab00_eq_5_3,
    Gtab00_eq_5_4,
    Gtab00_eq_5_5,
    Gtab00_eq_5_6,
    Gtab00_eq_5_7,
    Gtab00_eq_5_8,
    Gtab00_eq_6_0,
    Gtab00_eq_6_1,
    Gtab00_eq_6_2,
    Gtab00_eq_6_3,
    Gtab00_eq_6_4,
    Gtab00_eq_6_5,
    Gtab00_eq_6_6,
    Gtab00_eq_6_7,
    Gtab00_eq_6_8,
    Gtab00_eq_7_0,
    Gtab00_eq_7_1,
    Gtab00_eq_7_2,
    Gtab00_eq_7_3,
    Gtab00_eq_7_4,
    Gtab00_eq_7_5,
    Gtab00_eq_7_6,
    Gtab00_eq_7_7,
    Gtab00_eq_7_8,
    Gtab00_eq_8_0,
    Gtab00_eq_8_1,
    Gtab00_eq_8_2,
    Gtab00_eq_8_3,
    Gtab00_eq_8_4,
    Gtab00_eq_8_5,
    Gtab00_eq_8_6,
    Gtab00_eq_8_7,
    Gtab00_eq_8_8]

/-- The 24 entries. -/
def col00 : List Itv :=
  [⟨-80000000000000000000000000000000000000016, -79999999999999999999999999999999999999992⟩,
    ⟨31860801626740325951758731801987768801776, 31860801626740325951758731801995704183467⟩,
    ⟨13387396974436070528512769455479063252198, 13387396974436070528512769455482943119284⟩,
    ⟨74430904899478203446940575735466041235200, 74430904899478203446940575735485535336368⟩,
    ⟨-4552501766159252521251332504055879317451, -4552501766159252521251332504053865946831⟩,
    ⟨33196626774896575037687761428637968386568, 33196626774896575037687761428645185467217⟩,
    ⟨34205353447331257475054795861235490867404, 34205353447331257475054795861250480605675⟩,
    ⟨80970815205474066248088739688663940224976, 80970815205474066248088739688742137876406⟩,
    ⟨-6257794742470647808224609026339337139598, -6257794742470647808224609026332176554876⟩,
    ⟨-40829893168272397896761017421600495601902, -40829893168272397896761017421571835037318⟩,
    ⟨-29917202737740505579278086747659613173712, -29917202737740505579278086747643123208223⟩,
    ⟨-1739189918274356038635152718835820829679, -1739189918274356038635152718833156215174⟩,
    ⟨-11949780856250741102933963529506965909290, -11949780856250741102933963529492119450041⟩,
    ⟨-12887231356511176215507074124104723072987, -12887231356511176215507074124096727921384⟩,
    ⟨2568874439422443441403216720168899951171, 2568874439422443441403216720170590644665⟩,
    ⟨18812600714435079891833090071146911112270, 18812600714435079891833090071157183652602⟩,
    ⟨-4412709101699779228595886098946530881527, -4412709101699779228595886098941453926520⟩,
    ⟨-5527004282488457836591166350164899189072, -5527004282488457836591166350159433901733⟩,
    ⟨271681334679062673393485852452748081163, 271681334679062673393485852453137589770⟩,
    ⟨4210219945728894384367479766310914127936, 4210219945728894384367479766313617509999⟩,
    ⟨-100762333672048094479715870353828433253, -100762333672048094479715870352260680924⟩,
    ⟨-99928213675704420089772113819056309045, -99928213675704420089772113818945994552⟩,
    ⟨576678451238972097873398783079931251983, 576678451238972097873398783080623324492⟩,
    ⟨757517662590759229025876795230240785859, 757517662590759229025876795231058460656⟩]

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col00_eq00 : col00.getD 0 Itv.zero = entAt (getT Gtab00) 0 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col00_eq01 : col00.getD 1 Itv.zero = entAt (getT Gtab00) 1 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col00_eq02 : col00.getD 2 Itv.zero = entAt (getT Gtab00) 2 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col00_eq03 : col00.getD 3 Itv.zero = entAt (getT Gtab00) 3 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col00_eq04 : col00.getD 4 Itv.zero = entAt (getT Gtab00) 4 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col00_eq05 : col00.getD 5 Itv.zero = entAt (getT Gtab00) 5 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col00_eq06 : col00.getD 6 Itv.zero = entAt (getT Gtab00) 6 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col00_eq07 : col00.getD 7 Itv.zero = entAt (getT Gtab00) 7 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col00_eq08 : col00.getD 8 Itv.zero = entAt (getT Gtab00) 8 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col00_eq09 : col00.getD 9 Itv.zero = entAt (getT Gtab00) 9 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col00_eq10 : col00.getD 10 Itv.zero = entAt (getT Gtab00) 10 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col00_eq11 : col00.getD 11 Itv.zero = entAt (getT Gtab00) 11 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col00_eq12 : col00.getD 12 Itv.zero = entAt (getT Gtab00) 12 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col00_eq13 : col00.getD 13 Itv.zero = entAt (getT Gtab00) 13 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col00_eq14 : col00.getD 14 Itv.zero = entAt (getT Gtab00) 14 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col00_eq15 : col00.getD 15 Itv.zero = entAt (getT Gtab00) 15 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col00_eq16 : col00.getD 16 Itv.zero = entAt (getT Gtab00) 16 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col00_eq17 : col00.getD 17 Itv.zero = entAt (getT Gtab00) 17 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col00_eq18 : col00.getD 18 Itv.zero = entAt (getT Gtab00) 18 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col00_eq19 : col00.getD 19 Itv.zero = entAt (getT Gtab00) 19 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col00_eq20 : col00.getD 20 Itv.zero = entAt (getT Gtab00) 20 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col00_eq21 : col00.getD 21 Itv.zero = entAt (getT Gtab00) 21 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col00_eq22 : col00.getD 22 Itv.zero = entAt (getT Gtab00) 22 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col00_eq23 : col00.getD 23 Itv.zero = entAt (getT Gtab00) 23 := by
  decide +kernel

theorem col00_eq : ∀ i : Fin 24, col00.getD (i : ℕ) Itv.zero = entAt (getT Gtab00) (i : ℕ) := by
  intro i
  fin_cases i
  exacts [col00_eq00,
    col00_eq01,
    col00_eq02,
    col00_eq03,
    col00_eq04,
    col00_eq05,
    col00_eq06,
    col00_eq07,
    col00_eq08,
    col00_eq09,
    col00_eq10,
    col00_eq11,
    col00_eq12,
    col00_eq13,
    col00_eq14,
    col00_eq15,
    col00_eq16,
    col00_eq17,
    col00_eq18,
    col00_eq19,
    col00_eq20,
    col00_eq21,
    col00_eq22,
    col00_eq23]

theorem ITMem_Gtab00 : ITMem (getT Gtab00) (cG 0) :=
  ITMem_getT_G MItab00_eq Gtab00_eq

theorem mem_col00 (i : Fin 24) : (col00.getD (i : ℕ) Itv.zero).Mem (pivotMatrix i 0) := by
  rw [col00_eq]; exact mem_entAt ITMem_Gtab00 i

end Thomson.Task1b
