-- GENERATED by Thomson/Pivots/gen/mk_tables.py; do not edit
import Thomson.Pivots.KBase

/-! # Task 1b: the tensor of `Gh 4`, and column 4 — GENERATED

Three literal tables, each checked against its definition by `decide +kernel` in pieces small
enough for the kernel's cache (see `KBase`): the blocks `M_k = B_k H_k B_kᵀ` of the indicator block of pivot 4,
three rows at a time; the coefficient tensor built from those blocks, one `(p, q)` row of nine
at a time; and the 24 entries of column 4 of the pivot system, one at a time. -/

namespace Thomson.Task1b

open Thomson Thomson.Tri5b

/-- The blocks `M_k`. -/
def MItab04 : ITab :=
  [[[⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨-434166006998694576952660906173537095235, -434166006998694576952660906173237027037⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨-434166006998694576952660906173537095235, -434166006998694576952660906173237027037⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨9992000000000000000000000000000000000000, 9992000000000000000000000000000000000000⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨9992000000000000000000000000000000000000, 9992000000000000000000000000000000000000⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]]]

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab04_eq_0_0 : ∀ j : Fin (9 - ((0 : Fin 6) : ℕ)),
    mif MItab04 0 ⟨0, by omega⟩ j = MI BI (eHI 4) 0 ⟨0, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab04_eq_0_1 : ∀ j : Fin (9 - ((0 : Fin 6) : ℕ)),
    mif MItab04 0 ⟨1, by omega⟩ j = MI BI (eHI 4) 0 ⟨1, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab04_eq_0_2 : ∀ j : Fin (9 - ((0 : Fin 6) : ℕ)),
    mif MItab04 0 ⟨2, by omega⟩ j = MI BI (eHI 4) 0 ⟨2, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab04_eq_0_3 : ∀ j : Fin (9 - ((0 : Fin 6) : ℕ)),
    mif MItab04 0 ⟨3, by omega⟩ j = MI BI (eHI 4) 0 ⟨3, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab04_eq_0_4 : ∀ j : Fin (9 - ((0 : Fin 6) : ℕ)),
    mif MItab04 0 ⟨4, by omega⟩ j = MI BI (eHI 4) 0 ⟨4, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab04_eq_0_5 : ∀ j : Fin (9 - ((0 : Fin 6) : ℕ)),
    mif MItab04 0 ⟨5, by omega⟩ j = MI BI (eHI 4) 0 ⟨5, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab04_eq_0_6 : ∀ j : Fin (9 - ((0 : Fin 6) : ℕ)),
    mif MItab04 0 ⟨6, by omega⟩ j = MI BI (eHI 4) 0 ⟨6, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab04_eq_0_7 : ∀ j : Fin (9 - ((0 : Fin 6) : ℕ)),
    mif MItab04 0 ⟨7, by omega⟩ j = MI BI (eHI 4) 0 ⟨7, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab04_eq_0_8 : ∀ j : Fin (9 - ((0 : Fin 6) : ℕ)),
    mif MItab04 0 ⟨8, by omega⟩ j = MI BI (eHI 4) 0 ⟨8, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab04_eq_1_0 : ∀ j : Fin (9 - ((1 : Fin 6) : ℕ)),
    mif MItab04 1 ⟨0, by omega⟩ j = MI BI (eHI 4) 1 ⟨0, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab04_eq_1_1 : ∀ j : Fin (9 - ((1 : Fin 6) : ℕ)),
    mif MItab04 1 ⟨1, by omega⟩ j = MI BI (eHI 4) 1 ⟨1, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab04_eq_1_2 : ∀ j : Fin (9 - ((1 : Fin 6) : ℕ)),
    mif MItab04 1 ⟨2, by omega⟩ j = MI BI (eHI 4) 1 ⟨2, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab04_eq_1_3 : ∀ j : Fin (9 - ((1 : Fin 6) : ℕ)),
    mif MItab04 1 ⟨3, by omega⟩ j = MI BI (eHI 4) 1 ⟨3, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab04_eq_1_4 : ∀ j : Fin (9 - ((1 : Fin 6) : ℕ)),
    mif MItab04 1 ⟨4, by omega⟩ j = MI BI (eHI 4) 1 ⟨4, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab04_eq_1_5 : ∀ j : Fin (9 - ((1 : Fin 6) : ℕ)),
    mif MItab04 1 ⟨5, by omega⟩ j = MI BI (eHI 4) 1 ⟨5, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab04_eq_1_6 : ∀ j : Fin (9 - ((1 : Fin 6) : ℕ)),
    mif MItab04 1 ⟨6, by omega⟩ j = MI BI (eHI 4) 1 ⟨6, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab04_eq_1_7 : ∀ j : Fin (9 - ((1 : Fin 6) : ℕ)),
    mif MItab04 1 ⟨7, by omega⟩ j = MI BI (eHI 4) 1 ⟨7, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab04_eq_2_0 : ∀ j : Fin (9 - ((2 : Fin 6) : ℕ)),
    mif MItab04 2 ⟨0, by omega⟩ j = MI BI (eHI 4) 2 ⟨0, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab04_eq_2_1 : ∀ j : Fin (9 - ((2 : Fin 6) : ℕ)),
    mif MItab04 2 ⟨1, by omega⟩ j = MI BI (eHI 4) 2 ⟨1, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab04_eq_2_2 : ∀ j : Fin (9 - ((2 : Fin 6) : ℕ)),
    mif MItab04 2 ⟨2, by omega⟩ j = MI BI (eHI 4) 2 ⟨2, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab04_eq_2_3 : ∀ j : Fin (9 - ((2 : Fin 6) : ℕ)),
    mif MItab04 2 ⟨3, by omega⟩ j = MI BI (eHI 4) 2 ⟨3, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab04_eq_2_4 : ∀ j : Fin (9 - ((2 : Fin 6) : ℕ)),
    mif MItab04 2 ⟨4, by omega⟩ j = MI BI (eHI 4) 2 ⟨4, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab04_eq_2_5 : ∀ j : Fin (9 - ((2 : Fin 6) : ℕ)),
    mif MItab04 2 ⟨5, by omega⟩ j = MI BI (eHI 4) 2 ⟨5, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab04_eq_2_6 : ∀ j : Fin (9 - ((2 : Fin 6) : ℕ)),
    mif MItab04 2 ⟨6, by omega⟩ j = MI BI (eHI 4) 2 ⟨6, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab04_eq_3_0 : ∀ j : Fin (9 - ((3 : Fin 6) : ℕ)),
    mif MItab04 3 ⟨0, by omega⟩ j = MI BI (eHI 4) 3 ⟨0, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab04_eq_3_1 : ∀ j : Fin (9 - ((3 : Fin 6) : ℕ)),
    mif MItab04 3 ⟨1, by omega⟩ j = MI BI (eHI 4) 3 ⟨1, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab04_eq_3_2 : ∀ j : Fin (9 - ((3 : Fin 6) : ℕ)),
    mif MItab04 3 ⟨2, by omega⟩ j = MI BI (eHI 4) 3 ⟨2, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab04_eq_3_3 : ∀ j : Fin (9 - ((3 : Fin 6) : ℕ)),
    mif MItab04 3 ⟨3, by omega⟩ j = MI BI (eHI 4) 3 ⟨3, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab04_eq_3_4 : ∀ j : Fin (9 - ((3 : Fin 6) : ℕ)),
    mif MItab04 3 ⟨4, by omega⟩ j = MI BI (eHI 4) 3 ⟨4, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab04_eq_3_5 : ∀ j : Fin (9 - ((3 : Fin 6) : ℕ)),
    mif MItab04 3 ⟨5, by omega⟩ j = MI BI (eHI 4) 3 ⟨5, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab04_eq_4_0 : ∀ j : Fin (9 - ((4 : Fin 6) : ℕ)),
    mif MItab04 4 ⟨0, by omega⟩ j = MI BI (eHI 4) 4 ⟨0, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab04_eq_4_1 : ∀ j : Fin (9 - ((4 : Fin 6) : ℕ)),
    mif MItab04 4 ⟨1, by omega⟩ j = MI BI (eHI 4) 4 ⟨1, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab04_eq_4_2 : ∀ j : Fin (9 - ((4 : Fin 6) : ℕ)),
    mif MItab04 4 ⟨2, by omega⟩ j = MI BI (eHI 4) 4 ⟨2, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab04_eq_4_3 : ∀ j : Fin (9 - ((4 : Fin 6) : ℕ)),
    mif MItab04 4 ⟨3, by omega⟩ j = MI BI (eHI 4) 4 ⟨3, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab04_eq_4_4 : ∀ j : Fin (9 - ((4 : Fin 6) : ℕ)),
    mif MItab04 4 ⟨4, by omega⟩ j = MI BI (eHI 4) 4 ⟨4, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab04_eq_5_0 : ∀ j : Fin (9 - ((5 : Fin 6) : ℕ)),
    mif MItab04 5 ⟨0, by omega⟩ j = MI BI (eHI 4) 5 ⟨0, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab04_eq_5_1 : ∀ j : Fin (9 - ((5 : Fin 6) : ℕ)),
    mif MItab04 5 ⟨1, by omega⟩ j = MI BI (eHI 4) 5 ⟨1, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab04_eq_5_2 : ∀ j : Fin (9 - ((5 : Fin 6) : ℕ)),
    mif MItab04 5 ⟨2, by omega⟩ j = MI BI (eHI 4) 5 ⟨2, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab04_eq_5_3 : ∀ j : Fin (9 - ((5 : Fin 6) : ℕ)),
    mif MItab04 5 ⟨3, by omega⟩ j = MI BI (eHI 4) 5 ⟨3, by omega⟩ j := by
  decide +kernel

theorem MItab04_eq : ∀ (k : Fin 6) (i j : Fin (9 - (k : ℕ))),
    mif MItab04 k i j = MI BI (eHI 4) k i j := by
  intro k i
  fin_cases k <;> fin_cases i
  exacts [MItab04_eq_0_0,
    MItab04_eq_0_1,
    MItab04_eq_0_2,
    MItab04_eq_0_3,
    MItab04_eq_0_4,
    MItab04_eq_0_5,
    MItab04_eq_0_6,
    MItab04_eq_0_7,
    MItab04_eq_0_8,
    MItab04_eq_1_0,
    MItab04_eq_1_1,
    MItab04_eq_1_2,
    MItab04_eq_1_3,
    MItab04_eq_1_4,
    MItab04_eq_1_5,
    MItab04_eq_1_6,
    MItab04_eq_1_7,
    MItab04_eq_2_0,
    MItab04_eq_2_1,
    MItab04_eq_2_2,
    MItab04_eq_2_3,
    MItab04_eq_2_4,
    MItab04_eq_2_5,
    MItab04_eq_2_6,
    MItab04_eq_3_0,
    MItab04_eq_3_1,
    MItab04_eq_3_2,
    MItab04_eq_3_3,
    MItab04_eq_3_4,
    MItab04_eq_3_5,
    MItab04_eq_4_0,
    MItab04_eq_4_1,
    MItab04_eq_4_2,
    MItab04_eq_4_3,
    MItab04_eq_4_4,
    MItab04_eq_5_0,
    MItab04_eq_5_1,
    MItab04_eq_5_2,
    MItab04_eq_5_3]

/-- The coefficient tensor. -/
def Gtab04 : ITab :=
  [[[⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨-289444004665796384635107270782358063491, -289444004665796384635107270782158018024⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨-289444004665796384635107270782358063491, -289444004665796384635107270782158018024⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨3330666666666666666666666666666666666666, 3330666666666666666666666666666666666668⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨3330666666666666666666666666666666666666, 3330666666666666666666666666666666666668⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨-289444004665796384635107270782358063491, -289444004665796384635107270782158018024⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨3330666666666666666666666666666666666666, 3330666666666666666666666666666666666668⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨3330666666666666666666666666666666666666, 3330666666666666666666666666666666666668⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨3330666666666666666666666666666666666666, 3330666666666666666666666666666666666668⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨3330666666666666666666666666666666666666, 3330666666666666666666666666666666666668⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]]]

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_0_0 : ∀ r : Fin 9, getT Gtab04 0 0 r = CF (mif MItab04) 0 0 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_0_1 : ∀ r : Fin 9, getT Gtab04 0 1 r = CF (mif MItab04) 0 1 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_0_2 : ∀ r : Fin 9, getT Gtab04 0 2 r = CF (mif MItab04) 0 2 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_0_3 : ∀ r : Fin 9, getT Gtab04 0 3 r = CF (mif MItab04) 0 3 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_0_4 : ∀ r : Fin 9, getT Gtab04 0 4 r = CF (mif MItab04) 0 4 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_0_5 : ∀ r : Fin 9, getT Gtab04 0 5 r = CF (mif MItab04) 0 5 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_0_6 : ∀ r : Fin 9, getT Gtab04 0 6 r = CF (mif MItab04) 0 6 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_0_7 : ∀ r : Fin 9, getT Gtab04 0 7 r = CF (mif MItab04) 0 7 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_0_8 : ∀ r : Fin 9, getT Gtab04 0 8 r = CF (mif MItab04) 0 8 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_1_0 : ∀ r : Fin 9, getT Gtab04 1 0 r = CF (mif MItab04) 1 0 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_1_1 : ∀ r : Fin 9, getT Gtab04 1 1 r = CF (mif MItab04) 1 1 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_1_2 : ∀ r : Fin 9, getT Gtab04 1 2 r = CF (mif MItab04) 1 2 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_1_3 : ∀ r : Fin 9, getT Gtab04 1 3 r = CF (mif MItab04) 1 3 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_1_4 : ∀ r : Fin 9, getT Gtab04 1 4 r = CF (mif MItab04) 1 4 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_1_5 : ∀ r : Fin 9, getT Gtab04 1 5 r = CF (mif MItab04) 1 5 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_1_6 : ∀ r : Fin 9, getT Gtab04 1 6 r = CF (mif MItab04) 1 6 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_1_7 : ∀ r : Fin 9, getT Gtab04 1 7 r = CF (mif MItab04) 1 7 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_1_8 : ∀ r : Fin 9, getT Gtab04 1 8 r = CF (mif MItab04) 1 8 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_2_0 : ∀ r : Fin 9, getT Gtab04 2 0 r = CF (mif MItab04) 2 0 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_2_1 : ∀ r : Fin 9, getT Gtab04 2 1 r = CF (mif MItab04) 2 1 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_2_2 : ∀ r : Fin 9, getT Gtab04 2 2 r = CF (mif MItab04) 2 2 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_2_3 : ∀ r : Fin 9, getT Gtab04 2 3 r = CF (mif MItab04) 2 3 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_2_4 : ∀ r : Fin 9, getT Gtab04 2 4 r = CF (mif MItab04) 2 4 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_2_5 : ∀ r : Fin 9, getT Gtab04 2 5 r = CF (mif MItab04) 2 5 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_2_6 : ∀ r : Fin 9, getT Gtab04 2 6 r = CF (mif MItab04) 2 6 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_2_7 : ∀ r : Fin 9, getT Gtab04 2 7 r = CF (mif MItab04) 2 7 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_2_8 : ∀ r : Fin 9, getT Gtab04 2 8 r = CF (mif MItab04) 2 8 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_3_0 : ∀ r : Fin 9, getT Gtab04 3 0 r = CF (mif MItab04) 3 0 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_3_1 : ∀ r : Fin 9, getT Gtab04 3 1 r = CF (mif MItab04) 3 1 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_3_2 : ∀ r : Fin 9, getT Gtab04 3 2 r = CF (mif MItab04) 3 2 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_3_3 : ∀ r : Fin 9, getT Gtab04 3 3 r = CF (mif MItab04) 3 3 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_3_4 : ∀ r : Fin 9, getT Gtab04 3 4 r = CF (mif MItab04) 3 4 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_3_5 : ∀ r : Fin 9, getT Gtab04 3 5 r = CF (mif MItab04) 3 5 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_3_6 : ∀ r : Fin 9, getT Gtab04 3 6 r = CF (mif MItab04) 3 6 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_3_7 : ∀ r : Fin 9, getT Gtab04 3 7 r = CF (mif MItab04) 3 7 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_3_8 : ∀ r : Fin 9, getT Gtab04 3 8 r = CF (mif MItab04) 3 8 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_4_0 : ∀ r : Fin 9, getT Gtab04 4 0 r = CF (mif MItab04) 4 0 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_4_1 : ∀ r : Fin 9, getT Gtab04 4 1 r = CF (mif MItab04) 4 1 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_4_2 : ∀ r : Fin 9, getT Gtab04 4 2 r = CF (mif MItab04) 4 2 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_4_3 : ∀ r : Fin 9, getT Gtab04 4 3 r = CF (mif MItab04) 4 3 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_4_4 : ∀ r : Fin 9, getT Gtab04 4 4 r = CF (mif MItab04) 4 4 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_4_5 : ∀ r : Fin 9, getT Gtab04 4 5 r = CF (mif MItab04) 4 5 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_4_6 : ∀ r : Fin 9, getT Gtab04 4 6 r = CF (mif MItab04) 4 6 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_4_7 : ∀ r : Fin 9, getT Gtab04 4 7 r = CF (mif MItab04) 4 7 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_4_8 : ∀ r : Fin 9, getT Gtab04 4 8 r = CF (mif MItab04) 4 8 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_5_0 : ∀ r : Fin 9, getT Gtab04 5 0 r = CF (mif MItab04) 5 0 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_5_1 : ∀ r : Fin 9, getT Gtab04 5 1 r = CF (mif MItab04) 5 1 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_5_2 : ∀ r : Fin 9, getT Gtab04 5 2 r = CF (mif MItab04) 5 2 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_5_3 : ∀ r : Fin 9, getT Gtab04 5 3 r = CF (mif MItab04) 5 3 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_5_4 : ∀ r : Fin 9, getT Gtab04 5 4 r = CF (mif MItab04) 5 4 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_5_5 : ∀ r : Fin 9, getT Gtab04 5 5 r = CF (mif MItab04) 5 5 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_5_6 : ∀ r : Fin 9, getT Gtab04 5 6 r = CF (mif MItab04) 5 6 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_5_7 : ∀ r : Fin 9, getT Gtab04 5 7 r = CF (mif MItab04) 5 7 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_5_8 : ∀ r : Fin 9, getT Gtab04 5 8 r = CF (mif MItab04) 5 8 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_6_0 : ∀ r : Fin 9, getT Gtab04 6 0 r = CF (mif MItab04) 6 0 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_6_1 : ∀ r : Fin 9, getT Gtab04 6 1 r = CF (mif MItab04) 6 1 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_6_2 : ∀ r : Fin 9, getT Gtab04 6 2 r = CF (mif MItab04) 6 2 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_6_3 : ∀ r : Fin 9, getT Gtab04 6 3 r = CF (mif MItab04) 6 3 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_6_4 : ∀ r : Fin 9, getT Gtab04 6 4 r = CF (mif MItab04) 6 4 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_6_5 : ∀ r : Fin 9, getT Gtab04 6 5 r = CF (mif MItab04) 6 5 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_6_6 : ∀ r : Fin 9, getT Gtab04 6 6 r = CF (mif MItab04) 6 6 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_6_7 : ∀ r : Fin 9, getT Gtab04 6 7 r = CF (mif MItab04) 6 7 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_6_8 : ∀ r : Fin 9, getT Gtab04 6 8 r = CF (mif MItab04) 6 8 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_7_0 : ∀ r : Fin 9, getT Gtab04 7 0 r = CF (mif MItab04) 7 0 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_7_1 : ∀ r : Fin 9, getT Gtab04 7 1 r = CF (mif MItab04) 7 1 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_7_2 : ∀ r : Fin 9, getT Gtab04 7 2 r = CF (mif MItab04) 7 2 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_7_3 : ∀ r : Fin 9, getT Gtab04 7 3 r = CF (mif MItab04) 7 3 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_7_4 : ∀ r : Fin 9, getT Gtab04 7 4 r = CF (mif MItab04) 7 4 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_7_5 : ∀ r : Fin 9, getT Gtab04 7 5 r = CF (mif MItab04) 7 5 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_7_6 : ∀ r : Fin 9, getT Gtab04 7 6 r = CF (mif MItab04) 7 6 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_7_7 : ∀ r : Fin 9, getT Gtab04 7 7 r = CF (mif MItab04) 7 7 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_7_8 : ∀ r : Fin 9, getT Gtab04 7 8 r = CF (mif MItab04) 7 8 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_8_0 : ∀ r : Fin 9, getT Gtab04 8 0 r = CF (mif MItab04) 8 0 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_8_1 : ∀ r : Fin 9, getT Gtab04 8 1 r = CF (mif MItab04) 8 1 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_8_2 : ∀ r : Fin 9, getT Gtab04 8 2 r = CF (mif MItab04) 8 2 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_8_3 : ∀ r : Fin 9, getT Gtab04 8 3 r = CF (mif MItab04) 8 3 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_8_4 : ∀ r : Fin 9, getT Gtab04 8 4 r = CF (mif MItab04) 8 4 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_8_5 : ∀ r : Fin 9, getT Gtab04 8 5 r = CF (mif MItab04) 8 5 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_8_6 : ∀ r : Fin 9, getT Gtab04 8 6 r = CF (mif MItab04) 8 6 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_8_7 : ∀ r : Fin 9, getT Gtab04 8 7 r = CF (mif MItab04) 8 7 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab04_eq_8_8 : ∀ r : Fin 9, getT Gtab04 8 8 r = CF (mif MItab04) 8 8 r := by
  decide +kernel

theorem Gtab04_eq : ∀ p q r : Fin 9, getT Gtab04 p q r = CF (mif MItab04) p q r := by
  intro p q
  fin_cases p <;> fin_cases q
  exacts [Gtab04_eq_0_0,
    Gtab04_eq_0_1,
    Gtab04_eq_0_2,
    Gtab04_eq_0_3,
    Gtab04_eq_0_4,
    Gtab04_eq_0_5,
    Gtab04_eq_0_6,
    Gtab04_eq_0_7,
    Gtab04_eq_0_8,
    Gtab04_eq_1_0,
    Gtab04_eq_1_1,
    Gtab04_eq_1_2,
    Gtab04_eq_1_3,
    Gtab04_eq_1_4,
    Gtab04_eq_1_5,
    Gtab04_eq_1_6,
    Gtab04_eq_1_7,
    Gtab04_eq_1_8,
    Gtab04_eq_2_0,
    Gtab04_eq_2_1,
    Gtab04_eq_2_2,
    Gtab04_eq_2_3,
    Gtab04_eq_2_4,
    Gtab04_eq_2_5,
    Gtab04_eq_2_6,
    Gtab04_eq_2_7,
    Gtab04_eq_2_8,
    Gtab04_eq_3_0,
    Gtab04_eq_3_1,
    Gtab04_eq_3_2,
    Gtab04_eq_3_3,
    Gtab04_eq_3_4,
    Gtab04_eq_3_5,
    Gtab04_eq_3_6,
    Gtab04_eq_3_7,
    Gtab04_eq_3_8,
    Gtab04_eq_4_0,
    Gtab04_eq_4_1,
    Gtab04_eq_4_2,
    Gtab04_eq_4_3,
    Gtab04_eq_4_4,
    Gtab04_eq_4_5,
    Gtab04_eq_4_6,
    Gtab04_eq_4_7,
    Gtab04_eq_4_8,
    Gtab04_eq_5_0,
    Gtab04_eq_5_1,
    Gtab04_eq_5_2,
    Gtab04_eq_5_3,
    Gtab04_eq_5_4,
    Gtab04_eq_5_5,
    Gtab04_eq_5_6,
    Gtab04_eq_5_7,
    Gtab04_eq_5_8,
    Gtab04_eq_6_0,
    Gtab04_eq_6_1,
    Gtab04_eq_6_2,
    Gtab04_eq_6_3,
    Gtab04_eq_6_4,
    Gtab04_eq_6_5,
    Gtab04_eq_6_6,
    Gtab04_eq_6_7,
    Gtab04_eq_6_8,
    Gtab04_eq_7_0,
    Gtab04_eq_7_1,
    Gtab04_eq_7_2,
    Gtab04_eq_7_3,
    Gtab04_eq_7_4,
    Gtab04_eq_7_5,
    Gtab04_eq_7_6,
    Gtab04_eq_7_7,
    Gtab04_eq_7_8,
    Gtab04_eq_8_0,
    Gtab04_eq_8_1,
    Gtab04_eq_8_2,
    Gtab04_eq_8_3,
    Gtab04_eq_8_4,
    Gtab04_eq_8_5,
    Gtab04_eq_8_6,
    Gtab04_eq_8_7,
    Gtab04_eq_8_8]

/-- The 24 entries. -/
def col04 : List Itv :=
  [⟨-76462671944010443384378712750614103783744, -76462671944010443384378712750611703238092⟩,
    ⟨9048511403599668763948575797104028635907, 9048511403599668763948575797109599680657⟩,
    ⟨3215146504213576924424528212967337957634, 3215146504213576924424528212969727360446⟩,
    ⟨27514185832534972244894169760409716157228, 27514185832534972244894169760426793782223⟩,
    ⟨997042212509646038291600475330362987683, 997042212509646038291600475331347168172⟩,
    ⟨3568650916843382806964338377766616244720, 3568650916843382806964338377770336070140⟩,
    ⟨25358490997940383059308666757931331317342, 25358490997940383059308666757950807004181⟩,
    ⟨166058255878148123429409445110647313502583, 166058255878148123429409445110835680802083⟩,
    ⟨-5547656656091529451949679690233712225961, -5547656656091529451949679690228178516619⟩,
    ⟨-49840513692846244531000276151480629977987, -49840513692846244531000276151438302850632⟩,
    ⟨-9146724542291744335634038866240873176712, -9146724542291744335634038866232233646008⟩,
    ⟨-902997712875870155272257820854686497879, -902997712875870155272257820853619071210⟩,
    ⟨-7491180827357611331989651401273897169847, -7491180827357611331989651401265624033094⟩,
    ⟨-1381374844219959471707636680872277391657, -1381374844219959471707636680870499327028⟩,
    ⟨-265658766030813669749278212833171112911, -265658766030813669749278212832566139253⟩,
    ⟨-1712370418300276312784037724762602920730, -1712370418300276312784037724758122742628⟩,
    ⟨-671981380731754196857166639979719330355, -671981380731754196857166639978574324211⟩,
    ⟨-1864058213133994953959217910893569729393, -1864058213133994953959217910891484953675⟩,
    ⟨11227454337212230101010251275587967787, 11227454337212230101010251275686071123⟩,
    ⟨-339027178958156156053314936431180350358, -339027178958156156053314936430486484312⟩,
    ⟨-237829473537628659329049063957937258372, -237829473537628659329049063957527338350⟩,
    ⟨22766555745998811733632902946662824503, 22766555745998811733632902946695961786⟩,
    ⟨-42144188319120888854297086391012580992, -42144188319120888854297086390880633271⟩,
    ⟨-171082561413971707086550471579569078959, -171082561413971707086550471579313054522⟩]

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col04_eq00 : col04.getD 0 Itv.zero = entAt (getT Gtab04) 0 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col04_eq01 : col04.getD 1 Itv.zero = entAt (getT Gtab04) 1 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col04_eq02 : col04.getD 2 Itv.zero = entAt (getT Gtab04) 2 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col04_eq03 : col04.getD 3 Itv.zero = entAt (getT Gtab04) 3 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col04_eq04 : col04.getD 4 Itv.zero = entAt (getT Gtab04) 4 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col04_eq05 : col04.getD 5 Itv.zero = entAt (getT Gtab04) 5 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col04_eq06 : col04.getD 6 Itv.zero = entAt (getT Gtab04) 6 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col04_eq07 : col04.getD 7 Itv.zero = entAt (getT Gtab04) 7 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col04_eq08 : col04.getD 8 Itv.zero = entAt (getT Gtab04) 8 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col04_eq09 : col04.getD 9 Itv.zero = entAt (getT Gtab04) 9 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col04_eq10 : col04.getD 10 Itv.zero = entAt (getT Gtab04) 10 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col04_eq11 : col04.getD 11 Itv.zero = entAt (getT Gtab04) 11 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col04_eq12 : col04.getD 12 Itv.zero = entAt (getT Gtab04) 12 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col04_eq13 : col04.getD 13 Itv.zero = entAt (getT Gtab04) 13 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col04_eq14 : col04.getD 14 Itv.zero = entAt (getT Gtab04) 14 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col04_eq15 : col04.getD 15 Itv.zero = entAt (getT Gtab04) 15 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col04_eq16 : col04.getD 16 Itv.zero = entAt (getT Gtab04) 16 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col04_eq17 : col04.getD 17 Itv.zero = entAt (getT Gtab04) 17 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col04_eq18 : col04.getD 18 Itv.zero = entAt (getT Gtab04) 18 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col04_eq19 : col04.getD 19 Itv.zero = entAt (getT Gtab04) 19 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col04_eq20 : col04.getD 20 Itv.zero = entAt (getT Gtab04) 20 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col04_eq21 : col04.getD 21 Itv.zero = entAt (getT Gtab04) 21 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col04_eq22 : col04.getD 22 Itv.zero = entAt (getT Gtab04) 22 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col04_eq23 : col04.getD 23 Itv.zero = entAt (getT Gtab04) 23 := by
  decide +kernel

theorem col04_eq : ∀ i : Fin 24, col04.getD (i : ℕ) Itv.zero = entAt (getT Gtab04) (i : ℕ) := by
  intro i
  fin_cases i
  exacts [col04_eq00,
    col04_eq01,
    col04_eq02,
    col04_eq03,
    col04_eq04,
    col04_eq05,
    col04_eq06,
    col04_eq07,
    col04_eq08,
    col04_eq09,
    col04_eq10,
    col04_eq11,
    col04_eq12,
    col04_eq13,
    col04_eq14,
    col04_eq15,
    col04_eq16,
    col04_eq17,
    col04_eq18,
    col04_eq19,
    col04_eq20,
    col04_eq21,
    col04_eq22,
    col04_eq23]

theorem ITMem_Gtab04 : ITMem (getT Gtab04) (cG 4) :=
  ITMem_getT_G MItab04_eq Gtab04_eq

theorem mem_col04 (i : Fin 24) : (col04.getD (i : ℕ) Itv.zero).Mem (pivotMatrix i 4) := by
  rw [col04_eq]; exact mem_entAt ITMem_Gtab04 i

end Thomson.Task1b
