-- GENERATED by Thomson/Pivots/gen/mk_tables.py; do not edit
import Thomson.Pivots.KBase

/-! # Task 1b: the tensor of `Gh 6`, and column 6 — GENERATED

Three literal tables, each checked against its definition by `decide +kernel` in pieces small
enough for the kernel's cache (see `KBase`): the blocks `M_k = B_k H_k B_kᵀ` of the indicator block of pivot 6,
three rows at a time; the coefficient tensor built from those blocks, one `(p, q)` row of nine
at a time; and the 24 entries of column 6 of the pivot system, one at a time. -/

namespace Thomson.Task1b

open Thomson Thomson.Tri5b

/-- The blocks `M_k`. -/
def MItab06 : ITab :=
  [[[⟨615586806621135160606610933921779460382, 615586806621135160606610933923607396318⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨-1614254750712060659396819219325501541130, -1614254750712060659396819219322002049851⟩, ⟨0, 0⟩, ⟨-1847087474389600069222724616050926395685, -1847087474389600069222724616049445858615⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨-1614254750712060659396819219325501541130, -1614254750712060659396819219322002049851⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨9687243776000000000000000000000000000000, 9687243776000000000000000000000000000000⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨-1847087474389600069222724616050926395685, -1847087474389600069222724616049445858615⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨9687243776000000000000000000000000000000, 9687243776000000000000000000000000000000⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]]]

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab06_eq_0_0 : ∀ j : Fin (9 - ((0 : Fin 6) : ℕ)),
    mif MItab06 0 ⟨0, by omega⟩ j = MI BI (eHI 6) 0 ⟨0, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab06_eq_0_1 : ∀ j : Fin (9 - ((0 : Fin 6) : ℕ)),
    mif MItab06 0 ⟨1, by omega⟩ j = MI BI (eHI 6) 0 ⟨1, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab06_eq_0_2 : ∀ j : Fin (9 - ((0 : Fin 6) : ℕ)),
    mif MItab06 0 ⟨2, by omega⟩ j = MI BI (eHI 6) 0 ⟨2, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab06_eq_0_3 : ∀ j : Fin (9 - ((0 : Fin 6) : ℕ)),
    mif MItab06 0 ⟨3, by omega⟩ j = MI BI (eHI 6) 0 ⟨3, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab06_eq_0_4 : ∀ j : Fin (9 - ((0 : Fin 6) : ℕ)),
    mif MItab06 0 ⟨4, by omega⟩ j = MI BI (eHI 6) 0 ⟨4, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab06_eq_0_5 : ∀ j : Fin (9 - ((0 : Fin 6) : ℕ)),
    mif MItab06 0 ⟨5, by omega⟩ j = MI BI (eHI 6) 0 ⟨5, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab06_eq_0_6 : ∀ j : Fin (9 - ((0 : Fin 6) : ℕ)),
    mif MItab06 0 ⟨6, by omega⟩ j = MI BI (eHI 6) 0 ⟨6, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab06_eq_0_7 : ∀ j : Fin (9 - ((0 : Fin 6) : ℕ)),
    mif MItab06 0 ⟨7, by omega⟩ j = MI BI (eHI 6) 0 ⟨7, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab06_eq_0_8 : ∀ j : Fin (9 - ((0 : Fin 6) : ℕ)),
    mif MItab06 0 ⟨8, by omega⟩ j = MI BI (eHI 6) 0 ⟨8, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab06_eq_1_0 : ∀ j : Fin (9 - ((1 : Fin 6) : ℕ)),
    mif MItab06 1 ⟨0, by omega⟩ j = MI BI (eHI 6) 1 ⟨0, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab06_eq_1_1 : ∀ j : Fin (9 - ((1 : Fin 6) : ℕ)),
    mif MItab06 1 ⟨1, by omega⟩ j = MI BI (eHI 6) 1 ⟨1, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab06_eq_1_2 : ∀ j : Fin (9 - ((1 : Fin 6) : ℕ)),
    mif MItab06 1 ⟨2, by omega⟩ j = MI BI (eHI 6) 1 ⟨2, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab06_eq_1_3 : ∀ j : Fin (9 - ((1 : Fin 6) : ℕ)),
    mif MItab06 1 ⟨3, by omega⟩ j = MI BI (eHI 6) 1 ⟨3, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab06_eq_1_4 : ∀ j : Fin (9 - ((1 : Fin 6) : ℕ)),
    mif MItab06 1 ⟨4, by omega⟩ j = MI BI (eHI 6) 1 ⟨4, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab06_eq_1_5 : ∀ j : Fin (9 - ((1 : Fin 6) : ℕ)),
    mif MItab06 1 ⟨5, by omega⟩ j = MI BI (eHI 6) 1 ⟨5, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab06_eq_1_6 : ∀ j : Fin (9 - ((1 : Fin 6) : ℕ)),
    mif MItab06 1 ⟨6, by omega⟩ j = MI BI (eHI 6) 1 ⟨6, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab06_eq_1_7 : ∀ j : Fin (9 - ((1 : Fin 6) : ℕ)),
    mif MItab06 1 ⟨7, by omega⟩ j = MI BI (eHI 6) 1 ⟨7, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab06_eq_2_0 : ∀ j : Fin (9 - ((2 : Fin 6) : ℕ)),
    mif MItab06 2 ⟨0, by omega⟩ j = MI BI (eHI 6) 2 ⟨0, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab06_eq_2_1 : ∀ j : Fin (9 - ((2 : Fin 6) : ℕ)),
    mif MItab06 2 ⟨1, by omega⟩ j = MI BI (eHI 6) 2 ⟨1, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab06_eq_2_2 : ∀ j : Fin (9 - ((2 : Fin 6) : ℕ)),
    mif MItab06 2 ⟨2, by omega⟩ j = MI BI (eHI 6) 2 ⟨2, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab06_eq_2_3 : ∀ j : Fin (9 - ((2 : Fin 6) : ℕ)),
    mif MItab06 2 ⟨3, by omega⟩ j = MI BI (eHI 6) 2 ⟨3, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab06_eq_2_4 : ∀ j : Fin (9 - ((2 : Fin 6) : ℕ)),
    mif MItab06 2 ⟨4, by omega⟩ j = MI BI (eHI 6) 2 ⟨4, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab06_eq_2_5 : ∀ j : Fin (9 - ((2 : Fin 6) : ℕ)),
    mif MItab06 2 ⟨5, by omega⟩ j = MI BI (eHI 6) 2 ⟨5, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab06_eq_2_6 : ∀ j : Fin (9 - ((2 : Fin 6) : ℕ)),
    mif MItab06 2 ⟨6, by omega⟩ j = MI BI (eHI 6) 2 ⟨6, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab06_eq_3_0 : ∀ j : Fin (9 - ((3 : Fin 6) : ℕ)),
    mif MItab06 3 ⟨0, by omega⟩ j = MI BI (eHI 6) 3 ⟨0, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab06_eq_3_1 : ∀ j : Fin (9 - ((3 : Fin 6) : ℕ)),
    mif MItab06 3 ⟨1, by omega⟩ j = MI BI (eHI 6) 3 ⟨1, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab06_eq_3_2 : ∀ j : Fin (9 - ((3 : Fin 6) : ℕ)),
    mif MItab06 3 ⟨2, by omega⟩ j = MI BI (eHI 6) 3 ⟨2, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab06_eq_3_3 : ∀ j : Fin (9 - ((3 : Fin 6) : ℕ)),
    mif MItab06 3 ⟨3, by omega⟩ j = MI BI (eHI 6) 3 ⟨3, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab06_eq_3_4 : ∀ j : Fin (9 - ((3 : Fin 6) : ℕ)),
    mif MItab06 3 ⟨4, by omega⟩ j = MI BI (eHI 6) 3 ⟨4, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab06_eq_3_5 : ∀ j : Fin (9 - ((3 : Fin 6) : ℕ)),
    mif MItab06 3 ⟨5, by omega⟩ j = MI BI (eHI 6) 3 ⟨5, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab06_eq_4_0 : ∀ j : Fin (9 - ((4 : Fin 6) : ℕ)),
    mif MItab06 4 ⟨0, by omega⟩ j = MI BI (eHI 6) 4 ⟨0, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab06_eq_4_1 : ∀ j : Fin (9 - ((4 : Fin 6) : ℕ)),
    mif MItab06 4 ⟨1, by omega⟩ j = MI BI (eHI 6) 4 ⟨1, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab06_eq_4_2 : ∀ j : Fin (9 - ((4 : Fin 6) : ℕ)),
    mif MItab06 4 ⟨2, by omega⟩ j = MI BI (eHI 6) 4 ⟨2, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab06_eq_4_3 : ∀ j : Fin (9 - ((4 : Fin 6) : ℕ)),
    mif MItab06 4 ⟨3, by omega⟩ j = MI BI (eHI 6) 4 ⟨3, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab06_eq_4_4 : ∀ j : Fin (9 - ((4 : Fin 6) : ℕ)),
    mif MItab06 4 ⟨4, by omega⟩ j = MI BI (eHI 6) 4 ⟨4, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab06_eq_5_0 : ∀ j : Fin (9 - ((5 : Fin 6) : ℕ)),
    mif MItab06 5 ⟨0, by omega⟩ j = MI BI (eHI 6) 5 ⟨0, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab06_eq_5_1 : ∀ j : Fin (9 - ((5 : Fin 6) : ℕ)),
    mif MItab06 5 ⟨1, by omega⟩ j = MI BI (eHI 6) 5 ⟨1, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab06_eq_5_2 : ∀ j : Fin (9 - ((5 : Fin 6) : ℕ)),
    mif MItab06 5 ⟨2, by omega⟩ j = MI BI (eHI 6) 5 ⟨2, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab06_eq_5_3 : ∀ j : Fin (9 - ((5 : Fin 6) : ℕ)),
    mif MItab06 5 ⟨3, by omega⟩ j = MI BI (eHI 6) 5 ⟨3, by omega⟩ j := by
  decide +kernel

theorem MItab06_eq : ∀ (k : Fin 6) (i j : Fin (9 - (k : ℕ))),
    mif MItab06 k i j = MI BI (eHI 6) k i j := by
  intro k i
  fin_cases k <;> fin_cases i
  exacts [MItab06_eq_0_0,
    MItab06_eq_0_1,
    MItab06_eq_0_2,
    MItab06_eq_0_3,
    MItab06_eq_0_4,
    MItab06_eq_0_5,
    MItab06_eq_0_6,
    MItab06_eq_0_7,
    MItab06_eq_0_8,
    MItab06_eq_1_0,
    MItab06_eq_1_1,
    MItab06_eq_1_2,
    MItab06_eq_1_3,
    MItab06_eq_1_4,
    MItab06_eq_1_5,
    MItab06_eq_1_6,
    MItab06_eq_1_7,
    MItab06_eq_2_0,
    MItab06_eq_2_1,
    MItab06_eq_2_2,
    MItab06_eq_2_3,
    MItab06_eq_2_4,
    MItab06_eq_2_5,
    MItab06_eq_2_6,
    MItab06_eq_3_0,
    MItab06_eq_3_1,
    MItab06_eq_3_2,
    MItab06_eq_3_3,
    MItab06_eq_3_4,
    MItab06_eq_3_5,
    MItab06_eq_4_0,
    MItab06_eq_4_1,
    MItab06_eq_4_2,
    MItab06_eq_4_3,
    MItab06_eq_4_4,
    MItab06_eq_5_0,
    MItab06_eq_5_1,
    MItab06_eq_5_2,
    MItab06_eq_5_3]

/-- The coefficient tensor. -/
def Gtab06 : ITab :=
  [[[⟨615586806621135160606610933921779460381, 615586806621135160606610933923607396319⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨-1076169833808040439597879479550334360754, -1076169833808040439597879479548001366567⟩, ⟨0, 0⟩, ⟨-1231391649593066712815149744033950930457, -1231391649593066712815149744032963905743⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨-1076169833808040439597879479550334360754, -1076169833808040439597879479548001366567⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨3229081258666666666666666666666666666666, 3229081258666666666666666666666666666668⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨-1231391649593066712815149744033950930457, -1231391649593066712815149744032963905743⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨3229081258666666666666666666666666666666, 3229081258666666666666666666666666666668⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨-1076169833808040439597879479550334360754, -1076169833808040439597879479548001366567⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨3229081258666666666666666666666666666666, 3229081258666666666666666666666666666668⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨3229081258666666666666666666666666666666, 3229081258666666666666666666666666666668⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨-1231391649593066712815149744033950930457, -1231391649593066712815149744032963905743⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨3229081258666666666666666666666666666666, 3229081258666666666666666666666666666668⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨3229081258666666666666666666666666666666, 3229081258666666666666666666666666666668⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]]]

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_0_0 : ∀ r : Fin 9, getT Gtab06 0 0 r = CF (mif MItab06) 0 0 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_0_1 : ∀ r : Fin 9, getT Gtab06 0 1 r = CF (mif MItab06) 0 1 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_0_2 : ∀ r : Fin 9, getT Gtab06 0 2 r = CF (mif MItab06) 0 2 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_0_3 : ∀ r : Fin 9, getT Gtab06 0 3 r = CF (mif MItab06) 0 3 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_0_4 : ∀ r : Fin 9, getT Gtab06 0 4 r = CF (mif MItab06) 0 4 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_0_5 : ∀ r : Fin 9, getT Gtab06 0 5 r = CF (mif MItab06) 0 5 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_0_6 : ∀ r : Fin 9, getT Gtab06 0 6 r = CF (mif MItab06) 0 6 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_0_7 : ∀ r : Fin 9, getT Gtab06 0 7 r = CF (mif MItab06) 0 7 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_0_8 : ∀ r : Fin 9, getT Gtab06 0 8 r = CF (mif MItab06) 0 8 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_1_0 : ∀ r : Fin 9, getT Gtab06 1 0 r = CF (mif MItab06) 1 0 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_1_1 : ∀ r : Fin 9, getT Gtab06 1 1 r = CF (mif MItab06) 1 1 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_1_2 : ∀ r : Fin 9, getT Gtab06 1 2 r = CF (mif MItab06) 1 2 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_1_3 : ∀ r : Fin 9, getT Gtab06 1 3 r = CF (mif MItab06) 1 3 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_1_4 : ∀ r : Fin 9, getT Gtab06 1 4 r = CF (mif MItab06) 1 4 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_1_5 : ∀ r : Fin 9, getT Gtab06 1 5 r = CF (mif MItab06) 1 5 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_1_6 : ∀ r : Fin 9, getT Gtab06 1 6 r = CF (mif MItab06) 1 6 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_1_7 : ∀ r : Fin 9, getT Gtab06 1 7 r = CF (mif MItab06) 1 7 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_1_8 : ∀ r : Fin 9, getT Gtab06 1 8 r = CF (mif MItab06) 1 8 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_2_0 : ∀ r : Fin 9, getT Gtab06 2 0 r = CF (mif MItab06) 2 0 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_2_1 : ∀ r : Fin 9, getT Gtab06 2 1 r = CF (mif MItab06) 2 1 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_2_2 : ∀ r : Fin 9, getT Gtab06 2 2 r = CF (mif MItab06) 2 2 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_2_3 : ∀ r : Fin 9, getT Gtab06 2 3 r = CF (mif MItab06) 2 3 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_2_4 : ∀ r : Fin 9, getT Gtab06 2 4 r = CF (mif MItab06) 2 4 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_2_5 : ∀ r : Fin 9, getT Gtab06 2 5 r = CF (mif MItab06) 2 5 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_2_6 : ∀ r : Fin 9, getT Gtab06 2 6 r = CF (mif MItab06) 2 6 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_2_7 : ∀ r : Fin 9, getT Gtab06 2 7 r = CF (mif MItab06) 2 7 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_2_8 : ∀ r : Fin 9, getT Gtab06 2 8 r = CF (mif MItab06) 2 8 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_3_0 : ∀ r : Fin 9, getT Gtab06 3 0 r = CF (mif MItab06) 3 0 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_3_1 : ∀ r : Fin 9, getT Gtab06 3 1 r = CF (mif MItab06) 3 1 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_3_2 : ∀ r : Fin 9, getT Gtab06 3 2 r = CF (mif MItab06) 3 2 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_3_3 : ∀ r : Fin 9, getT Gtab06 3 3 r = CF (mif MItab06) 3 3 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_3_4 : ∀ r : Fin 9, getT Gtab06 3 4 r = CF (mif MItab06) 3 4 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_3_5 : ∀ r : Fin 9, getT Gtab06 3 5 r = CF (mif MItab06) 3 5 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_3_6 : ∀ r : Fin 9, getT Gtab06 3 6 r = CF (mif MItab06) 3 6 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_3_7 : ∀ r : Fin 9, getT Gtab06 3 7 r = CF (mif MItab06) 3 7 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_3_8 : ∀ r : Fin 9, getT Gtab06 3 8 r = CF (mif MItab06) 3 8 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_4_0 : ∀ r : Fin 9, getT Gtab06 4 0 r = CF (mif MItab06) 4 0 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_4_1 : ∀ r : Fin 9, getT Gtab06 4 1 r = CF (mif MItab06) 4 1 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_4_2 : ∀ r : Fin 9, getT Gtab06 4 2 r = CF (mif MItab06) 4 2 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_4_3 : ∀ r : Fin 9, getT Gtab06 4 3 r = CF (mif MItab06) 4 3 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_4_4 : ∀ r : Fin 9, getT Gtab06 4 4 r = CF (mif MItab06) 4 4 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_4_5 : ∀ r : Fin 9, getT Gtab06 4 5 r = CF (mif MItab06) 4 5 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_4_6 : ∀ r : Fin 9, getT Gtab06 4 6 r = CF (mif MItab06) 4 6 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_4_7 : ∀ r : Fin 9, getT Gtab06 4 7 r = CF (mif MItab06) 4 7 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_4_8 : ∀ r : Fin 9, getT Gtab06 4 8 r = CF (mif MItab06) 4 8 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_5_0 : ∀ r : Fin 9, getT Gtab06 5 0 r = CF (mif MItab06) 5 0 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_5_1 : ∀ r : Fin 9, getT Gtab06 5 1 r = CF (mif MItab06) 5 1 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_5_2 : ∀ r : Fin 9, getT Gtab06 5 2 r = CF (mif MItab06) 5 2 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_5_3 : ∀ r : Fin 9, getT Gtab06 5 3 r = CF (mif MItab06) 5 3 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_5_4 : ∀ r : Fin 9, getT Gtab06 5 4 r = CF (mif MItab06) 5 4 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_5_5 : ∀ r : Fin 9, getT Gtab06 5 5 r = CF (mif MItab06) 5 5 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_5_6 : ∀ r : Fin 9, getT Gtab06 5 6 r = CF (mif MItab06) 5 6 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_5_7 : ∀ r : Fin 9, getT Gtab06 5 7 r = CF (mif MItab06) 5 7 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_5_8 : ∀ r : Fin 9, getT Gtab06 5 8 r = CF (mif MItab06) 5 8 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_6_0 : ∀ r : Fin 9, getT Gtab06 6 0 r = CF (mif MItab06) 6 0 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_6_1 : ∀ r : Fin 9, getT Gtab06 6 1 r = CF (mif MItab06) 6 1 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_6_2 : ∀ r : Fin 9, getT Gtab06 6 2 r = CF (mif MItab06) 6 2 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_6_3 : ∀ r : Fin 9, getT Gtab06 6 3 r = CF (mif MItab06) 6 3 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_6_4 : ∀ r : Fin 9, getT Gtab06 6 4 r = CF (mif MItab06) 6 4 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_6_5 : ∀ r : Fin 9, getT Gtab06 6 5 r = CF (mif MItab06) 6 5 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_6_6 : ∀ r : Fin 9, getT Gtab06 6 6 r = CF (mif MItab06) 6 6 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_6_7 : ∀ r : Fin 9, getT Gtab06 6 7 r = CF (mif MItab06) 6 7 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_6_8 : ∀ r : Fin 9, getT Gtab06 6 8 r = CF (mif MItab06) 6 8 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_7_0 : ∀ r : Fin 9, getT Gtab06 7 0 r = CF (mif MItab06) 7 0 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_7_1 : ∀ r : Fin 9, getT Gtab06 7 1 r = CF (mif MItab06) 7 1 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_7_2 : ∀ r : Fin 9, getT Gtab06 7 2 r = CF (mif MItab06) 7 2 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_7_3 : ∀ r : Fin 9, getT Gtab06 7 3 r = CF (mif MItab06) 7 3 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_7_4 : ∀ r : Fin 9, getT Gtab06 7 4 r = CF (mif MItab06) 7 4 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_7_5 : ∀ r : Fin 9, getT Gtab06 7 5 r = CF (mif MItab06) 7 5 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_7_6 : ∀ r : Fin 9, getT Gtab06 7 6 r = CF (mif MItab06) 7 6 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_7_7 : ∀ r : Fin 9, getT Gtab06 7 7 r = CF (mif MItab06) 7 7 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_7_8 : ∀ r : Fin 9, getT Gtab06 7 8 r = CF (mif MItab06) 7 8 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_8_0 : ∀ r : Fin 9, getT Gtab06 8 0 r = CF (mif MItab06) 8 0 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_8_1 : ∀ r : Fin 9, getT Gtab06 8 1 r = CF (mif MItab06) 8 1 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_8_2 : ∀ r : Fin 9, getT Gtab06 8 2 r = CF (mif MItab06) 8 2 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_8_3 : ∀ r : Fin 9, getT Gtab06 8 3 r = CF (mif MItab06) 8 3 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_8_4 : ∀ r : Fin 9, getT Gtab06 8 4 r = CF (mif MItab06) 8 4 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_8_5 : ∀ r : Fin 9, getT Gtab06 8 5 r = CF (mif MItab06) 8 5 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_8_6 : ∀ r : Fin 9, getT Gtab06 8 6 r = CF (mif MItab06) 8 6 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_8_7 : ∀ r : Fin 9, getT Gtab06 8 7 r = CF (mif MItab06) 8 7 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab06_eq_8_8 : ∀ r : Fin 9, getT Gtab06 8 8 r = CF (mif MItab06) 8 8 r := by
  decide +kernel

theorem Gtab06_eq : ∀ p q r : Fin 9, getT Gtab06 p q r = CF (mif MItab06) p q r := by
  intro p q
  fin_cases p <;> fin_cases q
  exacts [Gtab06_eq_0_0,
    Gtab06_eq_0_1,
    Gtab06_eq_0_2,
    Gtab06_eq_0_3,
    Gtab06_eq_0_4,
    Gtab06_eq_0_5,
    Gtab06_eq_0_6,
    Gtab06_eq_0_7,
    Gtab06_eq_0_8,
    Gtab06_eq_1_0,
    Gtab06_eq_1_1,
    Gtab06_eq_1_2,
    Gtab06_eq_1_3,
    Gtab06_eq_1_4,
    Gtab06_eq_1_5,
    Gtab06_eq_1_6,
    Gtab06_eq_1_7,
    Gtab06_eq_1_8,
    Gtab06_eq_2_0,
    Gtab06_eq_2_1,
    Gtab06_eq_2_2,
    Gtab06_eq_2_3,
    Gtab06_eq_2_4,
    Gtab06_eq_2_5,
    Gtab06_eq_2_6,
    Gtab06_eq_2_7,
    Gtab06_eq_2_8,
    Gtab06_eq_3_0,
    Gtab06_eq_3_1,
    Gtab06_eq_3_2,
    Gtab06_eq_3_3,
    Gtab06_eq_3_4,
    Gtab06_eq_3_5,
    Gtab06_eq_3_6,
    Gtab06_eq_3_7,
    Gtab06_eq_3_8,
    Gtab06_eq_4_0,
    Gtab06_eq_4_1,
    Gtab06_eq_4_2,
    Gtab06_eq_4_3,
    Gtab06_eq_4_4,
    Gtab06_eq_4_5,
    Gtab06_eq_4_6,
    Gtab06_eq_4_7,
    Gtab06_eq_4_8,
    Gtab06_eq_5_0,
    Gtab06_eq_5_1,
    Gtab06_eq_5_2,
    Gtab06_eq_5_3,
    Gtab06_eq_5_4,
    Gtab06_eq_5_5,
    Gtab06_eq_5_6,
    Gtab06_eq_5_7,
    Gtab06_eq_5_8,
    Gtab06_eq_6_0,
    Gtab06_eq_6_1,
    Gtab06_eq_6_2,
    Gtab06_eq_6_3,
    Gtab06_eq_6_4,
    Gtab06_eq_6_5,
    Gtab06_eq_6_6,
    Gtab06_eq_6_7,
    Gtab06_eq_6_8,
    Gtab06_eq_7_0,
    Gtab06_eq_7_1,
    Gtab06_eq_7_2,
    Gtab06_eq_7_3,
    Gtab06_eq_7_4,
    Gtab06_eq_7_5,
    Gtab06_eq_7_6,
    Gtab06_eq_7_7,
    Gtab06_eq_7_8,
    Gtab06_eq_8_0,
    Gtab06_eq_8_1,
    Gtab06_eq_8_2,
    Gtab06_eq_8_3,
    Gtab06_eq_8_4,
    Gtab06_eq_8_5,
    Gtab06_eq_8_6,
    Gtab06_eq_8_7,
    Gtab06_eq_8_8]

/-- The 24 entries. -/
def col06 : List Itv :=
  [⟨-52269559633671254813470093052722846317588, -52269559633671254813470093052675694346976⟩,
    ⟨5427167232675843628102947697327866833703, 5427167232675843628102947697344324038567⟩,
    ⟨8343909567113222226227628172718393398401, 8343909567113222226227628172744384921815⟩,
    ⟨3265756550188839707387770760952565154149, 3265756550188839707387770760973402944536⟩,
    ⟨6535808517638472792407874523695889549973, 6535808517638472792407874523716032699230⟩,
    ⟨5095018773036780109973007820131420272978, 5095018773036780109973007820146962766602⟩,
    ⟨-2123181617019613347831106354230687399201, -2123181617019613347831106354176770005826⟩,
    ⟨-216657923610214925058464240713191484965575, -216657923610214925058464240712761968923940⟩,
    ⟨314785955888217006088016582307900966760, 314785955888217006088016582326377671144⟩,
    ⟨13745944525326437852088855253905347575100, 13745944525326437852088855254009122230054⟩,
    ⟨273907907249844813143181627388270544824, 273907907249844813143181627404526765451⟩,
    ⟨-522110919634645053072270226198023784305, -522110919634645053072270226186132315402⟩,
    ⟨31475604370473169234319261799977019336861, 31475604370473169234319261800052583733226⟩,
    ⟨-407983745760604435150476473166289957137, -407983745760604435150476473157043079170⟩,
    ⟨-372085991706175669513605631949925983074, -372085991706175669513605631941539295873⟩,
    ⟨22313429385332696207617178509340318581864, 22313429385332696207617178509393862087989⟩,
    ⟨-290741968816142803880543226827873361210, -290741968816142803880543226821351881500⟩,
    ⟨-353981891333109576349637738250145085215, -353981891333109576349637738242719086159⟩,
    ⟨-1386084414797860616124611786331846035249, -1386084414797860616124611786327525656390⟩,
    ⟨-627946212018406693037203727124353773333, -627946212018406693037203727121137783256⟩,
    ⟨-1243714607236585189289930359256545888273, -1243714607236585189289930359252722017307⟩,
    ⟨-1193196348975566189289785951987856134290, -1193196348975566189289785951984165597901⟩,
    ⟨-929074898166469699449714526435938671630, -929074898166469699449714526433098367806⟩,
    ⟨-1070393218536298988873635916998565227510, -1070393218536298988873635916995298243376⟩]

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col06_eq00 : col06.getD 0 Itv.zero = entAt (getT Gtab06) 0 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col06_eq01 : col06.getD 1 Itv.zero = entAt (getT Gtab06) 1 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col06_eq02 : col06.getD 2 Itv.zero = entAt (getT Gtab06) 2 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col06_eq03 : col06.getD 3 Itv.zero = entAt (getT Gtab06) 3 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col06_eq04 : col06.getD 4 Itv.zero = entAt (getT Gtab06) 4 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col06_eq05 : col06.getD 5 Itv.zero = entAt (getT Gtab06) 5 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col06_eq06 : col06.getD 6 Itv.zero = entAt (getT Gtab06) 6 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col06_eq07 : col06.getD 7 Itv.zero = entAt (getT Gtab06) 7 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col06_eq08 : col06.getD 8 Itv.zero = entAt (getT Gtab06) 8 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col06_eq09 : col06.getD 9 Itv.zero = entAt (getT Gtab06) 9 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col06_eq10 : col06.getD 10 Itv.zero = entAt (getT Gtab06) 10 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col06_eq11 : col06.getD 11 Itv.zero = entAt (getT Gtab06) 11 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col06_eq12 : col06.getD 12 Itv.zero = entAt (getT Gtab06) 12 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col06_eq13 : col06.getD 13 Itv.zero = entAt (getT Gtab06) 13 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col06_eq14 : col06.getD 14 Itv.zero = entAt (getT Gtab06) 14 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col06_eq15 : col06.getD 15 Itv.zero = entAt (getT Gtab06) 15 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col06_eq16 : col06.getD 16 Itv.zero = entAt (getT Gtab06) 16 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col06_eq17 : col06.getD 17 Itv.zero = entAt (getT Gtab06) 17 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col06_eq18 : col06.getD 18 Itv.zero = entAt (getT Gtab06) 18 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col06_eq19 : col06.getD 19 Itv.zero = entAt (getT Gtab06) 19 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col06_eq20 : col06.getD 20 Itv.zero = entAt (getT Gtab06) 20 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col06_eq21 : col06.getD 21 Itv.zero = entAt (getT Gtab06) 21 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col06_eq22 : col06.getD 22 Itv.zero = entAt (getT Gtab06) 22 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col06_eq23 : col06.getD 23 Itv.zero = entAt (getT Gtab06) 23 := by
  decide +kernel

theorem col06_eq : ∀ i : Fin 24, col06.getD (i : ℕ) Itv.zero = entAt (getT Gtab06) (i : ℕ) := by
  intro i
  fin_cases i
  exacts [col06_eq00,
    col06_eq01,
    col06_eq02,
    col06_eq03,
    col06_eq04,
    col06_eq05,
    col06_eq06,
    col06_eq07,
    col06_eq08,
    col06_eq09,
    col06_eq10,
    col06_eq11,
    col06_eq12,
    col06_eq13,
    col06_eq14,
    col06_eq15,
    col06_eq16,
    col06_eq17,
    col06_eq18,
    col06_eq19,
    col06_eq20,
    col06_eq21,
    col06_eq22,
    col06_eq23]

theorem ITMem_Gtab06 : ITMem (getT Gtab06) (cG 6) :=
  ITMem_getT_G MItab06_eq Gtab06_eq

theorem mem_col06 (i : Fin 24) : (col06.getD (i : ℕ) Itv.zero).Mem (pivotMatrix i 6) := by
  rw [col06_eq]; exact mem_entAt ITMem_Gtab06 i

end Thomson.Task1b
