-- GENERATED by Thomson/Pivots/gen/mk_tables.py; do not edit
import Thomson.Pivots.KBase

/-! # Task 1b: the tensor of `Gh 10`, and column 10 — GENERATED

Three literal tables, each checked against its definition by `decide +kernel` in pieces small
enough for the kernel's cache (see `KBase`): the blocks `M_k = B_k H_k B_kᵀ` of the indicator block of pivot 10,
three rows at a time; the coefficient tensor built from those blocks, one `(p, q)` row of nine
at a time; and the 24 entries of column 10 of the pivot system, one at a time. -/

namespace Thomson.Task1b

open Thomson Thomson.Tri5b

/-- The blocks `M_k`. -/
def MItab10 : ITab :=
  [[[⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨-9002041555693929052205642566516341075964, -9002041555693929052205642566474890545530⟩, ⟨0, 0⟩, ⟨-4312432991432733955164209156766181091252, -4312432991432733955164209156752726677269⟩, ⟨5646366307579387775329375638907279761123, 5646366307579387775329375638933267263231⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨-4312432991432733955164209156766181091252, -4312432991432733955164209156752726677269⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨5409789811760666652497772197679889803740, 5409789811760666652497772197696756773787⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨5646366307579387775329375638907279761123, 5646366307579387775329375638933267263231⟩, ⟨0, 0⟩, ⟨5409789811760666652497772197679889803740, 5409789811760666652497772197696756773787⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]]]

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab10_eq_0_0 : ∀ j : Fin (9 - ((0 : Fin 6) : ℕ)),
    mif MItab10 0 ⟨0, by omega⟩ j = MI BI (eHI 10) 0 ⟨0, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab10_eq_0_1 : ∀ j : Fin (9 - ((0 : Fin 6) : ℕ)),
    mif MItab10 0 ⟨1, by omega⟩ j = MI BI (eHI 10) 0 ⟨1, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab10_eq_0_2 : ∀ j : Fin (9 - ((0 : Fin 6) : ℕ)),
    mif MItab10 0 ⟨2, by omega⟩ j = MI BI (eHI 10) 0 ⟨2, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab10_eq_0_3 : ∀ j : Fin (9 - ((0 : Fin 6) : ℕ)),
    mif MItab10 0 ⟨3, by omega⟩ j = MI BI (eHI 10) 0 ⟨3, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab10_eq_0_4 : ∀ j : Fin (9 - ((0 : Fin 6) : ℕ)),
    mif MItab10 0 ⟨4, by omega⟩ j = MI BI (eHI 10) 0 ⟨4, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab10_eq_0_5 : ∀ j : Fin (9 - ((0 : Fin 6) : ℕ)),
    mif MItab10 0 ⟨5, by omega⟩ j = MI BI (eHI 10) 0 ⟨5, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab10_eq_0_6 : ∀ j : Fin (9 - ((0 : Fin 6) : ℕ)),
    mif MItab10 0 ⟨6, by omega⟩ j = MI BI (eHI 10) 0 ⟨6, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab10_eq_0_7 : ∀ j : Fin (9 - ((0 : Fin 6) : ℕ)),
    mif MItab10 0 ⟨7, by omega⟩ j = MI BI (eHI 10) 0 ⟨7, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab10_eq_0_8 : ∀ j : Fin (9 - ((0 : Fin 6) : ℕ)),
    mif MItab10 0 ⟨8, by omega⟩ j = MI BI (eHI 10) 0 ⟨8, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab10_eq_1_0 : ∀ j : Fin (9 - ((1 : Fin 6) : ℕ)),
    mif MItab10 1 ⟨0, by omega⟩ j = MI BI (eHI 10) 1 ⟨0, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab10_eq_1_1 : ∀ j : Fin (9 - ((1 : Fin 6) : ℕ)),
    mif MItab10 1 ⟨1, by omega⟩ j = MI BI (eHI 10) 1 ⟨1, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab10_eq_1_2 : ∀ j : Fin (9 - ((1 : Fin 6) : ℕ)),
    mif MItab10 1 ⟨2, by omega⟩ j = MI BI (eHI 10) 1 ⟨2, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab10_eq_1_3 : ∀ j : Fin (9 - ((1 : Fin 6) : ℕ)),
    mif MItab10 1 ⟨3, by omega⟩ j = MI BI (eHI 10) 1 ⟨3, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab10_eq_1_4 : ∀ j : Fin (9 - ((1 : Fin 6) : ℕ)),
    mif MItab10 1 ⟨4, by omega⟩ j = MI BI (eHI 10) 1 ⟨4, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab10_eq_1_5 : ∀ j : Fin (9 - ((1 : Fin 6) : ℕ)),
    mif MItab10 1 ⟨5, by omega⟩ j = MI BI (eHI 10) 1 ⟨5, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab10_eq_1_6 : ∀ j : Fin (9 - ((1 : Fin 6) : ℕ)),
    mif MItab10 1 ⟨6, by omega⟩ j = MI BI (eHI 10) 1 ⟨6, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab10_eq_1_7 : ∀ j : Fin (9 - ((1 : Fin 6) : ℕ)),
    mif MItab10 1 ⟨7, by omega⟩ j = MI BI (eHI 10) 1 ⟨7, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab10_eq_2_0 : ∀ j : Fin (9 - ((2 : Fin 6) : ℕ)),
    mif MItab10 2 ⟨0, by omega⟩ j = MI BI (eHI 10) 2 ⟨0, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab10_eq_2_1 : ∀ j : Fin (9 - ((2 : Fin 6) : ℕ)),
    mif MItab10 2 ⟨1, by omega⟩ j = MI BI (eHI 10) 2 ⟨1, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab10_eq_2_2 : ∀ j : Fin (9 - ((2 : Fin 6) : ℕ)),
    mif MItab10 2 ⟨2, by omega⟩ j = MI BI (eHI 10) 2 ⟨2, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab10_eq_2_3 : ∀ j : Fin (9 - ((2 : Fin 6) : ℕ)),
    mif MItab10 2 ⟨3, by omega⟩ j = MI BI (eHI 10) 2 ⟨3, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab10_eq_2_4 : ∀ j : Fin (9 - ((2 : Fin 6) : ℕ)),
    mif MItab10 2 ⟨4, by omega⟩ j = MI BI (eHI 10) 2 ⟨4, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab10_eq_2_5 : ∀ j : Fin (9 - ((2 : Fin 6) : ℕ)),
    mif MItab10 2 ⟨5, by omega⟩ j = MI BI (eHI 10) 2 ⟨5, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab10_eq_2_6 : ∀ j : Fin (9 - ((2 : Fin 6) : ℕ)),
    mif MItab10 2 ⟨6, by omega⟩ j = MI BI (eHI 10) 2 ⟨6, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab10_eq_3_0 : ∀ j : Fin (9 - ((3 : Fin 6) : ℕ)),
    mif MItab10 3 ⟨0, by omega⟩ j = MI BI (eHI 10) 3 ⟨0, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab10_eq_3_1 : ∀ j : Fin (9 - ((3 : Fin 6) : ℕ)),
    mif MItab10 3 ⟨1, by omega⟩ j = MI BI (eHI 10) 3 ⟨1, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab10_eq_3_2 : ∀ j : Fin (9 - ((3 : Fin 6) : ℕ)),
    mif MItab10 3 ⟨2, by omega⟩ j = MI BI (eHI 10) 3 ⟨2, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab10_eq_3_3 : ∀ j : Fin (9 - ((3 : Fin 6) : ℕ)),
    mif MItab10 3 ⟨3, by omega⟩ j = MI BI (eHI 10) 3 ⟨3, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab10_eq_3_4 : ∀ j : Fin (9 - ((3 : Fin 6) : ℕ)),
    mif MItab10 3 ⟨4, by omega⟩ j = MI BI (eHI 10) 3 ⟨4, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab10_eq_3_5 : ∀ j : Fin (9 - ((3 : Fin 6) : ℕ)),
    mif MItab10 3 ⟨5, by omega⟩ j = MI BI (eHI 10) 3 ⟨5, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab10_eq_4_0 : ∀ j : Fin (9 - ((4 : Fin 6) : ℕ)),
    mif MItab10 4 ⟨0, by omega⟩ j = MI BI (eHI 10) 4 ⟨0, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab10_eq_4_1 : ∀ j : Fin (9 - ((4 : Fin 6) : ℕ)),
    mif MItab10 4 ⟨1, by omega⟩ j = MI BI (eHI 10) 4 ⟨1, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab10_eq_4_2 : ∀ j : Fin (9 - ((4 : Fin 6) : ℕ)),
    mif MItab10 4 ⟨2, by omega⟩ j = MI BI (eHI 10) 4 ⟨2, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab10_eq_4_3 : ∀ j : Fin (9 - ((4 : Fin 6) : ℕ)),
    mif MItab10 4 ⟨3, by omega⟩ j = MI BI (eHI 10) 4 ⟨3, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab10_eq_4_4 : ∀ j : Fin (9 - ((4 : Fin 6) : ℕ)),
    mif MItab10 4 ⟨4, by omega⟩ j = MI BI (eHI 10) 4 ⟨4, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab10_eq_5_0 : ∀ j : Fin (9 - ((5 : Fin 6) : ℕ)),
    mif MItab10 5 ⟨0, by omega⟩ j = MI BI (eHI 10) 5 ⟨0, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab10_eq_5_1 : ∀ j : Fin (9 - ((5 : Fin 6) : ℕ)),
    mif MItab10 5 ⟨1, by omega⟩ j = MI BI (eHI 10) 5 ⟨1, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab10_eq_5_2 : ∀ j : Fin (9 - ((5 : Fin 6) : ℕ)),
    mif MItab10 5 ⟨2, by omega⟩ j = MI BI (eHI 10) 5 ⟨2, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab10_eq_5_3 : ∀ j : Fin (9 - ((5 : Fin 6) : ℕ)),
    mif MItab10 5 ⟨3, by omega⟩ j = MI BI (eHI 10) 5 ⟨3, by omega⟩ j := by
  decide +kernel

theorem MItab10_eq : ∀ (k : Fin 6) (i j : Fin (9 - (k : ℕ))),
    mif MItab10 k i j = MI BI (eHI 10) k i j := by
  intro k i
  fin_cases k <;> fin_cases i
  exacts [MItab10_eq_0_0,
    MItab10_eq_0_1,
    MItab10_eq_0_2,
    MItab10_eq_0_3,
    MItab10_eq_0_4,
    MItab10_eq_0_5,
    MItab10_eq_0_6,
    MItab10_eq_0_7,
    MItab10_eq_0_8,
    MItab10_eq_1_0,
    MItab10_eq_1_1,
    MItab10_eq_1_2,
    MItab10_eq_1_3,
    MItab10_eq_1_4,
    MItab10_eq_1_5,
    MItab10_eq_1_6,
    MItab10_eq_1_7,
    MItab10_eq_2_0,
    MItab10_eq_2_1,
    MItab10_eq_2_2,
    MItab10_eq_2_3,
    MItab10_eq_2_4,
    MItab10_eq_2_5,
    MItab10_eq_2_6,
    MItab10_eq_3_0,
    MItab10_eq_3_1,
    MItab10_eq_3_2,
    MItab10_eq_3_3,
    MItab10_eq_3_4,
    MItab10_eq_3_5,
    MItab10_eq_4_0,
    MItab10_eq_4_1,
    MItab10_eq_4_2,
    MItab10_eq_4_3,
    MItab10_eq_4_4,
    MItab10_eq_5_0,
    MItab10_eq_5_1,
    MItab10_eq_5_2,
    MItab10_eq_5_3]

/-- The coefficient tensor. -/
def Gtab10 : ITab :=
  [[[⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨3000680518564643017401880855491630181843, 3000680518564643017401880855505447025322⟩, ⟨0, 0⟩, ⟨1437477663810911318388069718917575559089, 1437477663810911318388069718922060363751⟩, ⟨-1882122102526462591776458546311089087745, -1882122102526462591776458546302426587040⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨1437477663810911318388069718917575559089, 1437477663810911318388069718922060363751⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨-1803263270586888884165924065898918924597, -1803263270586888884165924065893296601246⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨-1882122102526462591776458546311089087745, -1882122102526462591776458546302426587040⟩, ⟨0, 0⟩, ⟨-1803263270586888884165924065898918924597, -1803263270586888884165924065893296601246⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨-9002041555693929052205642566516341075966, -9002041555693929052205642566474890545529⟩, ⟨0, 0⟩, ⟨-2874955327621822636776139437844120727502, -2874955327621822636776139437835151118179⟩, ⟨3764244205052925183552917092604853174081, 3764244205052925183552917092622178175489⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨-2874955327621822636776139437844120727502, -2874955327621822636776139437835151118179⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨1803263270586888884165924065893296601246, 1803263270586888884165924065898918924597⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨3764244205052925183552917092604853174081, 3764244205052925183552917092622178175489⟩, ⟨0, 0⟩, ⟨1803263270586888884165924065893296601246, 1803263270586888884165924065898918924597⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨0, 0⟩, ⟨0, 0⟩, ⟨3000680518564643017401880855491630181843, 3000680518564643017401880855505447025322⟩, ⟨0, 0⟩, ⟨1437477663810911318388069718917575559089, 1437477663810911318388069718922060363751⟩, ⟨-1882122102526462591776458546311089087745, -1882122102526462591776458546302426587040⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨3000680518564643017401880855491630181843, 3000680518564643017401880855505447025322⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨1437477663810911318388069718917575559089, 1437477663810911318388069718922060363751⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨-1882122102526462591776458546311089087745, -1882122102526462591776458546302426587040⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨-2874955327621822636776139437844120727502, -2874955327621822636776139437835151118179⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨1803263270586888884165924065893296601246, 1803263270586888884165924065898918924597⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨1803263270586888884165924065893296601246, 1803263270586888884165924065898918924597⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨0, 0⟩, ⟨0, 0⟩, ⟨1437477663810911318388069718917575559089, 1437477663810911318388069718922060363751⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨-1803263270586888884165924065898918924597, -1803263270586888884165924065893296601246⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨3764244205052925183552917092604853174081, 3764244205052925183552917092622178175489⟩, ⟨0, 0⟩, ⟨1803263270586888884165924065893296601246, 1803263270586888884165924065898918924597⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨1437477663810911318388069718917575559089, 1437477663810911318388069718922060363751⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨1803263270586888884165924065893296601246, 1803263270586888884165924065898918924597⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨-1803263270586888884165924065898918924597, -1803263270586888884165924065893296601246⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨0, 0⟩, ⟨0, 0⟩, ⟨-1882122102526462591776458546311089087745, -1882122102526462591776458546302426587040⟩, ⟨0, 0⟩, ⟨-1803263270586888884165924065898918924597, -1803263270586888884165924065893296601246⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨-1882122102526462591776458546311089087745, -1882122102526462591776458546302426587040⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨-1803263270586888884165924065898918924597, -1803263270586888884165924065893296601246⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]]]

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_0_0 : ∀ r : Fin 9, getT Gtab10 0 0 r = CF (mif MItab10) 0 0 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_0_1 : ∀ r : Fin 9, getT Gtab10 0 1 r = CF (mif MItab10) 0 1 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_0_2 : ∀ r : Fin 9, getT Gtab10 0 2 r = CF (mif MItab10) 0 2 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_0_3 : ∀ r : Fin 9, getT Gtab10 0 3 r = CF (mif MItab10) 0 3 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_0_4 : ∀ r : Fin 9, getT Gtab10 0 4 r = CF (mif MItab10) 0 4 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_0_5 : ∀ r : Fin 9, getT Gtab10 0 5 r = CF (mif MItab10) 0 5 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_0_6 : ∀ r : Fin 9, getT Gtab10 0 6 r = CF (mif MItab10) 0 6 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_0_7 : ∀ r : Fin 9, getT Gtab10 0 7 r = CF (mif MItab10) 0 7 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_0_8 : ∀ r : Fin 9, getT Gtab10 0 8 r = CF (mif MItab10) 0 8 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_1_0 : ∀ r : Fin 9, getT Gtab10 1 0 r = CF (mif MItab10) 1 0 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_1_1 : ∀ r : Fin 9, getT Gtab10 1 1 r = CF (mif MItab10) 1 1 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_1_2 : ∀ r : Fin 9, getT Gtab10 1 2 r = CF (mif MItab10) 1 2 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_1_3 : ∀ r : Fin 9, getT Gtab10 1 3 r = CF (mif MItab10) 1 3 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_1_4 : ∀ r : Fin 9, getT Gtab10 1 4 r = CF (mif MItab10) 1 4 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_1_5 : ∀ r : Fin 9, getT Gtab10 1 5 r = CF (mif MItab10) 1 5 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_1_6 : ∀ r : Fin 9, getT Gtab10 1 6 r = CF (mif MItab10) 1 6 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_1_7 : ∀ r : Fin 9, getT Gtab10 1 7 r = CF (mif MItab10) 1 7 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_1_8 : ∀ r : Fin 9, getT Gtab10 1 8 r = CF (mif MItab10) 1 8 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_2_0 : ∀ r : Fin 9, getT Gtab10 2 0 r = CF (mif MItab10) 2 0 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_2_1 : ∀ r : Fin 9, getT Gtab10 2 1 r = CF (mif MItab10) 2 1 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_2_2 : ∀ r : Fin 9, getT Gtab10 2 2 r = CF (mif MItab10) 2 2 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_2_3 : ∀ r : Fin 9, getT Gtab10 2 3 r = CF (mif MItab10) 2 3 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_2_4 : ∀ r : Fin 9, getT Gtab10 2 4 r = CF (mif MItab10) 2 4 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_2_5 : ∀ r : Fin 9, getT Gtab10 2 5 r = CF (mif MItab10) 2 5 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_2_6 : ∀ r : Fin 9, getT Gtab10 2 6 r = CF (mif MItab10) 2 6 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_2_7 : ∀ r : Fin 9, getT Gtab10 2 7 r = CF (mif MItab10) 2 7 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_2_8 : ∀ r : Fin 9, getT Gtab10 2 8 r = CF (mif MItab10) 2 8 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_3_0 : ∀ r : Fin 9, getT Gtab10 3 0 r = CF (mif MItab10) 3 0 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_3_1 : ∀ r : Fin 9, getT Gtab10 3 1 r = CF (mif MItab10) 3 1 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_3_2 : ∀ r : Fin 9, getT Gtab10 3 2 r = CF (mif MItab10) 3 2 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_3_3 : ∀ r : Fin 9, getT Gtab10 3 3 r = CF (mif MItab10) 3 3 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_3_4 : ∀ r : Fin 9, getT Gtab10 3 4 r = CF (mif MItab10) 3 4 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_3_5 : ∀ r : Fin 9, getT Gtab10 3 5 r = CF (mif MItab10) 3 5 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_3_6 : ∀ r : Fin 9, getT Gtab10 3 6 r = CF (mif MItab10) 3 6 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_3_7 : ∀ r : Fin 9, getT Gtab10 3 7 r = CF (mif MItab10) 3 7 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_3_8 : ∀ r : Fin 9, getT Gtab10 3 8 r = CF (mif MItab10) 3 8 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_4_0 : ∀ r : Fin 9, getT Gtab10 4 0 r = CF (mif MItab10) 4 0 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_4_1 : ∀ r : Fin 9, getT Gtab10 4 1 r = CF (mif MItab10) 4 1 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_4_2 : ∀ r : Fin 9, getT Gtab10 4 2 r = CF (mif MItab10) 4 2 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_4_3 : ∀ r : Fin 9, getT Gtab10 4 3 r = CF (mif MItab10) 4 3 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_4_4 : ∀ r : Fin 9, getT Gtab10 4 4 r = CF (mif MItab10) 4 4 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_4_5 : ∀ r : Fin 9, getT Gtab10 4 5 r = CF (mif MItab10) 4 5 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_4_6 : ∀ r : Fin 9, getT Gtab10 4 6 r = CF (mif MItab10) 4 6 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_4_7 : ∀ r : Fin 9, getT Gtab10 4 7 r = CF (mif MItab10) 4 7 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_4_8 : ∀ r : Fin 9, getT Gtab10 4 8 r = CF (mif MItab10) 4 8 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_5_0 : ∀ r : Fin 9, getT Gtab10 5 0 r = CF (mif MItab10) 5 0 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_5_1 : ∀ r : Fin 9, getT Gtab10 5 1 r = CF (mif MItab10) 5 1 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_5_2 : ∀ r : Fin 9, getT Gtab10 5 2 r = CF (mif MItab10) 5 2 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_5_3 : ∀ r : Fin 9, getT Gtab10 5 3 r = CF (mif MItab10) 5 3 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_5_4 : ∀ r : Fin 9, getT Gtab10 5 4 r = CF (mif MItab10) 5 4 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_5_5 : ∀ r : Fin 9, getT Gtab10 5 5 r = CF (mif MItab10) 5 5 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_5_6 : ∀ r : Fin 9, getT Gtab10 5 6 r = CF (mif MItab10) 5 6 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_5_7 : ∀ r : Fin 9, getT Gtab10 5 7 r = CF (mif MItab10) 5 7 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_5_8 : ∀ r : Fin 9, getT Gtab10 5 8 r = CF (mif MItab10) 5 8 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_6_0 : ∀ r : Fin 9, getT Gtab10 6 0 r = CF (mif MItab10) 6 0 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_6_1 : ∀ r : Fin 9, getT Gtab10 6 1 r = CF (mif MItab10) 6 1 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_6_2 : ∀ r : Fin 9, getT Gtab10 6 2 r = CF (mif MItab10) 6 2 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_6_3 : ∀ r : Fin 9, getT Gtab10 6 3 r = CF (mif MItab10) 6 3 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_6_4 : ∀ r : Fin 9, getT Gtab10 6 4 r = CF (mif MItab10) 6 4 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_6_5 : ∀ r : Fin 9, getT Gtab10 6 5 r = CF (mif MItab10) 6 5 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_6_6 : ∀ r : Fin 9, getT Gtab10 6 6 r = CF (mif MItab10) 6 6 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_6_7 : ∀ r : Fin 9, getT Gtab10 6 7 r = CF (mif MItab10) 6 7 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_6_8 : ∀ r : Fin 9, getT Gtab10 6 8 r = CF (mif MItab10) 6 8 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_7_0 : ∀ r : Fin 9, getT Gtab10 7 0 r = CF (mif MItab10) 7 0 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_7_1 : ∀ r : Fin 9, getT Gtab10 7 1 r = CF (mif MItab10) 7 1 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_7_2 : ∀ r : Fin 9, getT Gtab10 7 2 r = CF (mif MItab10) 7 2 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_7_3 : ∀ r : Fin 9, getT Gtab10 7 3 r = CF (mif MItab10) 7 3 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_7_4 : ∀ r : Fin 9, getT Gtab10 7 4 r = CF (mif MItab10) 7 4 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_7_5 : ∀ r : Fin 9, getT Gtab10 7 5 r = CF (mif MItab10) 7 5 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_7_6 : ∀ r : Fin 9, getT Gtab10 7 6 r = CF (mif MItab10) 7 6 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_7_7 : ∀ r : Fin 9, getT Gtab10 7 7 r = CF (mif MItab10) 7 7 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_7_8 : ∀ r : Fin 9, getT Gtab10 7 8 r = CF (mif MItab10) 7 8 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_8_0 : ∀ r : Fin 9, getT Gtab10 8 0 r = CF (mif MItab10) 8 0 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_8_1 : ∀ r : Fin 9, getT Gtab10 8 1 r = CF (mif MItab10) 8 1 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_8_2 : ∀ r : Fin 9, getT Gtab10 8 2 r = CF (mif MItab10) 8 2 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_8_3 : ∀ r : Fin 9, getT Gtab10 8 3 r = CF (mif MItab10) 8 3 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_8_4 : ∀ r : Fin 9, getT Gtab10 8 4 r = CF (mif MItab10) 8 4 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_8_5 : ∀ r : Fin 9, getT Gtab10 8 5 r = CF (mif MItab10) 8 5 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_8_6 : ∀ r : Fin 9, getT Gtab10 8 6 r = CF (mif MItab10) 8 6 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_8_7 : ∀ r : Fin 9, getT Gtab10 8 7 r = CF (mif MItab10) 8 7 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab10_eq_8_8 : ∀ r : Fin 9, getT Gtab10 8 8 r = CF (mif MItab10) 8 8 r := by
  decide +kernel

theorem Gtab10_eq : ∀ p q r : Fin 9, getT Gtab10 p q r = CF (mif MItab10) p q r := by
  intro p q
  fin_cases p <;> fin_cases q
  exacts [Gtab10_eq_0_0,
    Gtab10_eq_0_1,
    Gtab10_eq_0_2,
    Gtab10_eq_0_3,
    Gtab10_eq_0_4,
    Gtab10_eq_0_5,
    Gtab10_eq_0_6,
    Gtab10_eq_0_7,
    Gtab10_eq_0_8,
    Gtab10_eq_1_0,
    Gtab10_eq_1_1,
    Gtab10_eq_1_2,
    Gtab10_eq_1_3,
    Gtab10_eq_1_4,
    Gtab10_eq_1_5,
    Gtab10_eq_1_6,
    Gtab10_eq_1_7,
    Gtab10_eq_1_8,
    Gtab10_eq_2_0,
    Gtab10_eq_2_1,
    Gtab10_eq_2_2,
    Gtab10_eq_2_3,
    Gtab10_eq_2_4,
    Gtab10_eq_2_5,
    Gtab10_eq_2_6,
    Gtab10_eq_2_7,
    Gtab10_eq_2_8,
    Gtab10_eq_3_0,
    Gtab10_eq_3_1,
    Gtab10_eq_3_2,
    Gtab10_eq_3_3,
    Gtab10_eq_3_4,
    Gtab10_eq_3_5,
    Gtab10_eq_3_6,
    Gtab10_eq_3_7,
    Gtab10_eq_3_8,
    Gtab10_eq_4_0,
    Gtab10_eq_4_1,
    Gtab10_eq_4_2,
    Gtab10_eq_4_3,
    Gtab10_eq_4_4,
    Gtab10_eq_4_5,
    Gtab10_eq_4_6,
    Gtab10_eq_4_7,
    Gtab10_eq_4_8,
    Gtab10_eq_5_0,
    Gtab10_eq_5_1,
    Gtab10_eq_5_2,
    Gtab10_eq_5_3,
    Gtab10_eq_5_4,
    Gtab10_eq_5_5,
    Gtab10_eq_5_6,
    Gtab10_eq_5_7,
    Gtab10_eq_5_8,
    Gtab10_eq_6_0,
    Gtab10_eq_6_1,
    Gtab10_eq_6_2,
    Gtab10_eq_6_3,
    Gtab10_eq_6_4,
    Gtab10_eq_6_5,
    Gtab10_eq_6_6,
    Gtab10_eq_6_7,
    Gtab10_eq_6_8,
    Gtab10_eq_7_0,
    Gtab10_eq_7_1,
    Gtab10_eq_7_2,
    Gtab10_eq_7_3,
    Gtab10_eq_7_4,
    Gtab10_eq_7_5,
    Gtab10_eq_7_6,
    Gtab10_eq_7_7,
    Gtab10_eq_7_8,
    Gtab10_eq_8_0,
    Gtab10_eq_8_1,
    Gtab10_eq_8_2,
    Gtab10_eq_8_3,
    Gtab10_eq_8_4,
    Gtab10_eq_8_5,
    Gtab10_eq_8_6,
    Gtab10_eq_8_7,
    Gtab10_eq_8_8]

/-- The 24 entries. -/
def col10 : List Itv :=
  [⟨-616273210956, 616273210968⟩,
    ⟨-5897476296150957239993486919838455003757, -5897476296150957239993486919415440609043⟩,
    ⟨2141489464604934204212238516500923672932, 2141489464604934204212238516602334077559⟩,
    ⟨21277176713786393975532696171412458576490, 21277176713786393975532696172453230413900⟩,
    ⟨335843011749439530565751861460091646854, 335843011749439530565751861476607105723⟩,
    ⟨-4737176382083954396622172282478135921833, -4737176382083954396622172282229239296323⟩,
    ⟨10418615221973485936109691033150768021273, 10418615221973485936109691033996485782284⟩,
    ⟨15299939312075059974071147736019370487113, 15299939312075059974071147743004228550291⟩,
    ⟨-1108574054459230590942401705346894963782, -1108574054459230590942401705198488290666⟩,
    ⟨-44673527170939732080565337563312807907243, -44673527170939732080565337562479709766860⟩,
    ⟨-38502864612780753949202669729297798543860, -38502864612780753949202669728783760093004⟩,
    ⟨457777410864969457859838177985431965244, 457777410864969457859838178011480384788⟩,
    ⟨-4373879951067991280208642588612617569901, -4373879951067991280208642588463352632532⟩,
    ⟨-14476513040879439988466322980692466094595, -14476513040879439988466322980535651751491⟩,
    ⟨-2796683741641953295039637003792370228108, -2796683741641953295039637003777642738581⟩,
    ⟨-16361242263663916483213886618777279161160, -16361242263663916483213886618693676153879⟩,
    ⟨14433505461082591427275332535863439768711, 14433505461082591427275332535958722308011⟩,
    ⟨10784048607895982199483639584979402238730, 10784048607895982199483639585062502812482⟩,
    ⟨-1106097248250870191488996722081046952490, -1106097248250870191488996722075091819783⟩,
    ⟨-6930636606165889647351995908331660869925, -6930636606165889647351995908295665489105⟩,
    ⟨3516749119692119717710076543829929771497, 3516749119692119717710076543859900354267⟩,
    ⟨125679588214637952567733654819830925077, 125679588214637952567733654821017573057⟩,
    ⟨-822188295396183312721835779913269268256, -822188295396183312721835779903577021601⟩,
    ⟨-259599167563614987952481920292166752077, -259599167563614987952481920285829340249⟩]

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col10_eq00 : col10.getD 0 Itv.zero = entAt (getT Gtab10) 0 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col10_eq01 : col10.getD 1 Itv.zero = entAt (getT Gtab10) 1 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col10_eq02 : col10.getD 2 Itv.zero = entAt (getT Gtab10) 2 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col10_eq03 : col10.getD 3 Itv.zero = entAt (getT Gtab10) 3 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col10_eq04 : col10.getD 4 Itv.zero = entAt (getT Gtab10) 4 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col10_eq05 : col10.getD 5 Itv.zero = entAt (getT Gtab10) 5 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col10_eq06 : col10.getD 6 Itv.zero = entAt (getT Gtab10) 6 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col10_eq07 : col10.getD 7 Itv.zero = entAt (getT Gtab10) 7 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col10_eq08 : col10.getD 8 Itv.zero = entAt (getT Gtab10) 8 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col10_eq09 : col10.getD 9 Itv.zero = entAt (getT Gtab10) 9 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col10_eq10 : col10.getD 10 Itv.zero = entAt (getT Gtab10) 10 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col10_eq11 : col10.getD 11 Itv.zero = entAt (getT Gtab10) 11 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col10_eq12 : col10.getD 12 Itv.zero = entAt (getT Gtab10) 12 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col10_eq13 : col10.getD 13 Itv.zero = entAt (getT Gtab10) 13 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col10_eq14 : col10.getD 14 Itv.zero = entAt (getT Gtab10) 14 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col10_eq15 : col10.getD 15 Itv.zero = entAt (getT Gtab10) 15 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col10_eq16 : col10.getD 16 Itv.zero = entAt (getT Gtab10) 16 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col10_eq17 : col10.getD 17 Itv.zero = entAt (getT Gtab10) 17 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col10_eq18 : col10.getD 18 Itv.zero = entAt (getT Gtab10) 18 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col10_eq19 : col10.getD 19 Itv.zero = entAt (getT Gtab10) 19 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col10_eq20 : col10.getD 20 Itv.zero = entAt (getT Gtab10) 20 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col10_eq21 : col10.getD 21 Itv.zero = entAt (getT Gtab10) 21 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col10_eq22 : col10.getD 22 Itv.zero = entAt (getT Gtab10) 22 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col10_eq23 : col10.getD 23 Itv.zero = entAt (getT Gtab10) 23 := by
  decide +kernel

theorem col10_eq : ∀ i : Fin 24, col10.getD (i : ℕ) Itv.zero = entAt (getT Gtab10) (i : ℕ) := by
  intro i
  fin_cases i
  exacts [col10_eq00,
    col10_eq01,
    col10_eq02,
    col10_eq03,
    col10_eq04,
    col10_eq05,
    col10_eq06,
    col10_eq07,
    col10_eq08,
    col10_eq09,
    col10_eq10,
    col10_eq11,
    col10_eq12,
    col10_eq13,
    col10_eq14,
    col10_eq15,
    col10_eq16,
    col10_eq17,
    col10_eq18,
    col10_eq19,
    col10_eq20,
    col10_eq21,
    col10_eq22,
    col10_eq23]

theorem ITMem_Gtab10 : ITMem (getT Gtab10) (cG 10) :=
  ITMem_getT_G MItab10_eq Gtab10_eq

theorem mem_col10 (i : Fin 24) : (col10.getD (i : ℕ) Itv.zero).Mem (pivotMatrix i 10) := by
  rw [col10_eq]; exact mem_entAt ITMem_Gtab10 i

end Thomson.Task1b
