-- GENERATED by Thomson/Pivots/gen/mk_tables.py; do not edit
import Thomson.Pivots.KBase

/-! # Task 1b: the tensor of `Gh 15`, and column 15 — GENERATED

Three literal tables, each checked against its definition by `decide +kernel` in pieces small
enough for the kernel's cache (see `KBase`): the blocks `M_k = B_k H_k B_kᵀ` of the indicator block of pivot 15,
three rows at a time; the coefficient tensor built from those blocks, one `(p, q)` row of nine
at a time; and the 24 entries of column 15 of the pivot system, one at a time. -/

namespace Thomson.Task1b

open Thomson Thomson.Tri5b

/-- The blocks `M_k`. -/
def MItab15 : ITab :=
  [[[⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨10000000000000000000000000000000000000000, 10000000000000000000000000000000000000000⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]]]

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab15_eq_0_0 : ∀ j : Fin (9 - ((0 : Fin 6) : ℕ)),
    mif MItab15 0 ⟨0, by omega⟩ j = MI BI (eHI 15) 0 ⟨0, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab15_eq_0_1 : ∀ j : Fin (9 - ((0 : Fin 6) : ℕ)),
    mif MItab15 0 ⟨1, by omega⟩ j = MI BI (eHI 15) 0 ⟨1, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab15_eq_0_2 : ∀ j : Fin (9 - ((0 : Fin 6) : ℕ)),
    mif MItab15 0 ⟨2, by omega⟩ j = MI BI (eHI 15) 0 ⟨2, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab15_eq_0_3 : ∀ j : Fin (9 - ((0 : Fin 6) : ℕ)),
    mif MItab15 0 ⟨3, by omega⟩ j = MI BI (eHI 15) 0 ⟨3, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab15_eq_0_4 : ∀ j : Fin (9 - ((0 : Fin 6) : ℕ)),
    mif MItab15 0 ⟨4, by omega⟩ j = MI BI (eHI 15) 0 ⟨4, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab15_eq_0_5 : ∀ j : Fin (9 - ((0 : Fin 6) : ℕ)),
    mif MItab15 0 ⟨5, by omega⟩ j = MI BI (eHI 15) 0 ⟨5, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab15_eq_0_6 : ∀ j : Fin (9 - ((0 : Fin 6) : ℕ)),
    mif MItab15 0 ⟨6, by omega⟩ j = MI BI (eHI 15) 0 ⟨6, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab15_eq_0_7 : ∀ j : Fin (9 - ((0 : Fin 6) : ℕ)),
    mif MItab15 0 ⟨7, by omega⟩ j = MI BI (eHI 15) 0 ⟨7, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab15_eq_0_8 : ∀ j : Fin (9 - ((0 : Fin 6) : ℕ)),
    mif MItab15 0 ⟨8, by omega⟩ j = MI BI (eHI 15) 0 ⟨8, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab15_eq_1_0 : ∀ j : Fin (9 - ((1 : Fin 6) : ℕ)),
    mif MItab15 1 ⟨0, by omega⟩ j = MI BI (eHI 15) 1 ⟨0, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab15_eq_1_1 : ∀ j : Fin (9 - ((1 : Fin 6) : ℕ)),
    mif MItab15 1 ⟨1, by omega⟩ j = MI BI (eHI 15) 1 ⟨1, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab15_eq_1_2 : ∀ j : Fin (9 - ((1 : Fin 6) : ℕ)),
    mif MItab15 1 ⟨2, by omega⟩ j = MI BI (eHI 15) 1 ⟨2, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab15_eq_1_3 : ∀ j : Fin (9 - ((1 : Fin 6) : ℕ)),
    mif MItab15 1 ⟨3, by omega⟩ j = MI BI (eHI 15) 1 ⟨3, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab15_eq_1_4 : ∀ j : Fin (9 - ((1 : Fin 6) : ℕ)),
    mif MItab15 1 ⟨4, by omega⟩ j = MI BI (eHI 15) 1 ⟨4, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab15_eq_1_5 : ∀ j : Fin (9 - ((1 : Fin 6) : ℕ)),
    mif MItab15 1 ⟨5, by omega⟩ j = MI BI (eHI 15) 1 ⟨5, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab15_eq_1_6 : ∀ j : Fin (9 - ((1 : Fin 6) : ℕ)),
    mif MItab15 1 ⟨6, by omega⟩ j = MI BI (eHI 15) 1 ⟨6, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab15_eq_1_7 : ∀ j : Fin (9 - ((1 : Fin 6) : ℕ)),
    mif MItab15 1 ⟨7, by omega⟩ j = MI BI (eHI 15) 1 ⟨7, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab15_eq_2_0 : ∀ j : Fin (9 - ((2 : Fin 6) : ℕ)),
    mif MItab15 2 ⟨0, by omega⟩ j = MI BI (eHI 15) 2 ⟨0, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab15_eq_2_1 : ∀ j : Fin (9 - ((2 : Fin 6) : ℕ)),
    mif MItab15 2 ⟨1, by omega⟩ j = MI BI (eHI 15) 2 ⟨1, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab15_eq_2_2 : ∀ j : Fin (9 - ((2 : Fin 6) : ℕ)),
    mif MItab15 2 ⟨2, by omega⟩ j = MI BI (eHI 15) 2 ⟨2, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab15_eq_2_3 : ∀ j : Fin (9 - ((2 : Fin 6) : ℕ)),
    mif MItab15 2 ⟨3, by omega⟩ j = MI BI (eHI 15) 2 ⟨3, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab15_eq_2_4 : ∀ j : Fin (9 - ((2 : Fin 6) : ℕ)),
    mif MItab15 2 ⟨4, by omega⟩ j = MI BI (eHI 15) 2 ⟨4, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab15_eq_2_5 : ∀ j : Fin (9 - ((2 : Fin 6) : ℕ)),
    mif MItab15 2 ⟨5, by omega⟩ j = MI BI (eHI 15) 2 ⟨5, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab15_eq_2_6 : ∀ j : Fin (9 - ((2 : Fin 6) : ℕ)),
    mif MItab15 2 ⟨6, by omega⟩ j = MI BI (eHI 15) 2 ⟨6, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab15_eq_3_0 : ∀ j : Fin (9 - ((3 : Fin 6) : ℕ)),
    mif MItab15 3 ⟨0, by omega⟩ j = MI BI (eHI 15) 3 ⟨0, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab15_eq_3_1 : ∀ j : Fin (9 - ((3 : Fin 6) : ℕ)),
    mif MItab15 3 ⟨1, by omega⟩ j = MI BI (eHI 15) 3 ⟨1, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab15_eq_3_2 : ∀ j : Fin (9 - ((3 : Fin 6) : ℕ)),
    mif MItab15 3 ⟨2, by omega⟩ j = MI BI (eHI 15) 3 ⟨2, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab15_eq_3_3 : ∀ j : Fin (9 - ((3 : Fin 6) : ℕ)),
    mif MItab15 3 ⟨3, by omega⟩ j = MI BI (eHI 15) 3 ⟨3, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab15_eq_3_4 : ∀ j : Fin (9 - ((3 : Fin 6) : ℕ)),
    mif MItab15 3 ⟨4, by omega⟩ j = MI BI (eHI 15) 3 ⟨4, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab15_eq_3_5 : ∀ j : Fin (9 - ((3 : Fin 6) : ℕ)),
    mif MItab15 3 ⟨5, by omega⟩ j = MI BI (eHI 15) 3 ⟨5, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab15_eq_4_0 : ∀ j : Fin (9 - ((4 : Fin 6) : ℕ)),
    mif MItab15 4 ⟨0, by omega⟩ j = MI BI (eHI 15) 4 ⟨0, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab15_eq_4_1 : ∀ j : Fin (9 - ((4 : Fin 6) : ℕ)),
    mif MItab15 4 ⟨1, by omega⟩ j = MI BI (eHI 15) 4 ⟨1, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab15_eq_4_2 : ∀ j : Fin (9 - ((4 : Fin 6) : ℕ)),
    mif MItab15 4 ⟨2, by omega⟩ j = MI BI (eHI 15) 4 ⟨2, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab15_eq_4_3 : ∀ j : Fin (9 - ((4 : Fin 6) : ℕ)),
    mif MItab15 4 ⟨3, by omega⟩ j = MI BI (eHI 15) 4 ⟨3, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab15_eq_4_4 : ∀ j : Fin (9 - ((4 : Fin 6) : ℕ)),
    mif MItab15 4 ⟨4, by omega⟩ j = MI BI (eHI 15) 4 ⟨4, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab15_eq_5_0 : ∀ j : Fin (9 - ((5 : Fin 6) : ℕ)),
    mif MItab15 5 ⟨0, by omega⟩ j = MI BI (eHI 15) 5 ⟨0, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab15_eq_5_1 : ∀ j : Fin (9 - ((5 : Fin 6) : ℕ)),
    mif MItab15 5 ⟨1, by omega⟩ j = MI BI (eHI 15) 5 ⟨1, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab15_eq_5_2 : ∀ j : Fin (9 - ((5 : Fin 6) : ℕ)),
    mif MItab15 5 ⟨2, by omega⟩ j = MI BI (eHI 15) 5 ⟨2, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab15_eq_5_3 : ∀ j : Fin (9 - ((5 : Fin 6) : ℕ)),
    mif MItab15 5 ⟨3, by omega⟩ j = MI BI (eHI 15) 5 ⟨3, by omega⟩ j := by
  decide +kernel

theorem MItab15_eq : ∀ (k : Fin 6) (i j : Fin (9 - (k : ℕ))),
    mif MItab15 k i j = MI BI (eHI 15) k i j := by
  intro k i
  fin_cases k <;> fin_cases i
  exacts [MItab15_eq_0_0,
    MItab15_eq_0_1,
    MItab15_eq_0_2,
    MItab15_eq_0_3,
    MItab15_eq_0_4,
    MItab15_eq_0_5,
    MItab15_eq_0_6,
    MItab15_eq_0_7,
    MItab15_eq_0_8,
    MItab15_eq_1_0,
    MItab15_eq_1_1,
    MItab15_eq_1_2,
    MItab15_eq_1_3,
    MItab15_eq_1_4,
    MItab15_eq_1_5,
    MItab15_eq_1_6,
    MItab15_eq_1_7,
    MItab15_eq_2_0,
    MItab15_eq_2_1,
    MItab15_eq_2_2,
    MItab15_eq_2_3,
    MItab15_eq_2_4,
    MItab15_eq_2_5,
    MItab15_eq_2_6,
    MItab15_eq_3_0,
    MItab15_eq_3_1,
    MItab15_eq_3_2,
    MItab15_eq_3_3,
    MItab15_eq_3_4,
    MItab15_eq_3_5,
    MItab15_eq_4_0,
    MItab15_eq_4_1,
    MItab15_eq_4_2,
    MItab15_eq_4_3,
    MItab15_eq_4_4,
    MItab15_eq_5_0,
    MItab15_eq_5_1,
    MItab15_eq_5_2,
    MItab15_eq_5_3]

/-- The coefficient tensor. -/
def Gtab15 : ITab :=
  [[[⟨0, 0⟩, ⟨-10000000000000000000000000000000000000002, -9999999999999999999999999999999999999999⟩, ⟨0, 0⟩, ⟨13333333333333333333333333333333333333332, 13333333333333333333333333333333333333336⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨-10000000000000000000000000000000000000002, -9999999999999999999999999999999999999999⟩, ⟨9999999999999999999999999999999999999999, 10000000000000000000000000000000000000002⟩, ⟨9999999999999999999999999999999999999999, 10000000000000000000000000000000000000002⟩, ⟨-10000000000000000000000000000000000000002, -9999999999999999999999999999999999999999⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨9999999999999999999999999999999999999999, 10000000000000000000000000000000000000002⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨13333333333333333333333333333333333333332, 13333333333333333333333333333333333333336⟩, ⟨-10000000000000000000000000000000000000002, -9999999999999999999999999999999999999999⟩, ⟨0, 0⟩, ⟨-3333333333333333333333333333333333333334, -3333333333333333333333333333333333333333⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨-10000000000000000000000000000000000000002, -9999999999999999999999999999999999999999⟩, ⟨9999999999999999999999999999999999999999, 10000000000000000000000000000000000000002⟩, ⟨9999999999999999999999999999999999999999, 10000000000000000000000000000000000000002⟩, ⟨-10000000000000000000000000000000000000002, -9999999999999999999999999999999999999999⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨9999999999999999999999999999999999999999, 10000000000000000000000000000000000000002⟩, ⟨0, 0⟩, ⟨-40000000000000000000000000000000000000008, -39999999999999999999999999999999999999996⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨9999999999999999999999999999999999999999, 10000000000000000000000000000000000000002⟩, ⟨-40000000000000000000000000000000000000008, -39999999999999999999999999999999999999996⟩, ⟨29999999999999999999999999999999999999997, 30000000000000000000000000000000000000006⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨-10000000000000000000000000000000000000002, -9999999999999999999999999999999999999999⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨0, 0⟩, ⟨9999999999999999999999999999999999999999, 10000000000000000000000000000000000000002⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨9999999999999999999999999999999999999999, 10000000000000000000000000000000000000002⟩, ⟨-40000000000000000000000000000000000000008, -39999999999999999999999999999999999999996⟩, ⟨29999999999999999999999999999999999999997, 30000000000000000000000000000000000000006⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨29999999999999999999999999999999999999997, 30000000000000000000000000000000000000006⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨13333333333333333333333333333333333333332, 13333333333333333333333333333333333333336⟩, ⟨-10000000000000000000000000000000000000002, -9999999999999999999999999999999999999999⟩, ⟨0, 0⟩, ⟨-3333333333333333333333333333333333333334, -3333333333333333333333333333333333333333⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨-10000000000000000000000000000000000000002, -9999999999999999999999999999999999999999⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨-3333333333333333333333333333333333333334, -3333333333333333333333333333333333333333⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]]]

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_0_0 : ∀ r : Fin 9, getT Gtab15 0 0 r = CF (mif MItab15) 0 0 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_0_1 : ∀ r : Fin 9, getT Gtab15 0 1 r = CF (mif MItab15) 0 1 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_0_2 : ∀ r : Fin 9, getT Gtab15 0 2 r = CF (mif MItab15) 0 2 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_0_3 : ∀ r : Fin 9, getT Gtab15 0 3 r = CF (mif MItab15) 0 3 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_0_4 : ∀ r : Fin 9, getT Gtab15 0 4 r = CF (mif MItab15) 0 4 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_0_5 : ∀ r : Fin 9, getT Gtab15 0 5 r = CF (mif MItab15) 0 5 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_0_6 : ∀ r : Fin 9, getT Gtab15 0 6 r = CF (mif MItab15) 0 6 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_0_7 : ∀ r : Fin 9, getT Gtab15 0 7 r = CF (mif MItab15) 0 7 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_0_8 : ∀ r : Fin 9, getT Gtab15 0 8 r = CF (mif MItab15) 0 8 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_1_0 : ∀ r : Fin 9, getT Gtab15 1 0 r = CF (mif MItab15) 1 0 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_1_1 : ∀ r : Fin 9, getT Gtab15 1 1 r = CF (mif MItab15) 1 1 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_1_2 : ∀ r : Fin 9, getT Gtab15 1 2 r = CF (mif MItab15) 1 2 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_1_3 : ∀ r : Fin 9, getT Gtab15 1 3 r = CF (mif MItab15) 1 3 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_1_4 : ∀ r : Fin 9, getT Gtab15 1 4 r = CF (mif MItab15) 1 4 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_1_5 : ∀ r : Fin 9, getT Gtab15 1 5 r = CF (mif MItab15) 1 5 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_1_6 : ∀ r : Fin 9, getT Gtab15 1 6 r = CF (mif MItab15) 1 6 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_1_7 : ∀ r : Fin 9, getT Gtab15 1 7 r = CF (mif MItab15) 1 7 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_1_8 : ∀ r : Fin 9, getT Gtab15 1 8 r = CF (mif MItab15) 1 8 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_2_0 : ∀ r : Fin 9, getT Gtab15 2 0 r = CF (mif MItab15) 2 0 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_2_1 : ∀ r : Fin 9, getT Gtab15 2 1 r = CF (mif MItab15) 2 1 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_2_2 : ∀ r : Fin 9, getT Gtab15 2 2 r = CF (mif MItab15) 2 2 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_2_3 : ∀ r : Fin 9, getT Gtab15 2 3 r = CF (mif MItab15) 2 3 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_2_4 : ∀ r : Fin 9, getT Gtab15 2 4 r = CF (mif MItab15) 2 4 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_2_5 : ∀ r : Fin 9, getT Gtab15 2 5 r = CF (mif MItab15) 2 5 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_2_6 : ∀ r : Fin 9, getT Gtab15 2 6 r = CF (mif MItab15) 2 6 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_2_7 : ∀ r : Fin 9, getT Gtab15 2 7 r = CF (mif MItab15) 2 7 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_2_8 : ∀ r : Fin 9, getT Gtab15 2 8 r = CF (mif MItab15) 2 8 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_3_0 : ∀ r : Fin 9, getT Gtab15 3 0 r = CF (mif MItab15) 3 0 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_3_1 : ∀ r : Fin 9, getT Gtab15 3 1 r = CF (mif MItab15) 3 1 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_3_2 : ∀ r : Fin 9, getT Gtab15 3 2 r = CF (mif MItab15) 3 2 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_3_3 : ∀ r : Fin 9, getT Gtab15 3 3 r = CF (mif MItab15) 3 3 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_3_4 : ∀ r : Fin 9, getT Gtab15 3 4 r = CF (mif MItab15) 3 4 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_3_5 : ∀ r : Fin 9, getT Gtab15 3 5 r = CF (mif MItab15) 3 5 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_3_6 : ∀ r : Fin 9, getT Gtab15 3 6 r = CF (mif MItab15) 3 6 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_3_7 : ∀ r : Fin 9, getT Gtab15 3 7 r = CF (mif MItab15) 3 7 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_3_8 : ∀ r : Fin 9, getT Gtab15 3 8 r = CF (mif MItab15) 3 8 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_4_0 : ∀ r : Fin 9, getT Gtab15 4 0 r = CF (mif MItab15) 4 0 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_4_1 : ∀ r : Fin 9, getT Gtab15 4 1 r = CF (mif MItab15) 4 1 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_4_2 : ∀ r : Fin 9, getT Gtab15 4 2 r = CF (mif MItab15) 4 2 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_4_3 : ∀ r : Fin 9, getT Gtab15 4 3 r = CF (mif MItab15) 4 3 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_4_4 : ∀ r : Fin 9, getT Gtab15 4 4 r = CF (mif MItab15) 4 4 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_4_5 : ∀ r : Fin 9, getT Gtab15 4 5 r = CF (mif MItab15) 4 5 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_4_6 : ∀ r : Fin 9, getT Gtab15 4 6 r = CF (mif MItab15) 4 6 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_4_7 : ∀ r : Fin 9, getT Gtab15 4 7 r = CF (mif MItab15) 4 7 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_4_8 : ∀ r : Fin 9, getT Gtab15 4 8 r = CF (mif MItab15) 4 8 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_5_0 : ∀ r : Fin 9, getT Gtab15 5 0 r = CF (mif MItab15) 5 0 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_5_1 : ∀ r : Fin 9, getT Gtab15 5 1 r = CF (mif MItab15) 5 1 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_5_2 : ∀ r : Fin 9, getT Gtab15 5 2 r = CF (mif MItab15) 5 2 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_5_3 : ∀ r : Fin 9, getT Gtab15 5 3 r = CF (mif MItab15) 5 3 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_5_4 : ∀ r : Fin 9, getT Gtab15 5 4 r = CF (mif MItab15) 5 4 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_5_5 : ∀ r : Fin 9, getT Gtab15 5 5 r = CF (mif MItab15) 5 5 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_5_6 : ∀ r : Fin 9, getT Gtab15 5 6 r = CF (mif MItab15) 5 6 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_5_7 : ∀ r : Fin 9, getT Gtab15 5 7 r = CF (mif MItab15) 5 7 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_5_8 : ∀ r : Fin 9, getT Gtab15 5 8 r = CF (mif MItab15) 5 8 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_6_0 : ∀ r : Fin 9, getT Gtab15 6 0 r = CF (mif MItab15) 6 0 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_6_1 : ∀ r : Fin 9, getT Gtab15 6 1 r = CF (mif MItab15) 6 1 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_6_2 : ∀ r : Fin 9, getT Gtab15 6 2 r = CF (mif MItab15) 6 2 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_6_3 : ∀ r : Fin 9, getT Gtab15 6 3 r = CF (mif MItab15) 6 3 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_6_4 : ∀ r : Fin 9, getT Gtab15 6 4 r = CF (mif MItab15) 6 4 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_6_5 : ∀ r : Fin 9, getT Gtab15 6 5 r = CF (mif MItab15) 6 5 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_6_6 : ∀ r : Fin 9, getT Gtab15 6 6 r = CF (mif MItab15) 6 6 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_6_7 : ∀ r : Fin 9, getT Gtab15 6 7 r = CF (mif MItab15) 6 7 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_6_8 : ∀ r : Fin 9, getT Gtab15 6 8 r = CF (mif MItab15) 6 8 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_7_0 : ∀ r : Fin 9, getT Gtab15 7 0 r = CF (mif MItab15) 7 0 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_7_1 : ∀ r : Fin 9, getT Gtab15 7 1 r = CF (mif MItab15) 7 1 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_7_2 : ∀ r : Fin 9, getT Gtab15 7 2 r = CF (mif MItab15) 7 2 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_7_3 : ∀ r : Fin 9, getT Gtab15 7 3 r = CF (mif MItab15) 7 3 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_7_4 : ∀ r : Fin 9, getT Gtab15 7 4 r = CF (mif MItab15) 7 4 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_7_5 : ∀ r : Fin 9, getT Gtab15 7 5 r = CF (mif MItab15) 7 5 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_7_6 : ∀ r : Fin 9, getT Gtab15 7 6 r = CF (mif MItab15) 7 6 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_7_7 : ∀ r : Fin 9, getT Gtab15 7 7 r = CF (mif MItab15) 7 7 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_7_8 : ∀ r : Fin 9, getT Gtab15 7 8 r = CF (mif MItab15) 7 8 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_8_0 : ∀ r : Fin 9, getT Gtab15 8 0 r = CF (mif MItab15) 8 0 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_8_1 : ∀ r : Fin 9, getT Gtab15 8 1 r = CF (mif MItab15) 8 1 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_8_2 : ∀ r : Fin 9, getT Gtab15 8 2 r = CF (mif MItab15) 8 2 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_8_3 : ∀ r : Fin 9, getT Gtab15 8 3 r = CF (mif MItab15) 8 3 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_8_4 : ∀ r : Fin 9, getT Gtab15 8 4 r = CF (mif MItab15) 8 4 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_8_5 : ∀ r : Fin 9, getT Gtab15 8 5 r = CF (mif MItab15) 8 5 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_8_6 : ∀ r : Fin 9, getT Gtab15 8 6 r = CF (mif MItab15) 8 6 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_8_7 : ∀ r : Fin 9, getT Gtab15 8 7 r = CF (mif MItab15) 8 7 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab15_eq_8_8 : ∀ r : Fin 9, getT Gtab15 8 8 r = CF (mif MItab15) 8 8 r := by
  decide +kernel

theorem Gtab15_eq : ∀ p q r : Fin 9, getT Gtab15 p q r = CF (mif MItab15) p q r := by
  intro p q
  fin_cases p <;> fin_cases q
  exacts [Gtab15_eq_0_0,
    Gtab15_eq_0_1,
    Gtab15_eq_0_2,
    Gtab15_eq_0_3,
    Gtab15_eq_0_4,
    Gtab15_eq_0_5,
    Gtab15_eq_0_6,
    Gtab15_eq_0_7,
    Gtab15_eq_0_8,
    Gtab15_eq_1_0,
    Gtab15_eq_1_1,
    Gtab15_eq_1_2,
    Gtab15_eq_1_3,
    Gtab15_eq_1_4,
    Gtab15_eq_1_5,
    Gtab15_eq_1_6,
    Gtab15_eq_1_7,
    Gtab15_eq_1_8,
    Gtab15_eq_2_0,
    Gtab15_eq_2_1,
    Gtab15_eq_2_2,
    Gtab15_eq_2_3,
    Gtab15_eq_2_4,
    Gtab15_eq_2_5,
    Gtab15_eq_2_6,
    Gtab15_eq_2_7,
    Gtab15_eq_2_8,
    Gtab15_eq_3_0,
    Gtab15_eq_3_1,
    Gtab15_eq_3_2,
    Gtab15_eq_3_3,
    Gtab15_eq_3_4,
    Gtab15_eq_3_5,
    Gtab15_eq_3_6,
    Gtab15_eq_3_7,
    Gtab15_eq_3_8,
    Gtab15_eq_4_0,
    Gtab15_eq_4_1,
    Gtab15_eq_4_2,
    Gtab15_eq_4_3,
    Gtab15_eq_4_4,
    Gtab15_eq_4_5,
    Gtab15_eq_4_6,
    Gtab15_eq_4_7,
    Gtab15_eq_4_8,
    Gtab15_eq_5_0,
    Gtab15_eq_5_1,
    Gtab15_eq_5_2,
    Gtab15_eq_5_3,
    Gtab15_eq_5_4,
    Gtab15_eq_5_5,
    Gtab15_eq_5_6,
    Gtab15_eq_5_7,
    Gtab15_eq_5_8,
    Gtab15_eq_6_0,
    Gtab15_eq_6_1,
    Gtab15_eq_6_2,
    Gtab15_eq_6_3,
    Gtab15_eq_6_4,
    Gtab15_eq_6_5,
    Gtab15_eq_6_6,
    Gtab15_eq_6_7,
    Gtab15_eq_6_8,
    Gtab15_eq_7_0,
    Gtab15_eq_7_1,
    Gtab15_eq_7_2,
    Gtab15_eq_7_3,
    Gtab15_eq_7_4,
    Gtab15_eq_7_5,
    Gtab15_eq_7_6,
    Gtab15_eq_7_7,
    Gtab15_eq_7_8,
    Gtab15_eq_8_0,
    Gtab15_eq_8_1,
    Gtab15_eq_8_2,
    Gtab15_eq_8_3,
    Gtab15_eq_8_4,
    Gtab15_eq_8_5,
    Gtab15_eq_8_6,
    Gtab15_eq_8_7,
    Gtab15_eq_8_8]

/-- The 24 entries. -/
def col15 : List Itv :=
  [⟨-264, 264⟩,
    ⟨-28326071016418511676103691892830148297165, -28326071016418511676103691892685426436304⟩,
    ⟨-10600004459532727663109504626241996078084, -10600004459532727663109504626165699919201⟩,
    ⟨39054808176618254378649045722708935680690, 39054808176618254378649045723139213181549⟩,
    ⟨-11781002982504730992055444531348272640540, -11781002982504730992055444531317066017665⟩,
    ⟨-25174821031659928969268209965783796156493, -25174821031659928969268209965638120796659⟩,
    ⟨-895654105394956975951295342706908956029, -895654105394956975951295342400700222982⟩,
    ⟨22065230295366947767821870261818337834694, 22065230295366947767821870263280341770995⟩,
    ⟨3588384713791650303291922299572964809002, 3588384713791650303291922299696678536626⟩,
    ⟨146583607384797490161011268102549536924490, 146583607384797490161011268102926547594292⟩,
    ⟨74218044655105236813633300958288248463515, 74218044655105236813633300958613819626216⟩,
    ⟨-7547446252665038898476854011292151220191, -7547446252665038898476854011236379293508⟩,
    ⟨133886027353060244467554800371102384421738, 133886027353060244467554800371301340522377⟩,
    ⟨-11248530487022684288763984743324513083987, -11248530487022684288763984743170682040044⟩,
    ⟨4408873934078857613984146980765733765918, 4408873934078857613984146980798826435031⟩,
    ⟨30910058002427830709054476844649392466289, 30910058002427830709054476844764069126514⟩,
    ⟨77292769726781342891340714682097282079, 77292769726781342891340714771385172245⟩,
    ⟨3707332755648425586877373447542731994892, 3707332755648425586877373447626891007417⟩,
    ⟨4832221667559101591096720125599558772403, 4832221667559101591096720125614047084396⟩,
    ⟨-15270230159842811283973127861048451692365, -15270230159842811283973127860999129430421⟩,
    ⟨1388042273438109269551070749602646346008, 1388042273438109269551070749642046350368⟩,
    ⟨8516552258903431289024708008147428454810, 8516552258903431289024708008155905628981⟩,
    ⟨-1544258243542960023640119058729803490834, -1544258243542960023640119058707291561704⟩,
    ⟨2847196639896090967213443047536290001290, 2847196639896090967213443047558113446310⟩]

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col15_eq00 : col15.getD 0 Itv.zero = entAt (getT Gtab15) 0 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col15_eq01 : col15.getD 1 Itv.zero = entAt (getT Gtab15) 1 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col15_eq02 : col15.getD 2 Itv.zero = entAt (getT Gtab15) 2 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col15_eq03 : col15.getD 3 Itv.zero = entAt (getT Gtab15) 3 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col15_eq04 : col15.getD 4 Itv.zero = entAt (getT Gtab15) 4 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col15_eq05 : col15.getD 5 Itv.zero = entAt (getT Gtab15) 5 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col15_eq06 : col15.getD 6 Itv.zero = entAt (getT Gtab15) 6 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col15_eq07 : col15.getD 7 Itv.zero = entAt (getT Gtab15) 7 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col15_eq08 : col15.getD 8 Itv.zero = entAt (getT Gtab15) 8 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col15_eq09 : col15.getD 9 Itv.zero = entAt (getT Gtab15) 9 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col15_eq10 : col15.getD 10 Itv.zero = entAt (getT Gtab15) 10 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col15_eq11 : col15.getD 11 Itv.zero = entAt (getT Gtab15) 11 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col15_eq12 : col15.getD 12 Itv.zero = entAt (getT Gtab15) 12 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col15_eq13 : col15.getD 13 Itv.zero = entAt (getT Gtab15) 13 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col15_eq14 : col15.getD 14 Itv.zero = entAt (getT Gtab15) 14 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col15_eq15 : col15.getD 15 Itv.zero = entAt (getT Gtab15) 15 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col15_eq16 : col15.getD 16 Itv.zero = entAt (getT Gtab15) 16 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col15_eq17 : col15.getD 17 Itv.zero = entAt (getT Gtab15) 17 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col15_eq18 : col15.getD 18 Itv.zero = entAt (getT Gtab15) 18 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col15_eq19 : col15.getD 19 Itv.zero = entAt (getT Gtab15) 19 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col15_eq20 : col15.getD 20 Itv.zero = entAt (getT Gtab15) 20 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col15_eq21 : col15.getD 21 Itv.zero = entAt (getT Gtab15) 21 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col15_eq22 : col15.getD 22 Itv.zero = entAt (getT Gtab15) 22 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col15_eq23 : col15.getD 23 Itv.zero = entAt (getT Gtab15) 23 := by
  decide +kernel

theorem col15_eq : ∀ i : Fin 24, col15.getD (i : ℕ) Itv.zero = entAt (getT Gtab15) (i : ℕ) := by
  intro i
  fin_cases i
  exacts [col15_eq00,
    col15_eq01,
    col15_eq02,
    col15_eq03,
    col15_eq04,
    col15_eq05,
    col15_eq06,
    col15_eq07,
    col15_eq08,
    col15_eq09,
    col15_eq10,
    col15_eq11,
    col15_eq12,
    col15_eq13,
    col15_eq14,
    col15_eq15,
    col15_eq16,
    col15_eq17,
    col15_eq18,
    col15_eq19,
    col15_eq20,
    col15_eq21,
    col15_eq22,
    col15_eq23]

theorem ITMem_Gtab15 : ITMem (getT Gtab15) (cG 15) :=
  ITMem_getT_G MItab15_eq Gtab15_eq

theorem mem_col15 (i : Fin 24) : (col15.getD (i : ℕ) Itv.zero).Mem (pivotMatrix i 15) := by
  rw [col15_eq]; exact mem_entAt ITMem_Gtab15 i

end Thomson.Task1b
