-- GENERATED by Thomson/Pivots/gen/mk_tables.py; do not edit
import Thomson.Pivots.KBase

/-! # Task 1b: the tensor of `Gh 16`, and column 16 — GENERATED

Three literal tables, each checked against its definition by `decide +kernel` in pieces small
enough for the kernel's cache (see `KBase`): the blocks `M_k = B_k H_k B_kᵀ` of the indicator block of pivot 16,
three rows at a time; the coefficient tensor built from those blocks, one `(p, q)` row of nine
at a time; and the 24 entries of column 16 of the pivot system, one at a time. -/

namespace Thomson.Task1b

open Thomson Thomson.Tri5b

/-- The blocks `M_k`. -/
def MItab16 : ITab :=
  [[[⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨0, 0⟩, ⟨-1422443566033621542298431409867601778264, -1422443566033621542298431409866652547129⟩, ⟨-9898531550982060970892282090065919388974, -9898531550982060970892282090062919688973⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨-1422443566033621542298431409867601778264, -1422443566033621542298431409866652547129⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨-9898531550982060970892282090065919388974, -9898531550982060970892282090062919688973⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]]]

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab16_eq_0_0 : ∀ j : Fin (9 - ((0 : Fin 6) : ℕ)),
    mif MItab16 0 ⟨0, by omega⟩ j = MI BI (eHI 16) 0 ⟨0, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab16_eq_0_1 : ∀ j : Fin (9 - ((0 : Fin 6) : ℕ)),
    mif MItab16 0 ⟨1, by omega⟩ j = MI BI (eHI 16) 0 ⟨1, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab16_eq_0_2 : ∀ j : Fin (9 - ((0 : Fin 6) : ℕ)),
    mif MItab16 0 ⟨2, by omega⟩ j = MI BI (eHI 16) 0 ⟨2, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab16_eq_0_3 : ∀ j : Fin (9 - ((0 : Fin 6) : ℕ)),
    mif MItab16 0 ⟨3, by omega⟩ j = MI BI (eHI 16) 0 ⟨3, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab16_eq_0_4 : ∀ j : Fin (9 - ((0 : Fin 6) : ℕ)),
    mif MItab16 0 ⟨4, by omega⟩ j = MI BI (eHI 16) 0 ⟨4, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab16_eq_0_5 : ∀ j : Fin (9 - ((0 : Fin 6) : ℕ)),
    mif MItab16 0 ⟨5, by omega⟩ j = MI BI (eHI 16) 0 ⟨5, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab16_eq_0_6 : ∀ j : Fin (9 - ((0 : Fin 6) : ℕ)),
    mif MItab16 0 ⟨6, by omega⟩ j = MI BI (eHI 16) 0 ⟨6, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab16_eq_0_7 : ∀ j : Fin (9 - ((0 : Fin 6) : ℕ)),
    mif MItab16 0 ⟨7, by omega⟩ j = MI BI (eHI 16) 0 ⟨7, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab16_eq_0_8 : ∀ j : Fin (9 - ((0 : Fin 6) : ℕ)),
    mif MItab16 0 ⟨8, by omega⟩ j = MI BI (eHI 16) 0 ⟨8, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab16_eq_1_0 : ∀ j : Fin (9 - ((1 : Fin 6) : ℕ)),
    mif MItab16 1 ⟨0, by omega⟩ j = MI BI (eHI 16) 1 ⟨0, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab16_eq_1_1 : ∀ j : Fin (9 - ((1 : Fin 6) : ℕ)),
    mif MItab16 1 ⟨1, by omega⟩ j = MI BI (eHI 16) 1 ⟨1, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab16_eq_1_2 : ∀ j : Fin (9 - ((1 : Fin 6) : ℕ)),
    mif MItab16 1 ⟨2, by omega⟩ j = MI BI (eHI 16) 1 ⟨2, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab16_eq_1_3 : ∀ j : Fin (9 - ((1 : Fin 6) : ℕ)),
    mif MItab16 1 ⟨3, by omega⟩ j = MI BI (eHI 16) 1 ⟨3, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab16_eq_1_4 : ∀ j : Fin (9 - ((1 : Fin 6) : ℕ)),
    mif MItab16 1 ⟨4, by omega⟩ j = MI BI (eHI 16) 1 ⟨4, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab16_eq_1_5 : ∀ j : Fin (9 - ((1 : Fin 6) : ℕ)),
    mif MItab16 1 ⟨5, by omega⟩ j = MI BI (eHI 16) 1 ⟨5, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab16_eq_1_6 : ∀ j : Fin (9 - ((1 : Fin 6) : ℕ)),
    mif MItab16 1 ⟨6, by omega⟩ j = MI BI (eHI 16) 1 ⟨6, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab16_eq_1_7 : ∀ j : Fin (9 - ((1 : Fin 6) : ℕ)),
    mif MItab16 1 ⟨7, by omega⟩ j = MI BI (eHI 16) 1 ⟨7, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab16_eq_2_0 : ∀ j : Fin (9 - ((2 : Fin 6) : ℕ)),
    mif MItab16 2 ⟨0, by omega⟩ j = MI BI (eHI 16) 2 ⟨0, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab16_eq_2_1 : ∀ j : Fin (9 - ((2 : Fin 6) : ℕ)),
    mif MItab16 2 ⟨1, by omega⟩ j = MI BI (eHI 16) 2 ⟨1, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab16_eq_2_2 : ∀ j : Fin (9 - ((2 : Fin 6) : ℕ)),
    mif MItab16 2 ⟨2, by omega⟩ j = MI BI (eHI 16) 2 ⟨2, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab16_eq_2_3 : ∀ j : Fin (9 - ((2 : Fin 6) : ℕ)),
    mif MItab16 2 ⟨3, by omega⟩ j = MI BI (eHI 16) 2 ⟨3, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab16_eq_2_4 : ∀ j : Fin (9 - ((2 : Fin 6) : ℕ)),
    mif MItab16 2 ⟨4, by omega⟩ j = MI BI (eHI 16) 2 ⟨4, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab16_eq_2_5 : ∀ j : Fin (9 - ((2 : Fin 6) : ℕ)),
    mif MItab16 2 ⟨5, by omega⟩ j = MI BI (eHI 16) 2 ⟨5, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab16_eq_2_6 : ∀ j : Fin (9 - ((2 : Fin 6) : ℕ)),
    mif MItab16 2 ⟨6, by omega⟩ j = MI BI (eHI 16) 2 ⟨6, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab16_eq_3_0 : ∀ j : Fin (9 - ((3 : Fin 6) : ℕ)),
    mif MItab16 3 ⟨0, by omega⟩ j = MI BI (eHI 16) 3 ⟨0, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab16_eq_3_1 : ∀ j : Fin (9 - ((3 : Fin 6) : ℕ)),
    mif MItab16 3 ⟨1, by omega⟩ j = MI BI (eHI 16) 3 ⟨1, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab16_eq_3_2 : ∀ j : Fin (9 - ((3 : Fin 6) : ℕ)),
    mif MItab16 3 ⟨2, by omega⟩ j = MI BI (eHI 16) 3 ⟨2, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab16_eq_3_3 : ∀ j : Fin (9 - ((3 : Fin 6) : ℕ)),
    mif MItab16 3 ⟨3, by omega⟩ j = MI BI (eHI 16) 3 ⟨3, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab16_eq_3_4 : ∀ j : Fin (9 - ((3 : Fin 6) : ℕ)),
    mif MItab16 3 ⟨4, by omega⟩ j = MI BI (eHI 16) 3 ⟨4, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab16_eq_3_5 : ∀ j : Fin (9 - ((3 : Fin 6) : ℕ)),
    mif MItab16 3 ⟨5, by omega⟩ j = MI BI (eHI 16) 3 ⟨5, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab16_eq_4_0 : ∀ j : Fin (9 - ((4 : Fin 6) : ℕ)),
    mif MItab16 4 ⟨0, by omega⟩ j = MI BI (eHI 16) 4 ⟨0, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab16_eq_4_1 : ∀ j : Fin (9 - ((4 : Fin 6) : ℕ)),
    mif MItab16 4 ⟨1, by omega⟩ j = MI BI (eHI 16) 4 ⟨1, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab16_eq_4_2 : ∀ j : Fin (9 - ((4 : Fin 6) : ℕ)),
    mif MItab16 4 ⟨2, by omega⟩ j = MI BI (eHI 16) 4 ⟨2, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab16_eq_4_3 : ∀ j : Fin (9 - ((4 : Fin 6) : ℕ)),
    mif MItab16 4 ⟨3, by omega⟩ j = MI BI (eHI 16) 4 ⟨3, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab16_eq_4_4 : ∀ j : Fin (9 - ((4 : Fin 6) : ℕ)),
    mif MItab16 4 ⟨4, by omega⟩ j = MI BI (eHI 16) 4 ⟨4, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab16_eq_5_0 : ∀ j : Fin (9 - ((5 : Fin 6) : ℕ)),
    mif MItab16 5 ⟨0, by omega⟩ j = MI BI (eHI 16) 5 ⟨0, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab16_eq_5_1 : ∀ j : Fin (9 - ((5 : Fin 6) : ℕ)),
    mif MItab16 5 ⟨1, by omega⟩ j = MI BI (eHI 16) 5 ⟨1, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab16_eq_5_2 : ∀ j : Fin (9 - ((5 : Fin 6) : ℕ)),
    mif MItab16 5 ⟨2, by omega⟩ j = MI BI (eHI 16) 5 ⟨2, by omega⟩ j := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem MItab16_eq_5_3 : ∀ j : Fin (9 - ((5 : Fin 6) : ℕ)),
    mif MItab16 5 ⟨3, by omega⟩ j = MI BI (eHI 16) 5 ⟨3, by omega⟩ j := by
  decide +kernel

theorem MItab16_eq : ∀ (k : Fin 6) (i j : Fin (9 - (k : ℕ))),
    mif MItab16 k i j = MI BI (eHI 16) k i j := by
  intro k i
  fin_cases k <;> fin_cases i
  exacts [MItab16_eq_0_0,
    MItab16_eq_0_1,
    MItab16_eq_0_2,
    MItab16_eq_0_3,
    MItab16_eq_0_4,
    MItab16_eq_0_5,
    MItab16_eq_0_6,
    MItab16_eq_0_7,
    MItab16_eq_0_8,
    MItab16_eq_1_0,
    MItab16_eq_1_1,
    MItab16_eq_1_2,
    MItab16_eq_1_3,
    MItab16_eq_1_4,
    MItab16_eq_1_5,
    MItab16_eq_1_6,
    MItab16_eq_1_7,
    MItab16_eq_2_0,
    MItab16_eq_2_1,
    MItab16_eq_2_2,
    MItab16_eq_2_3,
    MItab16_eq_2_4,
    MItab16_eq_2_5,
    MItab16_eq_2_6,
    MItab16_eq_3_0,
    MItab16_eq_3_1,
    MItab16_eq_3_2,
    MItab16_eq_3_3,
    MItab16_eq_3_4,
    MItab16_eq_3_5,
    MItab16_eq_4_0,
    MItab16_eq_4_1,
    MItab16_eq_4_2,
    MItab16_eq_4_3,
    MItab16_eq_4_4,
    MItab16_eq_5_0,
    MItab16_eq_5_1,
    MItab16_eq_5_2,
    MItab16_eq_5_3]

/-- The coefficient tensor. -/
def Gtab16 : ITab :=
  [[[⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨2844887132067243084596862819733305094257, 2844887132067243084596862819735203556529⟩, ⟨8476087984948439428593850680195317910708, 8476087984948439428593850680199266841847⟩, ⟨-13217566538393844569588622046423656871593, -13217566538393844569588622046418442298939⟩, ⟨-8476087984948439428593850680199266841847, -8476087984948439428593850680195317910708⟩, ⟨9898531550982060970892282090062919688972, 9898531550982060970892282090065919388976⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨8476087984948439428593850680195317910708, 8476087984948439428593850680199266841847⟩, ⟨0, 0⟩, ⟨-11775598501942459752224611376887906638173, -11775598501942459752224611376882957807032⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨-13217566538393844569588622046423656871593, -13217566538393844569588622046418442298939⟩, ⟨-11775598501942459752224611376887906638173, -11775598501942459752224611376882957807032⟩, ⟨19797063101964121941784564180125839377944, 19797063101964121941784564180131838777952⟩, ⟨474147855344540514099477136622217515709, 474147855344540514099477136622533926089⟩, ⟨3299510516994020323630760696687639896324, 3299510516994020323630760696688639796326⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨-8476087984948439428593850680199266841847, -8476087984948439428593850680195317910708⟩, ⟨0, 0⟩, ⟨474147855344540514099477136622217515709, 474147855344540514099477136622533926089⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨9898531550982060970892282090062919688972, 9898531550982060970892282090065919388976⟩, ⟨0, 0⟩, ⟨3299510516994020323630760696687639896324, 3299510516994020323630760696688639796326⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨0, 0⟩, ⟨2844887132067243084596862819733305094257, 2844887132067243084596862819735203556529⟩, ⟨8476087984948439428593850680195317910708, 8476087984948439428593850680199266841847⟩, ⟨-13217566538393844569588622046423656871593, -13217566538393844569588622046418442298939⟩, ⟨-8476087984948439428593850680199266841847, -8476087984948439428593850680195317910708⟩, ⟨9898531550982060970892282090062919688972, 9898531550982060970892282090065919388976⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨2844887132067243084596862819733305094257, 2844887132067243084596862819735203556529⟩, ⟨0, 0⟩, ⟨-2844887132067243084596862819735203556529, -2844887132067243084596862819733305094257⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨8476087984948439428593850680195317910708, 8476087984948439428593850680199266841847⟩, ⟨-2844887132067243084596862819735203556529, -2844887132067243084596862819733305094257⟩, ⟨-8417514573695149603397112901198618400918, -8417514573695149603397112901185025151833⟩, ⟨35326795505827379256673834130648873421096, 35326795505827379256673834130663719914517⟩, ⟨-29695594652946182912676846270197758166928, -29695594652946182912676846270188759066916⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨-13217566538393844569588622046423656871593, -13217566538393844569588622046418442298939⟩, ⟨0, 0⟩, ⟨35326795505827379256673834130648873421096, 35326795505827379256673834130663719914517⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨-8476087984948439428593850680199266841847, -8476087984948439428593850680195317910708⟩, ⟨0, 0⟩, ⟨-29695594652946182912676846270197758166928, -29695594652946182912676846270188759066916⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨9898531550982060970892282090062919688972, 9898531550982060970892282090065919388976⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨0, 0⟩, ⟨8476087984948439428593850680195317910708, 8476087984948439428593850680199266841847⟩, ⟨0, 0⟩, ⟨-11775598501942459752224611376887906638173, -11775598501942459752224611376882957807032⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨8476087984948439428593850680195317910708, 8476087984948439428593850680199266841847⟩, ⟨-2844887132067243084596862819735203556529, -2844887132067243084596862819733305094257⟩, ⟨-8417514573695149603397112901198618400918, -8417514573695149603397112901185025151833⟩, ⟨35326795505827379256673834130648873421096, 35326795505827379256673834130663719914517⟩, ⟨-29695594652946182912676846270197758166928, -29695594652946182912676846270188759066916⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨-8417514573695149603397112901198618400918, -8417514573695149603397112901185025151833⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨-11775598501942459752224611376887906638173, -11775598501942459752224611376882957807032⟩, ⟨35326795505827379256673834130648873421096, 35326795505827379256673834130663719914517⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨-29695594652946182912676846270197758166928, -29695594652946182912676846270188759066916⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨0, 0⟩, ⟨-13217566538393844569588622046423656871593, -13217566538393844569588622046418442298939⟩, ⟨-11775598501942459752224611376887906638173, -11775598501942459752224611376882957807032⟩, ⟨19797063101964121941784564180125839377944, 19797063101964121941784564180131838777952⟩, ⟨474147855344540514099477136622217515709, 474147855344540514099477136622533926089⟩, ⟨3299510516994020323630760696687639896324, 3299510516994020323630760696688639796326⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨-13217566538393844569588622046423656871593, -13217566538393844569588622046418442298939⟩, ⟨0, 0⟩, ⟨35326795505827379256673834130648873421096, 35326795505827379256673834130663719914517⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨-11775598501942459752224611376887906638173, -11775598501942459752224611376882957807032⟩, ⟨35326795505827379256673834130648873421096, 35326795505827379256673834130663719914517⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨19797063101964121941784564180125839377944, 19797063101964121941784564180131838777952⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨474147855344540514099477136622217515709, 474147855344540514099477136622533926089⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨3299510516994020323630760696687639896324, 3299510516994020323630760696688639796326⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨0, 0⟩, ⟨-8476087984948439428593850680199266841847, -8476087984948439428593850680195317910708⟩, ⟨0, 0⟩, ⟨474147855344540514099477136622217515709, 474147855344540514099477136622533926089⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨-8476087984948439428593850680199266841847, -8476087984948439428593850680195317910708⟩, ⟨0, 0⟩, ⟨-29695594652946182912676846270197758166928, -29695594652946182912676846270188759066916⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨-29695594652946182912676846270197758166928, -29695594652946182912676846270188759066916⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨474147855344540514099477136622217515709, 474147855344540514099477136622533926089⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨0, 0⟩, ⟨9898531550982060970892282090062919688972, 9898531550982060970892282090065919388976⟩, ⟨0, 0⟩, ⟨3299510516994020323630760696687639896324, 3299510516994020323630760696688639796326⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨9898531550982060970892282090062919688972, 9898531550982060970892282090065919388976⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨3299510516994020323630760696687639896324, 3299510516994020323630760696688639796326⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]],
    [[⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩],
     [⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩, ⟨0, 0⟩]]]

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_0_0 : ∀ r : Fin 9, getT Gtab16 0 0 r = CF (mif MItab16) 0 0 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_0_1 : ∀ r : Fin 9, getT Gtab16 0 1 r = CF (mif MItab16) 0 1 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_0_2 : ∀ r : Fin 9, getT Gtab16 0 2 r = CF (mif MItab16) 0 2 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_0_3 : ∀ r : Fin 9, getT Gtab16 0 3 r = CF (mif MItab16) 0 3 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_0_4 : ∀ r : Fin 9, getT Gtab16 0 4 r = CF (mif MItab16) 0 4 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_0_5 : ∀ r : Fin 9, getT Gtab16 0 5 r = CF (mif MItab16) 0 5 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_0_6 : ∀ r : Fin 9, getT Gtab16 0 6 r = CF (mif MItab16) 0 6 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_0_7 : ∀ r : Fin 9, getT Gtab16 0 7 r = CF (mif MItab16) 0 7 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_0_8 : ∀ r : Fin 9, getT Gtab16 0 8 r = CF (mif MItab16) 0 8 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_1_0 : ∀ r : Fin 9, getT Gtab16 1 0 r = CF (mif MItab16) 1 0 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_1_1 : ∀ r : Fin 9, getT Gtab16 1 1 r = CF (mif MItab16) 1 1 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_1_2 : ∀ r : Fin 9, getT Gtab16 1 2 r = CF (mif MItab16) 1 2 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_1_3 : ∀ r : Fin 9, getT Gtab16 1 3 r = CF (mif MItab16) 1 3 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_1_4 : ∀ r : Fin 9, getT Gtab16 1 4 r = CF (mif MItab16) 1 4 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_1_5 : ∀ r : Fin 9, getT Gtab16 1 5 r = CF (mif MItab16) 1 5 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_1_6 : ∀ r : Fin 9, getT Gtab16 1 6 r = CF (mif MItab16) 1 6 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_1_7 : ∀ r : Fin 9, getT Gtab16 1 7 r = CF (mif MItab16) 1 7 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_1_8 : ∀ r : Fin 9, getT Gtab16 1 8 r = CF (mif MItab16) 1 8 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_2_0 : ∀ r : Fin 9, getT Gtab16 2 0 r = CF (mif MItab16) 2 0 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_2_1 : ∀ r : Fin 9, getT Gtab16 2 1 r = CF (mif MItab16) 2 1 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_2_2 : ∀ r : Fin 9, getT Gtab16 2 2 r = CF (mif MItab16) 2 2 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_2_3 : ∀ r : Fin 9, getT Gtab16 2 3 r = CF (mif MItab16) 2 3 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_2_4 : ∀ r : Fin 9, getT Gtab16 2 4 r = CF (mif MItab16) 2 4 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_2_5 : ∀ r : Fin 9, getT Gtab16 2 5 r = CF (mif MItab16) 2 5 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_2_6 : ∀ r : Fin 9, getT Gtab16 2 6 r = CF (mif MItab16) 2 6 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_2_7 : ∀ r : Fin 9, getT Gtab16 2 7 r = CF (mif MItab16) 2 7 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_2_8 : ∀ r : Fin 9, getT Gtab16 2 8 r = CF (mif MItab16) 2 8 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_3_0 : ∀ r : Fin 9, getT Gtab16 3 0 r = CF (mif MItab16) 3 0 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_3_1 : ∀ r : Fin 9, getT Gtab16 3 1 r = CF (mif MItab16) 3 1 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_3_2 : ∀ r : Fin 9, getT Gtab16 3 2 r = CF (mif MItab16) 3 2 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_3_3 : ∀ r : Fin 9, getT Gtab16 3 3 r = CF (mif MItab16) 3 3 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_3_4 : ∀ r : Fin 9, getT Gtab16 3 4 r = CF (mif MItab16) 3 4 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_3_5 : ∀ r : Fin 9, getT Gtab16 3 5 r = CF (mif MItab16) 3 5 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_3_6 : ∀ r : Fin 9, getT Gtab16 3 6 r = CF (mif MItab16) 3 6 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_3_7 : ∀ r : Fin 9, getT Gtab16 3 7 r = CF (mif MItab16) 3 7 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_3_8 : ∀ r : Fin 9, getT Gtab16 3 8 r = CF (mif MItab16) 3 8 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_4_0 : ∀ r : Fin 9, getT Gtab16 4 0 r = CF (mif MItab16) 4 0 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_4_1 : ∀ r : Fin 9, getT Gtab16 4 1 r = CF (mif MItab16) 4 1 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_4_2 : ∀ r : Fin 9, getT Gtab16 4 2 r = CF (mif MItab16) 4 2 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_4_3 : ∀ r : Fin 9, getT Gtab16 4 3 r = CF (mif MItab16) 4 3 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_4_4 : ∀ r : Fin 9, getT Gtab16 4 4 r = CF (mif MItab16) 4 4 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_4_5 : ∀ r : Fin 9, getT Gtab16 4 5 r = CF (mif MItab16) 4 5 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_4_6 : ∀ r : Fin 9, getT Gtab16 4 6 r = CF (mif MItab16) 4 6 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_4_7 : ∀ r : Fin 9, getT Gtab16 4 7 r = CF (mif MItab16) 4 7 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_4_8 : ∀ r : Fin 9, getT Gtab16 4 8 r = CF (mif MItab16) 4 8 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_5_0 : ∀ r : Fin 9, getT Gtab16 5 0 r = CF (mif MItab16) 5 0 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_5_1 : ∀ r : Fin 9, getT Gtab16 5 1 r = CF (mif MItab16) 5 1 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_5_2 : ∀ r : Fin 9, getT Gtab16 5 2 r = CF (mif MItab16) 5 2 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_5_3 : ∀ r : Fin 9, getT Gtab16 5 3 r = CF (mif MItab16) 5 3 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_5_4 : ∀ r : Fin 9, getT Gtab16 5 4 r = CF (mif MItab16) 5 4 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_5_5 : ∀ r : Fin 9, getT Gtab16 5 5 r = CF (mif MItab16) 5 5 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_5_6 : ∀ r : Fin 9, getT Gtab16 5 6 r = CF (mif MItab16) 5 6 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_5_7 : ∀ r : Fin 9, getT Gtab16 5 7 r = CF (mif MItab16) 5 7 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_5_8 : ∀ r : Fin 9, getT Gtab16 5 8 r = CF (mif MItab16) 5 8 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_6_0 : ∀ r : Fin 9, getT Gtab16 6 0 r = CF (mif MItab16) 6 0 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_6_1 : ∀ r : Fin 9, getT Gtab16 6 1 r = CF (mif MItab16) 6 1 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_6_2 : ∀ r : Fin 9, getT Gtab16 6 2 r = CF (mif MItab16) 6 2 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_6_3 : ∀ r : Fin 9, getT Gtab16 6 3 r = CF (mif MItab16) 6 3 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_6_4 : ∀ r : Fin 9, getT Gtab16 6 4 r = CF (mif MItab16) 6 4 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_6_5 : ∀ r : Fin 9, getT Gtab16 6 5 r = CF (mif MItab16) 6 5 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_6_6 : ∀ r : Fin 9, getT Gtab16 6 6 r = CF (mif MItab16) 6 6 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_6_7 : ∀ r : Fin 9, getT Gtab16 6 7 r = CF (mif MItab16) 6 7 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_6_8 : ∀ r : Fin 9, getT Gtab16 6 8 r = CF (mif MItab16) 6 8 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_7_0 : ∀ r : Fin 9, getT Gtab16 7 0 r = CF (mif MItab16) 7 0 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_7_1 : ∀ r : Fin 9, getT Gtab16 7 1 r = CF (mif MItab16) 7 1 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_7_2 : ∀ r : Fin 9, getT Gtab16 7 2 r = CF (mif MItab16) 7 2 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_7_3 : ∀ r : Fin 9, getT Gtab16 7 3 r = CF (mif MItab16) 7 3 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_7_4 : ∀ r : Fin 9, getT Gtab16 7 4 r = CF (mif MItab16) 7 4 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_7_5 : ∀ r : Fin 9, getT Gtab16 7 5 r = CF (mif MItab16) 7 5 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_7_6 : ∀ r : Fin 9, getT Gtab16 7 6 r = CF (mif MItab16) 7 6 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_7_7 : ∀ r : Fin 9, getT Gtab16 7 7 r = CF (mif MItab16) 7 7 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_7_8 : ∀ r : Fin 9, getT Gtab16 7 8 r = CF (mif MItab16) 7 8 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_8_0 : ∀ r : Fin 9, getT Gtab16 8 0 r = CF (mif MItab16) 8 0 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_8_1 : ∀ r : Fin 9, getT Gtab16 8 1 r = CF (mif MItab16) 8 1 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_8_2 : ∀ r : Fin 9, getT Gtab16 8 2 r = CF (mif MItab16) 8 2 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_8_3 : ∀ r : Fin 9, getT Gtab16 8 3 r = CF (mif MItab16) 8 3 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_8_4 : ∀ r : Fin 9, getT Gtab16 8 4 r = CF (mif MItab16) 8 4 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_8_5 : ∀ r : Fin 9, getT Gtab16 8 5 r = CF (mif MItab16) 8 5 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_8_6 : ∀ r : Fin 9, getT Gtab16 8 6 r = CF (mif MItab16) 8 6 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_8_7 : ∀ r : Fin 9, getT Gtab16 8 7 r = CF (mif MItab16) 8 7 r := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem Gtab16_eq_8_8 : ∀ r : Fin 9, getT Gtab16 8 8 r = CF (mif MItab16) 8 8 r := by
  decide +kernel

theorem Gtab16_eq : ∀ p q r : Fin 9, getT Gtab16 p q r = CF (mif MItab16) p q r := by
  intro p q
  fin_cases p <;> fin_cases q
  exacts [Gtab16_eq_0_0,
    Gtab16_eq_0_1,
    Gtab16_eq_0_2,
    Gtab16_eq_0_3,
    Gtab16_eq_0_4,
    Gtab16_eq_0_5,
    Gtab16_eq_0_6,
    Gtab16_eq_0_7,
    Gtab16_eq_0_8,
    Gtab16_eq_1_0,
    Gtab16_eq_1_1,
    Gtab16_eq_1_2,
    Gtab16_eq_1_3,
    Gtab16_eq_1_4,
    Gtab16_eq_1_5,
    Gtab16_eq_1_6,
    Gtab16_eq_1_7,
    Gtab16_eq_1_8,
    Gtab16_eq_2_0,
    Gtab16_eq_2_1,
    Gtab16_eq_2_2,
    Gtab16_eq_2_3,
    Gtab16_eq_2_4,
    Gtab16_eq_2_5,
    Gtab16_eq_2_6,
    Gtab16_eq_2_7,
    Gtab16_eq_2_8,
    Gtab16_eq_3_0,
    Gtab16_eq_3_1,
    Gtab16_eq_3_2,
    Gtab16_eq_3_3,
    Gtab16_eq_3_4,
    Gtab16_eq_3_5,
    Gtab16_eq_3_6,
    Gtab16_eq_3_7,
    Gtab16_eq_3_8,
    Gtab16_eq_4_0,
    Gtab16_eq_4_1,
    Gtab16_eq_4_2,
    Gtab16_eq_4_3,
    Gtab16_eq_4_4,
    Gtab16_eq_4_5,
    Gtab16_eq_4_6,
    Gtab16_eq_4_7,
    Gtab16_eq_4_8,
    Gtab16_eq_5_0,
    Gtab16_eq_5_1,
    Gtab16_eq_5_2,
    Gtab16_eq_5_3,
    Gtab16_eq_5_4,
    Gtab16_eq_5_5,
    Gtab16_eq_5_6,
    Gtab16_eq_5_7,
    Gtab16_eq_5_8,
    Gtab16_eq_6_0,
    Gtab16_eq_6_1,
    Gtab16_eq_6_2,
    Gtab16_eq_6_3,
    Gtab16_eq_6_4,
    Gtab16_eq_6_5,
    Gtab16_eq_6_6,
    Gtab16_eq_6_7,
    Gtab16_eq_6_8,
    Gtab16_eq_7_0,
    Gtab16_eq_7_1,
    Gtab16_eq_7_2,
    Gtab16_eq_7_3,
    Gtab16_eq_7_4,
    Gtab16_eq_7_5,
    Gtab16_eq_7_6,
    Gtab16_eq_7_7,
    Gtab16_eq_7_8,
    Gtab16_eq_8_0,
    Gtab16_eq_8_1,
    Gtab16_eq_8_2,
    Gtab16_eq_8_3,
    Gtab16_eq_8_4,
    Gtab16_eq_8_5,
    Gtab16_eq_8_6,
    Gtab16_eq_8_7,
    Gtab16_eq_8_8]

/-- The 24 entries. -/
def col16 : List Itv :=
  [⟨-695011880532, 695011880520⟩,
    ⟨-7287407671699454825687341526320970900267, -7287407671699454825687341525662210680613⟩,
    ⟨1779926546464575609386507630526301233507, 1779926546464575609386507630739625982556⟩,
    ⟨14295487866914605723139533780016867211263, 14295487866914605723139533781792214569946⟩,
    ⟨1254227231257139574092498526787870892209, 1254227231257139574092498526848665751268⟩,
    ⟨-11902194888597821760072891527254243372097, -11902194888597821760072891526791158946942⟩,
    ⟨928642876551709032495217444718841800756, 928642876551709032495217446302507512339⟩,
    ⟨-17985810555766481593180530639059642160967, -17985810555766481593180530626654545068555⟩,
    ⟨-2421101924364368561867227664571184587944, -2421101924364368561867227664235496016704⟩,
    ⟨-114577082736489528548616805976641208546283, -114577082736489528548616805974927081956046⟩,
    ⟨-51382709337683862089905251865520912163272, -51382709337683862089905251864439705245514⟩,
    ⟨2870580162139670373366401916230910577414, 2870580162139670373366401916309874008711⟩,
    ⟨-21974621385207885745738039010423151601309, -21974621385207885745738039009936324101088⟩,
    ⟨8219934538812317878826407208626921650643, 8219934538812317878826407208939039059256⟩,
    ⟨-1747011311956205704025425484985246428836, -1747011311956205704025425484940577325468⟩,
    ⟨22041241370969879003341962556948828539732, 22041241370969879003341962557231188428342⟩,
    ⟨-11135241628468057294492540401629136908167, -11135241628468057294492540401441273022840⟩,
    ⟨-10579768200231068781062958364475037393469, -10579768200231068781062958364286210093790⟩,
    ⟨-770674705611201869191575110770167921269, -770674705611201869191575110757630286422⟩,
    ⟨-6702956988874105916936912987382835907808, -6702956988874105916936912987305822037168⟩,
    ⟨98615908854560012418550003920373839021, 98615908854560012418550003977975701147⟩,
    ⟨-1254272409092348824142317523283232152073, -1254272409092348824142317523279776225453⟩,
    ⟨5130912138563307996240153683487601944902, 5130912138563307996240153683507838957987⟩,
    ⟨2033302776040672760737343121313437972984, 2033302776040672760737343121332695815681⟩]

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col16_eq00 : col16.getD 0 Itv.zero = entAt (getT Gtab16) 0 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col16_eq01 : col16.getD 1 Itv.zero = entAt (getT Gtab16) 1 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col16_eq02 : col16.getD 2 Itv.zero = entAt (getT Gtab16) 2 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col16_eq03 : col16.getD 3 Itv.zero = entAt (getT Gtab16) 3 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col16_eq04 : col16.getD 4 Itv.zero = entAt (getT Gtab16) 4 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col16_eq05 : col16.getD 5 Itv.zero = entAt (getT Gtab16) 5 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col16_eq06 : col16.getD 6 Itv.zero = entAt (getT Gtab16) 6 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col16_eq07 : col16.getD 7 Itv.zero = entAt (getT Gtab16) 7 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col16_eq08 : col16.getD 8 Itv.zero = entAt (getT Gtab16) 8 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col16_eq09 : col16.getD 9 Itv.zero = entAt (getT Gtab16) 9 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col16_eq10 : col16.getD 10 Itv.zero = entAt (getT Gtab16) 10 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col16_eq11 : col16.getD 11 Itv.zero = entAt (getT Gtab16) 11 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col16_eq12 : col16.getD 12 Itv.zero = entAt (getT Gtab16) 12 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col16_eq13 : col16.getD 13 Itv.zero = entAt (getT Gtab16) 13 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col16_eq14 : col16.getD 14 Itv.zero = entAt (getT Gtab16) 14 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col16_eq15 : col16.getD 15 Itv.zero = entAt (getT Gtab16) 15 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col16_eq16 : col16.getD 16 Itv.zero = entAt (getT Gtab16) 16 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col16_eq17 : col16.getD 17 Itv.zero = entAt (getT Gtab16) 17 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col16_eq18 : col16.getD 18 Itv.zero = entAt (getT Gtab16) 18 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col16_eq19 : col16.getD 19 Itv.zero = entAt (getT Gtab16) 19 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col16_eq20 : col16.getD 20 Itv.zero = entAt (getT Gtab16) 20 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col16_eq21 : col16.getD 21 Itv.zero = entAt (getT Gtab16) 21 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col16_eq22 : col16.getD 22 Itv.zero = entAt (getT Gtab16) 22 := by
  decide +kernel

set_option maxHeartbeats 0 in
set_option maxRecDepth 100000 in
theorem col16_eq23 : col16.getD 23 Itv.zero = entAt (getT Gtab16) 23 := by
  decide +kernel

theorem col16_eq : ∀ i : Fin 24, col16.getD (i : ℕ) Itv.zero = entAt (getT Gtab16) (i : ℕ) := by
  intro i
  fin_cases i
  exacts [col16_eq00,
    col16_eq01,
    col16_eq02,
    col16_eq03,
    col16_eq04,
    col16_eq05,
    col16_eq06,
    col16_eq07,
    col16_eq08,
    col16_eq09,
    col16_eq10,
    col16_eq11,
    col16_eq12,
    col16_eq13,
    col16_eq14,
    col16_eq15,
    col16_eq16,
    col16_eq17,
    col16_eq18,
    col16_eq19,
    col16_eq20,
    col16_eq21,
    col16_eq22,
    col16_eq23]

theorem ITMem_Gtab16 : ITMem (getT Gtab16) (cG 16) :=
  ITMem_getT_G MItab16_eq Gtab16_eq

theorem mem_col16 (i : Fin 24) : (col16.getD (i : ℕ) Itv.zero).Mem (pivotMatrix i 16) := by
  rw [col16_eq]; exact mem_entAt ITMem_Gtab16 i

end Thomson.Task1b
