"""[Tri5b] Cut the covering tree into kernel-sized pieces and emit the Lean files of `Thomson/TriangleGlobal/Covering/`.

`decide +kernel` checks one group of at most `group_leaves` leaves per theorem (memory and time
grow faster than linearly with the size of a group: 4 leaves ≈ 17 s and 2 GB, 32 leaves ≈ 10 min
and 8 GB), and one file holds a subtree of at most `file_leaves` leaves so that `lake` can build
the ≈ 640 files in parallel.  Usage: `python tri5b_kparts.py [file_leaves=128] [group_leaves=4]`."""
import sys, pickle, os
import os
S = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, S)
sys.setrecursionlimit(100000)
import tri5b_kmirror as K
import tri5b_cubes as CU
CUBE = CU.CUBE
SCALE = K.SCALE
UHI = 107474839 * 5 * 10 ** 31
ROOT = (-SCALE, UHI, -SCALE, UHI, -SCALE, UHI)
bits = pickle.load(open(os.path.join(S, 'tri5b_tree2.pkl'), 'rb'))['bits']

def replay():
    pos = 0
    def go(b):
        nonlocal pos
        start = pos
        x = bits[pos]; pos += 1
        if x == 0:
            return {'box': b, 'start': start, 'end': pos, 'leaves': 1, 'kids': None}
        ax = K.splitAxis(b); m = K.splitPoint(CUBE, b, ax)
        lo = go(K.lower(b, ax, m)); hi = go(K.upper(b, ax, m))
        return {'box': b, 'start': start, 'end': pos, 'leaves': lo['leaves'] + hi['leaves'],
                'kids': (ax, m, lo, hi)}
    root = go(ROOT)
    assert pos == len(bits)
    return root

def frontier(node, maxleaves, out):
    if node['leaves'] <= maxleaves or node['kids'] is None:
        out.append(node); return
    frontier(node['kids'][2], maxleaves, out); frontier(node['kids'][3], maxleaves, out)

def slice_nat(s, e):
    n = 0
    for i, x in enumerate(bits[s:e]): n |= x << i
    return n | (1 << (e - s))

def bx(b): return "⟨%d, %d, %d, %d, %d, %d⟩" % b

def group_decls(node, name):
    return ('def box_%s : Bx := %s\n\ndef cert_%s : ℕ :=\n  %d\n\n'
            'set_option maxHeartbeats 0 in\nset_option maxRecDepth 100000 in\n'
            'theorem ok_%s : kbcheck CFtabL MG cubeD FUEL cert_%s box_%s = some 1 := by decide +kernel\n\n'
            % (name, bx(node['box']), name, slice_nat(node['start'], node['end']), name, name, name))

def term(node, index, leaf_term):
    if id(node) in index:
        return leaf_term(index[id(node)])
    ax, m, lo, hi = node['kids']
    return "covers_split %d (%d)\n    (%s)\n    (%s)" % (ax, m, term(lo, index, leaf_term), term(hi, index, leaf_term))

HEADER = '''-- GENERATED by scripts/threepoint/tri5b_kparts.py; do not edit
import Thomson.TriangleGlobal.KernelLeaf
import Thomson.TriangleGlobal.KernelTable
import Thomson.TriangleGlobal.Params

/-! # Task 5b: piece %d of the covering, kernel-checked — GENERATED

`%d` leaves of the tree in `%d` groups, over the box below.  Each group is one `decide +kernel`. -/

namespace Thomson.TriangleGlobal.Covering.Part%03d

open Thomson.Tri5b

'''

def emit(file_leaves, group_leaves, outdir=os.path.join(S, '..', '..', 'Thomson', 'TriangleGlobal', 'Covering')):
    root = replay()
    files = []
    frontier(root, file_leaves, files)
    files.sort(key=lambda n: -n['leaves'])
    findex = {id(n): k for k, n in enumerate(files)}
    print("%d files, leaves min %d max %d total %d" % (len(files), min(n['leaves'] for n in files),
          max(n['leaves'] for n in files), sum(n['leaves'] for n in files)))
    ngroups = 0
    for k, fnode in enumerate(files):
        groups = []
        frontier(fnode, group_leaves, groups)
        gindex = {id(n): g for g, n in enumerate(groups)}
        ngroups += len(groups)
        src = HEADER % (k, fnode['leaves'], len(groups), k)
        for g, gnode in enumerate(groups):
            src += group_decls(gnode, "%d" % g)
        src += ('set_option maxRecDepth 100000 in\n'
                '/-- The covering of this piece\'s box. -/\n'
                'theorem cover {c : RT} (hC : Mem3 CFtabL (ofRT c)) {ρ : Fin 5 → ℝ} (hD : CubeSound cubeD ρ) :\n'
                '    Covers c MG ρ (%s) :=\n  %s\n\nend Thomson.TriangleGlobal.Covering.Part%03d\n'
                % (bx(fnode['box']),
                   term(fnode, gindex, lambda g: "covers_of_kbcheck hC hD FUEL cert_%d box_%d 1 ok_%d" % (g, g, g)),
                   k))
        open(os.path.join(outdir, 'Part%03d.lean' % k), 'w').write(src)
    cert = ('-- GENERATED by scripts/threepoint/tri5b_kparts.py; do not edit\n' +
            "".join('import Thomson.TriangleGlobal.Covering.Part%03d\n' % k for k in range(len(files))) +
            '''
/-! # Task 5b: the covering, recombined — GENERATED

The `%d` pieces of the covering (`Covering/Part000` … `Part%03d`, `%d` leaves, `%d` kernel checks),
put back together with `covers_split`. -/

namespace Thomson.Tri5b

set_option maxRecDepth 100000 in
/-- **The covering of the root box.** -/
theorem kcert_cover {c : RT} (hC : Mem3 CFtabL (ofRT c)) {ρ : Fin 5 → ℝ} (hD : CubeSound cubeD ρ) :
    Covers c MG ρ rootBx :=
  %s

end Thomson.Tri5b
''' % (len(files), len(files) - 1, root['leaves'], ngroups,
       term(root, findex, lambda k: "Thomson.TriangleGlobal.Covering.Part%03d.cover hC hD" % k)))
    open(os.path.join(outdir, 'Certificate.lean'), 'w').write(cert)
    print("groups:", ngroups)
    return files

if __name__ == '__main__':
    emit(int(sys.argv[1]) if len(sys.argv) > 1 else 128, int(sys.argv[2]) if len(sys.argv) > 2 else 4)
