"""SUPERSEDED: the covering is now checked by `decide +kernel`; see `tri5b_kparts.py`.

[Tri5b] Cut the covering tree into independent pieces, one Lean module each.

`native_decide` runs in Lean's interpreter, at `~0.1 s` per box: the whole tree is an hour on one
core.  The covering of a box is however a *union*, so it can be cut into subtrees, each certified
by its own `native_decide` in its own module and recombined with `covers_split` — and `lake` then
builds the modules in parallel.  The cut is greedy: a subtree becomes a piece as soon as it has at
most `MAXLEAVES` leaves."""
import pickle, sys, os
import tri5b_tree as T

MAXLEAVES = 900
OUT = os.path.join(os.path.dirname(__file__), '..', 'Thomson', 'Tri5b')

def replay(bits):
    """the tree: each node is (box, start, end, nleaves, children)"""
    pos = 0
    sys.setrecursionlimit(100000)
    def go(b):
        nonlocal pos
        start = pos
        x = bits[pos]; pos += 1
        if x == 0:
            return {'box': b, 'start': start, 'end': pos, 'leaves': 1, 'kids': None}
        ax = T.splitAxis(b); m = T.splitPoint(b, ax)
        lo = go(T.lower(b, ax, m)); hi = go(T.upper(b, ax, m))
        return {'box': b, 'start': start, 'end': pos, 'leaves': lo['leaves'] + hi['leaves'],
                'kids': (ax, m, lo, hi)}
    root = go(T.ROOT)
    assert pos == len(bits), (pos, len(bits))
    return root

def frontier(node, out):
    if node['leaves'] <= MAXLEAVES or node['kids'] is None:
        out.append(node); return
    frontier(node['kids'][2], out); frontier(node['kids'][3], out)

def slice_nat(bits, s, e):
    n = 0
    for i, x in enumerate(bits[s:e]): n |= x << i
    return n | (1 << (e - s))

def bx(b):
    return "⟨%d, %d, %d, %d, %d, %d⟩" % b

def term(node, index):
    if id(node) in index:
        k = index[id(node)]
        return "covers_of_bcheck hC hD FUEL Part%03d.cert Part%03d.box 1 Part%03d.ok" % (k, k, k)
    ax, m, lo, hi = node['kids']
    return "covers_split %d (%d)\n    (%s)\n    (%s)" % (ax, m, term(lo, index), term(hi, index))

if __name__ == "__main__":
    bits = pickle.load(open(os.path.join(os.path.dirname(__file__), 'tri5b_tree2.pkl'), 'rb'))['bits']
    root = replay(bits)
    front = []
    frontier(root, front)
    front.sort(key=lambda n: -n['leaves'])          # biggest first: better load balance
    index = {id(n): k for k, n in enumerate(front)}
    print("%d pieces, leaves min %d max %d total %d"
          % (len(front), min(n['leaves'] for n in front), max(n['leaves'] for n in front),
             sum(n['leaves'] for n in front)))
    for k, n in enumerate(front):
        cert = slice_nat(bits, n['start'], n['end'])
        src = '''import Thomson.TriangleGlobal.Params

/-! # Task 5b: piece %d of the covering — GENERATED

`%d` leaves of the tree, over the box below.  Generated by `scripts/threepoint/tri5b_parts.py`. -/

namespace Thomson.Tri5b.Part%03d

open Thomson.Tri5b

def box : Bx := %s

def cert : ℕ :=
  %d

theorem ok : bcheck CFtab MG cubeD FUEL cert box = some 1 := by native_decide

end Thomson.Tri5b.Part%03d
''' % (k, n['leaves'], k, bx(n['box']), cert, k)
        open(os.path.join(OUT, 'Part%03d.lean' % k), 'w').write(src)
    imports = "\n".join("import Thomson.Tri5b.Part%03d" % k for k in range(len(front)))
    cov = '''%s

/-! # Task 5b, step 18: the covering — GENERATED

The tree of `%d` nodes (`%d` leaves) is cut into `%d` pieces, each checked by its own
`native_decide` in its own module; `covers_split` puts them back together.  Generated by
`scripts/threepoint/tri5b_parts.py`. -/

namespace Thomson.Tri5b

open Thomson

/-- **The covering.**  Every sorted triple in the root box satisfies the certificate's bound. -/
theorem cert_cover {c : RT} (hC : ITMem CFtab c) {ρ : Fin 5 → ℝ} (hD : CubeSound cubeD ρ) :
    Covers c MG ρ rootBx :=
  %s

end Thomson.Tri5b
''' % (imports, len(bits), root['leaves'], len(front), term(root, index))
        # noqa
    open(os.path.join(OUT, 'Certificate.lean'), 'w').write(cov)
    params = '''import Thomson.Tri5b.CFTable
import Thomson.TriangleGlobal.CubeData

/-! # Task 5b: the parameters of the covering — GENERATED -/

namespace Thomson.Tri5b

/-- The root box `[-1, uHi]³` on the fixed-point grid. -/
def rootBx : Bx := %s

/-- The margin certified on every box: `10⁻¹⁰`. -/
def MG : ℤ := 1000000000000000000000000000000

/-- Enough fuel: the tree is at most `%d` deep. -/
def FUEL : ℕ := 256

end Thomson.Tri5b
''' % (bx(T.ROOT), 70)
    open(os.path.join(OUT, 'Params.lean'), 'w').write(params)
    print("wrote Params.lean, %d Part files, Certificate.lean" % len(front))
