"""Generate Thomson/ThreePoint/Kernel/{Entries,Psi}<k>.lean: the kernel lemma of Task 1c.

For each block k (0..5):
  * Entries<k>.lean: AcombN k i j u = (polynomial in u, rational coefficients), for all i, j < 9-k,
    proved by `linear_combination COF * cU_sq u` (the cross-chord inner products are -u +- cU u);
  * Psi<k>.lean: psiN k a b u = (u - uStar)^2 * chi(u), for all a, b < 9-k, proved by expanding the
    sums (B is sparse: at most two nonzero rows per column) and `ring`; plus the DoubleZero
    dispatcher `psiN_dz_k : a < 9-k -> b < 9-k -> DoubleZero (psiN k a b) uStar`.
Run from the repository root: python3 threepoint/kernel_lean.py
"""
import re, itertools, sys, os
import sympy as sp

u, u0, c = sp.symbols('u u0 c')
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
src = open(os.path.join(ROOT, 'Thomson/ThreePoint/CertData.lean')).read()
body = src[src.index('def Bpoly'):src.index('/-- The basis matrices')]
Bp = {}
for m in re.finditer(r'^\s*\|\s*(\d+),\s*(\d+),\s*(\d+)\s*=>\s*(-?)\((\d+)(?:/(\d+))?\s*:\s*ℝ\)\s*\*\s*\((.*)\)\s*$', body, re.M):
    k, i, a, sg, nu, de, poly = m.groups()
    co = sp.Rational(int(nu), int(de) if de else 1) * (-1 if sg == '-' else 1)
    val = 0
    for t in re.finditer(r'\((-?\d+)\s*:\s*ℝ\)(\s*\*\s*uStar(\s*\^\s*(\d+))?)?', poly):
        cc = int(t.group(1)); p = 0 if t.group(2) is None else (1 if t.group(4) is None else int(t.group(4)))
        val += cc * u0**p
    Bp[(int(k), int(i), int(a))] = co * val
assert len(Bp) == 60

def Q3(k, x, y, z):
    X = z - x*y; Y = (1 - x**2)*(1 - y**2)
    return [1, X, 2*X**2 - Y, 4*X**3 - 3*X*Y, 8*X**4 - 8*X**2*Y + Y**2,
            16*X**5 - 20*X**3*Y + 5*X*Y**2][k]

def S3N(k, i, j, x, y, z):
    return sp.Rational(1, 6)*(x**i*y**j*Q3(k, x, y, z) + x**i*z**j*Q3(k, x, z, y)
        + y**i*x**j*Q3(k, y, x, z) + y**i*z**j*Q3(k, y, z, x)
        + z**i*x**j*Q3(k, z, x, y) + z**i*y**j*Q3(k, z, y, x))

tA = u; tD = 2*u - 1; tN = -u + c; tF = -u - c
def AcombN(k, i, j):
    return sp.expand(8*S3N(k, i, j, 1, 1, 1)
        + 48*S3N(k, i, j, 1, tA, tA) + 24*S3N(k, i, j, 1, tD, tD)
        + 48*S3N(k, i, j, 1, tN, tN) + 48*S3N(k, i, j, 1, tF, tF)
        + 48*S3N(k, i, j, tF, tF, tA) + 96*S3N(k, i, j, tF, tD, tN)
        + 96*S3N(k, i, j, tF, tN, tA) + 48*S3N(k, i, j, tD, tA, tA)
        + 48*S3N(k, i, j, tN, tN, tA))

REL = c**2 - (1 - u)**2/2
def reduce_c(e):
    p = sp.Poly(e, c); out = 0
    for (d,), co in p.terms():
        out += co * ((1 - u)**2/2)**(d//2) * (c if d % 2 else 1)
    return sp.expand(out)

def lean_rat(q):
    q = sp.Rational(q)
    return f"({q.p} : ℝ)" if q.q == 1 else f"({q.p} / {q.q} : ℝ)"

def lean_poly(e, gens, names):
    e = sp.expand(e)
    if e == 0:
        return "0"
    p = sp.Poly(e, *gens)
    parts = []
    for mon, co in p.terms():
        ms = []
        for nm, d in zip(names, mon):
            if d == 1: ms.append(nm)
            elif d > 1: ms.append(f"{nm} ^ {d}")
        parts.append(" * ".join([lean_rat(co)] + ms))
    return " + ".join(parts)

BTXT = {}
for m in re.finditer(r'^\s*\|\s*(\d+),\s*(\d+),\s*(\d+)\s*=>\s*(.*?)\s*$', body, re.M):
    BTXT[(int(m.group(1)), int(m.group(2)), int(m.group(3)))] = m.group(4)
def lean_bval(k, i, a):
    return BTXT.get((k, i, a), "0")

HDR = "-- GENERATED by threepoint/kernel_lean.py; do not edit\n"

def gen(k):
    n = 9 - k
    A = {}; Apoly = {}
    ent = [HDR + "import Thomson.ThreePoint.Kernel.Defs\n",
           f"/-! # Task 1c: the entries of `Acomb {k} u` — GENERATED\n\n"
           f"Each entry is a polynomial in `u` with rational coefficients: the `√2` of the cross chords\n"
           f"cancels (`cU_sq`). -/\n",
           "namespace Thomson\n"]
    for i in range(n):
        for a in range(n):
            ent.append(f"theorem Bpoly_{k}_{i}_{a} : Bpoly {k} {i} {a} = {lean_bval(k, i, a)} := rfl\n")
    for i in range(n):
        for j in range(n):
            raw = AcombN(k, i, j)
            red = reduce_c(raw)
            assert not red.has(c)
            q, r = sp.div(sp.Poly(sp.expand(raw - red), c), sp.Poly(REL, c))
            assert r.is_zero
            Apoly[(i, j)] = red
            if i > j:
                assert sp.expand(red - Apoly[(j, i)]) == 0
                ent.append(f"theorem AcombN_{k}_{i}_{j} (u : ℝ) : AcombN {k} {i} {j} u = {lean_poly(red, (u,), ('u',))} := by\n"
                           f"  rw [AcombN_symm]; exact AcombN_{k}_{j}_{i} u\n")
                continue
            cof = lean_poly(q.as_expr(), (u, c), ("u", "cU u"))
            ent.append(f"set_option maxHeartbeats 1000000 in\n"
                       f"theorem AcombN_{k}_{i}_{j} (u : ℝ) : AcombN {k} {i} {j} u = {lean_poly(red, (u,), ('u',))} := by\n"
                       f"  simp only [AcombN, S3N, Q3, tA, tD, tN, tF]\n"
                       f"  linear_combination ({cof}) * cU_sq u\n")
    ent.append("end Thomson\n")
    psi = [HDR + f"import Thomson.ThreePoint.Kernel.Entries{k}\n",
           f"/-! # Task 1c: the kernel lemma for the block `k = {k}` — GENERATED\n\n"
           f"`psiN {k} a b u = (u − u*)²·χ(u)` for every `a, b < {n}`. -/\n",
           "namespace Thomson\n"]
    names = {}
    for a in range(n):
        for b in range(n):
            if a > b:
                psi.append(f"theorem psiN_dz_{k}_{a}_{b} : DoubleZero (psiN {k} {a} {b}) uStar :=\n"
                           f"  psiN_dz_{k}_{b}_{a}.congr fun u => psiN_symm {k} {b} {a} u\n")
                continue
            terms = []
            for i in range(n):
                for j in range(n):
                    bi = Bp.get((k, i, a), 0); bj = Bp.get((k, j, b), 0)
                    if bi != 0 and bj != 0:
                        terms.append((i, j, bi, bj))
            psiv = sp.expand(sum(bi*Apoly[(i, j)]*bj for (i, j, bi, bj) in terms))
            if psiv == 0:
                chi = sp.Integer(0)
            else:
                qq, rr = sp.div(sp.Poly(psiv, u), sp.Poly((u - u0)**2, u))
                assert rr.is_zero, (k, a, b)
                chi = sp.expand(qq.as_expr())
            chis = lean_poly(chi, (u, u0), ("u", "uStar"))
            used = sorted(set((i, j) for (i, j, _, _) in terms))
            entries = ", ".join(f"AcombN_{k}_{i}_{j}" for (i, j) in used)
            psi.append(f"set_option maxHeartbeats 1000000 in\n"
                       f"/-- The cofactor `χ` of `psiN {k} {a} {b}`. -/\n"
                       f"noncomputable def chi_{k}_{a}_{b} (u : ℝ) : ℝ :=\n  {chis}\n")
            psi.append(f"set_option maxHeartbeats 1000000 in\n"
                       f"theorem psiN_{k}_{a}_{b} (u : ℝ) : psiN {k} {a} {b} u = (u - uStar) ^ 2 * chi_{k}_{a}_{b} u := by\n"
                       f"  simp only [psiN, Finset.sum_range_succ, Finset.sum_range_zero, "
                       + ", ".join(f"Bpoly_{k}_{i}_{a}" for i in range(n))
                       + (", " + ", ".join(f"Bpoly_{k}_{j}_{b}" for j in range(n)) if b != a else "")
                       + f",\n    zero_mul, mul_zero, zero_add, add_zero]\n"
                       + (f"  rw [{entries}]\n  unfold chi_{k}_{a}_{b}\n  ring\n" if used else f"  unfold chi_{k}_{a}_{b}\n  ring\n"))
            psi.append(f"set_option maxHeartbeats 1000000 in\n"
                       f"theorem psiN_dz_{k}_{a}_{b} : DoubleZero (psiN {k} {a} {b}) uStar :=\n"
                       f"  ⟨chi_{k}_{a}_{b}, by unfold chi_{k}_{a}_{b}; fun_prop, psiN_{k}_{a}_{b}⟩\n")
    # dispatcher
    lines = [f"theorem psiN_dz_{k} : ∀ a b : ℕ, a < {n} → b < {n} → DoubleZero (psiN {k} a b) uStar"]
    for a in range(n):
        for b in range(n):
            lines.append(f"  | {a}, {b}, _, _ => psiN_dz_{k}_{a}_{b}")
    lines.append(f"  | a + {n}, _, h, _ => absurd h (by omega)")
    lines.append(f"  | _, b + {n}, _, h => absurd h (by omega)")
    psi.append("\n".join(lines) + "\n")
    psi.append("end Thomson\n")
    d = os.path.join(ROOT, 'Thomson/ThreePoint/Kernel')
    open(os.path.join(d, f'Entries{k}.lean'), 'w').write("\n".join(ent))
    open(os.path.join(d, f'Psi{k}.lean'), 'w').write("\n".join(psi))
    print("k", k, "done", flush=True)

if __name__ == '__main__':
    ks = [int(a) for a in sys.argv[1:]] or range(6)
    for k in ks:
        gen(k)
