import Thomson.Pair.SweepFl
import Thomson.Pair.SweepFr
import Thomson.Pair.SweepDl
import Thomson.Pair.SweepDr
import Thomson.Pair.SweepNl
import Thomson.Pair.SweepNr
import Thomson.Pair.SweepAl
import Thomson.Pair.SweepAr
import Thomson.Unique.PairStrict

/-! # Uniqueness, step U3: the eight sweeps pass the strict checker

The certificate data `cellsFl … cellsAr` of `Thomson/Pair/SweepXx.lean` (generated by
`threepoint/pair_gen.py`), re-checked by the strict checker `sweepOKS` of
`Thomson.Unique.PairStrict`.  `decide +kernel` only.  The smallest lower bound for `Φ` carried by
any step is `≈ 1.5·10⁻⁸` (sweeps `Fl`, `Fr`), i.e. `≈ 10³²` on the `10⁴⁰` grid. -/

namespace Thomson.Pair

set_option maxRecDepth 1000000 in
theorem sweepFl_strict :
    sweepOKS G2tab G3tab G4tab (7991014271426985006585882053787772673902) (7991014271426985006585882053788284805937) (10000000000000000000000000000000000000000) cellsFl = true := by
  decide +kernel

set_option maxRecDepth 1000000 in
theorem sweepFr_strict :
    sweepOKS F2tab F3tab F4tab (-7991014271426985006585882053788284805937) (-7991014271426985006585882053787772673902) (-6024000000000000000000000000000000000000) cellsFr = true := by
  decide +kernel

set_option maxRecDepth 1000000 in
theorem sweepDl_strict :
    sweepOKS G2tab G3tab G4tab (3718212642215962652375334760784200000000) (3718212642215962652375334760784800000000) (6024000000000000000000000000000000000000) cellsDl = true := by
  decide +kernel

set_option maxRecDepth 1000000 in
theorem sweepDr_strict :
    sweepOKS F2tab F3tab F4tab (-3718212642215962652375334760784800000000) (-3718212642215962652375334760784200000000) (-235000000000000000000000000000000000000) cellsDr = true := by
  decide +kernel

set_option maxRecDepth 1000000 in
theorem sweepNl_strict :
    sweepOKS G2tab G3tab G4tab (-1709226913642947658961216814572784805937) (-1709226913642947658961216814572272673902) (235000000000000000000000000000000000000) cellsNl = true := by
  decide +kernel

set_option maxRecDepth 1000000 in
theorem sweepNr_strict :
    sweepOKS F2tab F3tab F4tab (1709226913642947658961216814572272673902) (1709226913642947658961216814572784805937) (2508000000000000000000000000000000000000) cellsNr = true := by
  decide +kernel

set_option maxRecDepth 1000000 in
theorem sweepAl_strict :
    sweepOKS G2tab G3tab G4tab (-3140893678892018673812332619607900000000) (-3140893678892018673812332619607600000000) (-2508000000000000000000000000000000000000) cellsAl = true := by
  decide +kernel

set_option maxRecDepth 1000000 in
theorem sweepAr_strict :
    sweepOKS F2tab F3tab F4tab (3140893678892018673812332619607600000000) (3140893678892018673812332619607900000000) (5392000000000000000000000000000000000000) cellsAr = true := by
  decide +kernel

end Thomson.Pair
